### ISSUE TITLE
Display of numeric answers in DOC view

### ISSUE THREAD

**Issue by spiegeljen** [CLOSER-Cohorts/archivist#10]
At present numeric answers show the answer's 'Numeric type' in the DOC view. it would be very useful, particularly in verification, if the DOC view showed the numeric answer's Description as well as its Numeric type.

**Comment by wpoynter** [comment]
Lets advance this to include type, label and paramters for all response domains excluding RDC

**Comment by spiegeljen** [comment]
Sounds good. What does RDC mean?

Jen

**Comment by wpoynter** [comment]
ResponseDomainCode. It means a code answer.
