### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by stevehassan** [CLOSER-Cohorts/archivist#105]
I am stuck here

C:\archivist>bundle exec puma -C config/puma.rb
Your Ruby version is 2.3.1, but your Gemfile specified 2.2.3

Trying with the version specified.

**Comment by wpoynter** [comment]
Hi @stevehassan, thanks for getting in touch.

Currently Archivist requires ruby 2.2.3. We briefly tried updating to 2.3.1 but several key gems were not ready for ruby 2.3.1.

Could you tell me what version of Archivist you are using and where the incorrect version is specified so I can fix it?

Cheers
Will

**Comment by stevehassan** [comment]
Where is the version found?
I just followed instructions today.
git clone -b master --single-branch https://github.com/CLOSER-Cohorts/archivist.git

**Comment by stevehassan** [comment]
Problem so far using Ruby 2.2.3

Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler --pre`.
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Using rake 11.2.2
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using rack 2.0.1
Installing nio4r 1.2.1 with native extensions

Gem::InstallError: The 'nio4r' native gem requires installed build tools.

Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.0
Using method_source 0.8.2
Using thor 0.19.1
Using tilt 2.0.5
Using jmespath 1.3.1
Using bcrypt 3.1.11
Using benchmark-ips 2.7.1
Installing debug_inspector 0.0.2 with native extensions

Gem::InstallError: The 'debug_inspector' native gem requires installed build tools.

Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'
Using bower-rails 0.10.0
Installing byebug 9.0.5 with native extensions

Gem::InstallError: The 'byebug' native gem requires installed build tools.

Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'
Using choice 0.2.0
Using coffee-script-source 1.10.0
Using execjs 2.7.0
Installing json 1.8.3 with native extensions

Gem::InstallError: The 'json' native gem requires installed build tools.

Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'
Using docile 1.1.5
Using simplecov-html 0.10.0
Using tins 1.6.0
Using db_fixtures_dump 0.1.1
Using get_process_mem 0.2.1
Using heapy 0.1.2
Using memory_profiler 0.9.6
Using orm_adapter 0.5.0
Using genericons-rails 0.5.0
Using hirefire-resource 0.3.11
Using multi_json 1.12.1
Using mono_logger 1.1.0
Installing oj 2.17.1 with native extensions

Gem::InstallError: The 'oj' native gem requires installed build tools.

Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'
Using parallel 1.9.0
Using pg 0.18.4
Installing puma 2.16.0 with native extensions

Gem::InstallError: The 'puma' native gem requires installed build tools.

Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'
Using rack-timeout 0.4.2
Using bundler 1.12.5
Using ruby-graphviz 1.2.2
Using rails_serve_static_assets 0.0.5
Using rails_stdout_logging 0.0.5
Using redis 3.3.1
Using sass 3.4.22
Using spring 1.7.2
Using sys-proctable 1.1.1
Using tzinfo 1.2.2
Using nokogiri 1.6.8
Using rack-test 0.6.3
Using sprockets 3.7.0
Using warden 1.2.6
Using rack-cache 1.6.1
Using sinatra 1.0
Using vegas 0.1.11
An error occurred while installing nio4r (1.2.1), and Bundler cannot continue.
Make sure that `gem install nio4r -v '1.2.1'` succeeds before bundling.

**Comment by wpoynter** [comment]
So it looks like you are using Windows which requires the Ruby Development-Kit. The easiest way to install it is to download from [http://rubyinstaller.org/downloads/](http://rubyinstaller.org/downloads/). There are two versions one for 32-bit and one for 64-bit.

**Comment by stevehassan** [comment]
Strange I did install it but before I installed the older Ruby version.

---
Steve Hassan

**Comment by stevehassan** [comment]
Getting closer. It does not seem to like the password I setup in the ENV. This is the same password I used to install Postgres.

C:\archivist>rake db:setup
FATAL:  password authentication failed for user "archivist"
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>16, "template"=>"template0", "username"=>"archivist", "password"=>"******", "database"=>"archivist_production"}
rake aborted!
PG::ConnectionBad: FATAL:  password authentication failed for user "archivist"
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `initialize'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `new'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `connect'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:217:in `initialize'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `new'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:721:in `new_connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:765:in `checkout_new_connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:744:in `try_to_checkout_new_connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:705:in `acquire_connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:501:in `checkout'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:875:in `retrieve_connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_handling.rb:91:in `connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/tasks/postgresql_database_tasks.rb:6:in `connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/tasks/postgresql_database_tasks.rb:15:in `create'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:109:in `create'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:129:in `block in create_current'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:292:in `block in each_current_configuration'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:291:in `each'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:291:in `each_current_configuration'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:128:in `create_current'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:27:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create
(See full trace by running task with --trace)

**Comment by wpoynter** [comment]
Ah, I can help here. Ruby on Rails changed the inital command between 4 and 5. It is now `rails db:migrate`.  I will update the README to reflect this.

**Comment by stevehassan** [comment]
Do I also need to install Rails?

**Comment by wpoynter** [comment]
Rails should be installed like any other gem when you run step 4. on the README (`bundle install`)

**Comment by stevehassan** [comment]
Strange I had to install it manually to get the command to work.
Next problem with the migrate command:

C:\archivist>rails db:migrate
E, [2016-08-30T11:41:55.652778 #88] ERROR -- : [SKYLIGHT] [0.10.5] The Skylight native extension for your platform wasn't found. Supported operating systems are Linux 2.6.18+ and Mac OS X 10.8+. The missing extension w
form, please contact support at support@skylight.io.
[SKYLIGHT] [0.10.5] Unable to start
Redis is NOT connected.
rails aborted!
Devise.secret_key was not set. Please add the following to your Devise initializer:

  config.secret_key = 'a8052a81ae030e06ffb56cfd1597ba9a0d36051e3b0a7d621f444bc5142c3adaac80647c1d9af9ba6a41d7023d73a07ca4472d4c5370da859f931ccb1ae34d79'

Please ensure you restarted your application after installing Devise or setting the key.
C:/archivist/vendor/bundle/ruby/2.2.0/gems/devise-4.2.0/lib/devise/rails/routes.rb:498:in `raise_no_secret_key'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/devise-4.2.0/lib/devise/rails/routes.rb:226:in `devise_for'
C:/archivist/config/routes.rb:4:in `block in <top (required)>'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0/lib/action_dispatch/routing/route_set.rb:389:in `instance_exec'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0/lib/action_dispatch/routing/route_set.rb:389:in `eval_block'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0/lib/action_dispatch/routing/route_set.rb:371:in `draw'
C:/archivist/config/routes.rb:1:in `<top (required)>'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/application/routes_reloader.rb:40:in `each'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/application/routes_reloader.rb:40:in `load_paths'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/application/routes_reloader.rb:16:in `reload!'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/application/routes_reloader.rb:26:in `block in updater'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/application/routes_reloader.rb:27:in `updater'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/application/finisher.rb:119:in `block in <module:Finisher>'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `instance_exec'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/initializable.rb:54:in `run_initializers'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/application.rb:352:in `initialize!'
C:/archivist/config/environment.rb:5:in `<top (required)>'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/skylight-0.10.5/lib/skylight/probes.rb:81:in `require'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/skylight-0.10.5/lib/skylight/probes.rb:81:in `require'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/application.rb:328:in `require_environment!'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/application.rb:448:in `block in run_tasks_blocks'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:9:in `require'
bin/rails:9:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

**Comment by stevehassan** [comment]
I added the key and now get the following:

C:\archivist>
C:\archivist>rails db:migrate
E, [2016-08-30T11:53:36.365022 #3196] ERROR -- : [SKYLIGHT] [0.10.5] The Skylight native extension for your platform wasn't found. Supported operating systems are Linux 2.6.18+ and Mac OS X 10.8+. The missing extension will not affect the functioning of your application. If you are on a supported pl
atform, please contact support at support@skylight.io.
[SKYLIGHT] [0.10.5] Unable to start
Redis is NOT connected.
rails aborted!
PG::ConnectionBad: FATAL:  password authentication failed for user "archivist"
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `initialize'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `new'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `connect'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:217:in `initialize'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `new'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:721:in `new_connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:765:in `checkout_new_connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:744:in `try_to_checkout_new_connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:705:in `acquire_connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:501:in `checkout'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:875:in `retrieve_connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_handling.rb:91:in `connection'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/migration.rb:1099:in `initialize'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/migration.rb:1005:in `new'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/migration.rb:1005:in `up'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/migration.rb:983:in `migrate'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:9:in `require'
bin/rails:9:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by wpoynter** [comment]
Just looking at this now. I am also slightly bemused that you were asked to add the secret, but I was not on my Windows build. So I will check that out separately.

**Comment by wpoynter** [comment]
If I am right, you should be able to create the user by typing `createuser -d -P archivist` into command prompt. Then type the password as 'farandwide', which is only safe for local development obviously. If this is a production version, instead use a strong password and set it as the enviroment varuiable `ARCHIVIST_DATABASE_PASSWORD`.

**Comment by stevehassan** [comment]
I get this (had to change order)

C:\archivist>"C:\Program Files\PostgreSQL\9.4\bin\PSQL"  createuser archivist  -d -P
PSQL: warning: extra command-line argument "-d" ignored
PSQL: warning: extra command-line argument "-P" ignored
Password for user archivist:
PSQL: FATAL:  password authentication failed for user "archivist"

**Comment by wpoynter** [comment]
Sorry, I edited the command about a minute after I posted it, as I realised that my configuration would be settting the login user. Can you try `createuser -U postgres -d -P archivist`

**Comment by stevehassan** [comment]
It just does not seem to like those flags. I found this
http://support.esri.com/technical-article/000010234

**Comment by stevehassan** [comment]
Maybe closer:

postgres=# CREATE ROLE archivist LOGIN PASSWORD 'ARCHIVIST' CREATEDB;
CREATE ROLE
postgres=# \q

C:\archivist>"C:\Program Files\PostgreSQL\9.4\bin\PSQL"  -U archivist
Password for user archivist:
PSQL: FATAL:  database "archivist" does not exist

**Comment by wpoynter** [comment]
If the user `archivist` now exists. Rails should create the database for you. Then you can connect using `rails dbconsole` or `psql -U archivist archivist_development`

**Comment by stevehassan** [comment]
I am using production, looks like I need to create the database manually:

C:\archivist>rails db:migrate
E, [2016-08-30T13:15:29.803962 #1420] ERROR -- : [SKYLIGHT] [0.10.5] The Skylight native extension for your platform wasn't found. Supported operating systems are Linux 2.6.18+ and Mac OS X 10.8+. The missing extension will not affect the functioning of your application. If you are on a suppor
atform, please contact support at support@skylight.io.
[SKYLIGHT] [0.10.5] Unable to start
Redis is NOT connected.
rails aborted!
ActiveRecord::NoDatabaseError: FATAL:  database "archivist_production" does not exist

**Comment by stevehassan** [comment]
The migrate command now seems to have worked after creating the database manually.

**Comment by stevehassan** [comment]
Error starting:

C:\archivist>bundle exec puma -C config/puma.rb
[5256] *** SIGUSR2 not implemented, signal based restart unavailable!
[5256] *** SIGUSR1 not implemented, signal based restart unavailable!
[5256] *** SIGHUP not implemented, signal based logs reopening unavailable!
[5256] Puma starting in cluster mode...
[5256] * Version 2.16.0 (ruby 2.2.3-p173), codename: Midwinter Nights Trance
[5256] * Min threads: 5, max threads: 5
[5256] * Environment: development
[5256] * Process workers: 2
[5256] * Preloading application
E, [2016-08-30T13:43:37.899147 #5256] ERROR -- : [SKYLIGHT] [0.10.5] The Skylight native extension for your platform wasn't found. Supported operating systems are Linux 2.6.18+ and Mac OS X 10.8+. The missing extension will not affect the functioning of your application. If you are on a supported pl
atform, please contact support at support@skylight.io.
[SKYLIGHT] [0.10.5] Unable to start
Redis is NOT connected.
[5256] * Listening on tcp://0.0.0.0:3000
C:/archivist/vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/cluster.rb:346:in `trap': unsupported signal SIGCHLD (ArgumentError)
        from C:/archivist/vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/cluster.rb:346:in `run'
        from C:/archivist/vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/cli.rb:214:in `run'
        from C:/archivist/vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/bin/puma:10:in `<top (required)>'
        from C:/archivist/vendor/bundle/ruby/2.2.0/bin/puma:23:in `load'
        from C:/archivist/vendor/bundle/ruby/2.2.0/bin/puma:23:in `<main>'

**Comment by stevehassan** [comment]
Fixed that following advice from http://stackoverflow.com/questions/20801734/error-while-starting-puma-server-with-workers

**Comment by stevehassan** [comment]
Started up and browser gives this error

Puma caught this error: Missing `secret_key_base` for 'production' environment, set this value in `config/secrets.yml` (RuntimeError)
C:/archivist/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/application.rb:513:in `validate_secret_key_config!'

**Comment by wpoynter** [comment]
Ok, we are nearly there. For a production environment you need to set the environment variable `SECRET_KEY_BASE`. A strong secret can be generated using `rails secret`.

**Comment by stevehassan** [comment]
I just copied the existing key from development and it's working!
Just one question, why does it say Environment: development when it boots up despite setting it to production in the ENV?
Also noticed these errors in the command line
cache error: Error connecting to Redis on 127.0.0.1:6379 (Redis::TimeoutError)

**Comment by wpoynter** [comment]
Can I see the command you are starting the server with? It may be that Rails and Rack (the middleware server software) are running two different environments. I.e. one is running in development mode and one in production mode.

**Comment by stevehassan** [comment]
bundle exec puma -C config/puma.rb

**Comment by stevehassan** [comment]
Ok I have changed it there

environment ENV['RACK_ENV'] || 'production'

**Comment by wpoynter** [comment]
That should put both of them on the same page. I am going to try and right a lot of this thread into the README

**Comment by stevehassan** [comment]
What about the (Redis::TimeoutError)?

**Comment by wpoynter** [comment]
Ah, I am assumeing you have not installed Redis? 

If you have, Archivist should default to connecting to the localhost on the default Redis port with no password.

## config/initializers/redis.rb
`$redis = Redis.new(url: ENV["REDIS_URL"] || 'redis://127.0.0.1:6379/0')`

**Comment by stevehassan** [comment]
I thought I did. That setup is correct for me.

**Comment by stevehassan** [comment]
I installed it as a GEM like this:

gem install redis -v 3.0.7

**Comment by wpoynter** [comment]
Ah, that is the gem that allows communication with a Redis server. Redis is a standalone server. It is not essential for most Archivist features, but does provide significant speed increases. If you would like to install it on Windows I recommend https://github.com/MSOpenTech/redis/releases. I am using `3.0.501`, but any version 3 should be fine.

**Comment by stevehassan** [comment]
Is there a way to run puma as a service so I don't need to run it in a command line as me?

**Comment by wpoynter** [comment]
I am not aware of a method. I am much more of a linux expert. If you find a simple method I would be keen to hear about it. 

I am also trying to generate a windows installer that takes care of much of this automatically,

**Comment by stevehassan** [comment]
Ok thanks for all of your help!
