### ISSUE TITLE
Send mail not working for user registration

### ISSUE THREAD

**Issue by stevehassan** [CLOSER-Cohorts/archivist#106]
Log:

Processing by Users::RegistrationsController#create as JSON
  Parameters: {"user"=>{"first_name"=>"Steve", "last_name"=>"Hassan", "group_id"=>1, "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "registration"=>{"user"=>{"first_name"=>"Steve", "last_name"=>"Hassan", "group_id"=>1, "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]
"}}}
source=rack-timeout id=45f605744bc8097b38440596c6feb707 timeout=25000ms service=200ms state=active
   (0.0ms)  BEGIN
   (0.0ms)  ROLLBACK
  Group Load (0.0ms)  SELECT  "groups".\* FROM "groups" WHERE "groups"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]](0.0ms)  BEGIN
   (0.0ms)  COMMIT
Completed 422 Unprocessable Entity in 219ms (Views: 0.4ms | ActiveRecord: 0.0ms)
source=rack-timeout id=45f605744bc8097b38440596c6feb707 timeout=25000ms service=231ms state=completed
cache: [POST /users.json] invalidate, pass

**Comment by wpoynter** [comment]
Was the sign up working before Redis was started?

**Comment by stevehassan** [comment]
My boss (John Shepherdson) said he has not tried Sign-in but the Sign-up did work.

**Comment by stevehassan** [comment]
It does not make any difference if I stop Redis.

**Comment by wpoynter** [comment]
Could you send me the result of querying this URL `/groups/external.json`

**Comment by stevehassan** [comment]
[{"id":1,"label":"Technical"}]

**Comment by wpoynter** [comment]
I am just reconfiguring my development environment to see if I can replicate the error.

**Comment by wpoynter** [comment]
I can only get it to work or give me an error 500.

When you first ran Archivist it will have asked you to create superuser (& supergroup). Can the superuser login?

**Comment by stevehassan** [comment]
No.

**Comment by wpoynter** [comment]
Ah! A recent update is surpressing the authentication errors. I will write a fix for that.

Until then, make sure both password and confirmation match, that the password is at least 8 characters long and that the email address has not been used before.

**Comment by stevehassan** [comment]
Shall I empty the user and groups tables?

**Comment by wpoynter** [comment]
If you can see the Users table, could you check the confirmed_at value? If it is NULL, setting it to a time, e.g. the created_at time, it may fix the issue.

**Comment by stevehassan** [comment]
Set that and now I get 500 error:

Processing by Users::RegistrationsController#create as JSON
  Parameters: {"user"=>{"email"=>"steveh@essex.ac.uk", "first_name"=>"Steve", "last_name"=>"Hassan", "group_id"=>1, "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "registration"=>{"user"=>{"email"=>"steveh@essex.ac.uk", "first_name"=>"Steve", "last_name"=>"Hassan", "group_id"=>1,
"password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}}}
source=rack-timeout id=996f80a3a77b2c2887c188e47f3076f6 timeout=25000ms service=203ms state=active
   (0.0ms)  BEGIN
  User Exists (0.0ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "steveh@essex.ac.uk"], ["LIMIT", 1]]
  SQL (0.0ms)  INSERT INTO "users" ("email", "encrypted_password", "first_name", "last_name", "group_id", "created_at", "updated_at", "confirmation_token", "confirmation_sent_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"  [["email", "steveh@essex.ac.uk"], ["encrypted_password", "$2
a$10$okslNin90v3euhuv.gtqzu2FHn4B0.TKWpTC2yizU1v/dcTztzK8O"], ["first_name", "Steve"], ["last_name", "Hassan"], ["group_id", 1], ["created_at", 2016-08-30 15:56:07 UTC], ["updated_at", 2016-08-30 15:56:07 UTC], ["confirmation_token", "qsaJNdsUvEFhDnrFS2g_"], ["confirmation_sent_at", 2016-08-30 15:56
:07 UTC]]
  Group Load (0.0ms)  SELECT  "groups".* FROM "groups" WHERE "groups"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
   (0.0ms)  COMMIT
source=rack-timeout id=996f80a3a77b2c2887c188e47f3076f6 timeout=25000ms service=1074ms state=active
  Rendering vendor/bundle/ruby/2.2.0/gems/devise-4.2.0/app/views/devise/mailer/confirmation_instructions.html.erb
  Rendered vendor/bundle/ruby/2.2.0/gems/devise-4.2.0/app/views/devise/mailer/confirmation_instructions.html.erb (15.6ms)
Devise::Mailer#confirmation_instructions: processed outbound mail in 1484.4ms
source=rack-timeout id=996f80a3a77b2c2887c188e47f3076f6 timeout=25000ms service=2012ms state=active
Sent mail to steveh@essex.ac.uk (281.3ms)
Date: Tue, 30 Aug 2016 16:56:08 +0100
From: w.poynter@ucl.ac.uk
Reply-To: w.poynter@ucl.ac.uk
To: steveh@essex.ac.uk
Message-ID: <57c5ac98a11e9_88454f2360224ec@daproc6.mail>
Subject: Confirmation instructions
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>Welcome steveh@essex.ac.uk!</p>

<p>You can confirm your account email through the link below:</p>

<p><a href="http://localhost/users/confirmation?confirmation_token=qsaJNdsUvEFhDnrFS2g_">Confirm my account</a></p>

Completed 500 Internal Server Error in 2031ms (ActiveRecord: 0.0ms)

OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed):

app/controllers/users/registrations_controller.rb:13:in `create'
source=rack-timeout id=996f80a3a77b2c2887c188e47f3076f6 timeout=25000ms service=2044ms state=completed
cache: [POST /users.json] invalidate, pass
cache: [POST /users.json] invalidate, pass

**Comment by stevehassan** [comment]
I execute the confirmation link and I can get in now but that is no good in production.

**Comment by stevehassan** [comment]
I think my problem is that smtp is not configured for essex?

**Comment by HayleyMills** [comment]
This needs to be setup for other Archivist instances, so we can add new users from the interface rather then the back end. We need to add Nimal to instances and Abdul Ari (CLS) to the Live Archivist. This will also mean that users can manage their own passwords.

**Comment by spuddybike** [comment]
could we check and make sure that it is working for all instances, NOT just live?

**Comment by HayleyMills** [comment]
Tested on GenScot instance by adding new user Nimal. There was an error message "Could not save user" however it did create the user. The problem remains that it did not send an email and so the password cannot be setup. This is also true for the closer-archivist instance. 

Tested resetting password on the closer-archivist instance to test the email functionality and this did send an email.
