### ISSUE TITLE
Can there be an close x to leave the add construct side panel

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#109]
Can there be an close x to leave the add construct window (the one after you select the construct type). If you change your mind about entering a construct you have to click back until you reach the build again, or you have to click build.

**Comment by HayleyMills** [comment]
Not sure how this will work for new react- but flagging in case useful.

**Comment by HayleyMills** [comment]
Also raised as an issue by NV.

**Comment by simonreed** [comment]
This is now on closer-react

**Comment by HayleyMills** [comment]
Yes this has been added.
