### ISSUE TITLE
Categories not appearing on code list page. 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#112]
You have to refresh the code list page to see the categories, as otherwise they first appear to be empty.

**Comment by HayleyMills** [comment]
This is also happening for min and max in response domains. Note-if you do not refresh before selecting edit, the metadata is lost. This has happened a few times.

**Comment by charlesdebarros** [comment]
Duplicate

**Comment by HayleyMills** [comment]
This is not a duplicate of 180.
