### ISSUE TITLE
Difficult/impossible to move construct out levels

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#124]
It appears to be impossible to move a construct to a different parent and position it correctly. The drag and drop works well for re-ordering with a level but it is not possible to move between levels. When dragging, the option to place (the square) only appears for the innermost level of where you want to move it.  Where MAs have needed to move constructs out levels they have been deleting and starting again.

**Comment by HayleyMills** [comment]
The construct page is quick for building, but not for moving. An option suggested might be to have an alternative way of moving constructs which is based on entering the position (like CADDIES). This might help/speed up moving constructs in verfication.

**Comment by wpoynter** [comment]
Is this still true with the work I have done to the construct page?

**Comment by HayleyMills** [comment]
Moving constructs is now much easier, so we can close this. The related issue #156 still seems to be an issue though (it happened on 10th July).
