### ISSUE TITLE
Summary pages not updating

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#125]
The construct summary tables do not reflect any changes made.

**Comment by wpoynter** [comment]
I cannot replicate this bug. Could you check if it is still there and supply more detail?

**Comment by HayleyMills** [comment]
As far as I can tell, this is now working for all summary tables except for the intervewiee which is not updating on the Questions summary page.

**Comment by HayleyMills** [comment]
This is also not updating when qi labels are changed and when the qi/qc linked to a qc is changed.

**Comment by simonreed** [comment]
@HayleyMills What pages are these can you give me an example on staging please.

**Comment by HayleyMills** [comment]
You can click the summary pages in the construct box on the build page. See alspac_00_msdhs for example. All the tables update apart from the Question one which is not updating the  base_label or response_unit_label. 

e.g. 
I changed the label of the qi linked to qc_A1_a test from qi_A1_a  to qi_A1_a test but this is not reflected here.  
I also changed the qi linked to qi_A1_b to to qi_A1_c, but this is not shown. 

Lastly the interviewee is not updating, I changed this to Cohort/Sample member for qc_A1_a. 

![image](https://user-images.githubusercontent.com/16664703/64628084-b12e8480-d3e8-11e9-9556-edeed0b3b767.png)

**Comment by simonreed** [comment]
@HayleyMills The Questions summary for example shows the `base_label` of the `CcQuestion` record which is taken from the `label` of the related `QuestionItem` (or QuestionGrid) when the `CcQuestion` is created or when the QuestionItem/Grid association to the CcQuestion is changed.

At the moment when the `QuestionItem` label is changed it doesn't change the `label` on any relatated `CcQuestion` objects. Which is causing the issue with 

>I changed the label of the qi linked to qc_A1_a test from qi_A1_a to qi_A1_a test but this is not reflected here.
>I also changed the qi linked to qi_A1_b to to qi_A1_c, but this is not shown.

Do you want me to change this behaviour? What is the reason for the `CcQuestion` has it's own db column for `label` as opposed to just using the `label` for the associated Question?

**Comment by HayleyMills** [comment]
Would you be able to clarify what you mean by 
> At the moment when the QuestionItem label is changed it doesn't change the label on any relatated CcQuestion objects. Which is causing the issue with

The ccquestion label needs to be different from the questionitem/grid label, as it needs to be unique within the instrument and it can re-use questionitems/grids.

**Comment by simonreed** [comment]
> Would you be able to clarify what you mean by
> 
> > At the moment when the QuestionItem label is changed it doesn't change the label on any relatated CcQuestion objects. Which is causing the issue with
> 
> The ccquestion label needs to be different from the questionitem/grid label, partly because it needs to be unique within the instrument but it can re-use questionitems/grids.

Ah yes sorry you're right, I got confused between `label` and `base_label` on a CcQuestion.

**Comment by simonreed** [comment]
This is on staging now @HayleyMills

**Comment by HayleyMills** [comment]
Tested on staging server using alspac_00_msdhs by; 
- changing the labels of qi/qg attached to a qc
- changing the qi/qg attached a qc
- changing the interviewee
All changes were reflected in the questions summary table.

**Comment by HayleyMills** [comment]
It is not showing when a construct has been deleted.

**Comment by HayleyMills** [comment]
Resolved on new React Archivist.
