### ISSUE TITLE
Question page will not load for nshd_65_hvi

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#130]
Looks like this is caused by two question items with the same label (qi_1), it allows you to save but then will not load the question page.

**Comment by HayleyMills** [comment]
ncds_91_myc question page will not load. Details from TA: 
11:40am: I was in the process of creating question items when at question qi_s4_pB_6 archivist did not allow me to save it. The page was stuck at the ‘creating qi’s’ process with the options for saving or cancelling. I then refreshed the page, only to be met with a blank page. 

11.45am: I then refreshed the page once more and the question items page reappeared again but this time with none of the question items that I had created this morning (all beginning with qi_s4…).

11.50am: After refreshing the page again, the question items disappeared again. 

13.00pm: The question items page has remained blank since.

**Comment by HayleyMills** [comment]
nshd_65_smsc code list page will not load (TA).

**Comment by HayleyMills** [comment]
alspac_02_fa10m question page and construct page will not load (IB).

**Comment by HayleyMills** [comment]
nshd_68_ftepq question page will not load (TA).

**Comment by wpoynter** [comment]
Fixed in version 7
