### ISSUE TITLE
Construct view no longer updating automatically when a change to a condition is made

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#132]
JS found that when a small change to a condition is made (e.g. to ID or text) the constuct view used to rebuild to reflect this. However since since 11/11/2016 it is no longer updating (it freezes), so you have to refresh the construct view in order to see the constructs related to that condition.

**Comment by wpoynter** [comment]
archivist-realtime keeps crashing.

**Comment by wpoynter** [comment]
The REDIS_URL changed. The two apps have now been attached which should keep changes in sync.
