### ISSUE TITLE
REACT: Select all option for adding interviewee instead of one by one

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#153]
On the construct page?

**Comment by HayleyMills** [comment]
This could be a feature to add on the summary page?

**Comment by simonreed** [comment]
You can now change the Response Unit Label (Interviewee) for all CcQuestions in an instrument on staging.

<img width="1413" alt="Screenshot 2024-04-10 at 22 06 38" src="https://github.com/CLOSER-Cohorts/archivist/assets/13276/a24416c7-bc65-40b2-87f0-c899d562233f">

**Comment by HayleyMills** [comment]
Tested on staging and this works well, it's good to have the pop asking to double check too.
