### ISSUE TITLE
Problems with moving constructs

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#156]
When moving a construct it will not save the first time. It takes several times of moving and refreshing before the new position will save. Intermittently, both the old and new postions are shown on the construct page and neither will save or delete.

**Comment by HayleyMills** [comment]
This is still an ongoing problem. It is not possible to tell if a move has saved or not, you have to refresh after each move to make sure it has saved.

**Comment by HayleyMills** [comment]
This is still an issue. It no longer creates a construct in two positions, but the construct reverts back to the original position e.g. nshd_06_ncs qc_61_a_i.

**Comment by spuddybike** [comment]
I think it might be related to line 270 in app\assets\javascripts\lib\data_manager.coffee
DataManager.Data.Instrument.topsequence = (s for s in DataManager.Data.Instrument.Constructs.Sequences when s.top)[0]

probably top should be topsequence

**Comment by charlesdebarros** [comment]
It seems the issue was due archivist timing out. Once timed out the moving process was not happening and it was not retaining the construct new position. It seems to be working now. I will monitor it for a little longer before closing this issue.

**Comment by charlesdebarros** [comment]
I have found out that only the last move is not saved. If only one move is made, then no changes will be saved. In case of three moves, for example, the first two will work fine, the last one will not. This happens both on the Live and in the Beta versions of Archivist.

**Comment by HayleyMills** [comment]
To add to this- The first move also doesn't save as Archivist automatically refreshes after this. So to get around the problem you need to do this move twice, then once you have finished the moves do an extra move before refreshing. 

I have tried this out using hm_test_1 and found that sometimes you have to move the same construct twice because it reverts back or becasue it appears twice (e.g. moving question in AT SCHOOL to inside Section A). Other times the construct will disappear (e.g. moving s_outro_2 or moving s_sectiona_2 and s_sectiona_1 to inside Section A) so you can’t tell where it is until you refresh.

**Comment by charlesdebarros** [comment]
Downgraded Angular-UI-Tree library (what adds the 'Drag and Drop' feature) to version 2.22.5 from 2.22.6.

Moving constructs, even staggered constructs seem to be working fine and saving to the database first time. No need of extra moves. 

I will keep monitoring it for a week, gathering feedback from users, before closing this issue.

**Comment by HayleyMills** [comment]
Tested in beta using nshd_82_q (medium sized questionnaire). It is now moving constructs the first time. It may have also solved #214, but this will need further testing.

**Comment by charlesdebarros** [comment]
Updates pushed to Archivist's Live version on 26Jul18. Apologies for the late update.

**Comment by HayleyMills** [comment]
I have also had a case of a construct appearing in two places, as described in the first comment. It resolved when refreshing however. 

![image](https://user-images.githubusercontent.com/16664703/43581425-c90b208a-9650-11e8-9a25-ad68cff672c1.png)

**Comment by charlesdebarros** [comment]
This seems to be related to external factors to Archivist as the moving constructs functionality work both in the Dev and Beta environments. One of such factors could be size of the database and the fact that sometimes the process times out, specially in times of heavy traffic.

**Comment by charlesdebarros** [comment]
This functionality has not been consistent in the Live version. Sometimes it works, sometimes it doesn't, as per users' feedback.

**Comment by HayleyMills** [comment]
Update: when you make a move and refresh the page, the move now saves. You have to refresh the page every time you make a move.

**Comment by charlesdebarros** [comment]
Updates in Archivist's code related to constructs, specially the removal of the Materialized View should help solve this issue. 

As informally discussed with Hayley, we will put together a 'check list' of things to test when code changes are made.

**Comment by HayleyMills** [comment]
Tested on staging and is working okay.

**Comment by HayleyMills** [comment]
Tested on live and first move still not saving.

**Comment by spuddybike** [comment]
@HayleyMills Could this be retested on Staging as improvements have been made to performance

**Comment by HayleyMills** [comment]
This is still an issue for the main Archivist and it is particularly bad for large instruments. 

For both the live and staging moving constructs in large instruments involves waiting for the processing wheel to finish which takes a while (20+ seconds).

**Comment by HayleyMills** [comment]
While testing for other issues, I noticed that this issue seems to have been resolved. I have tested using bcs8 on the staging, which had problems with duplicates and constructs not moving, and it is working okay (although they do take a but of processing time).

**Comment by HayleyMills** [comment]
Tested on staging server on largest instrument us4. It did move and save the constructs in the new positions although it took between 25-60 seconds processing to do this. I tested on an average instrument alspac_03_tyo  and this tool about 10 seconds processing to move and save. So no longer a problem with getting the moves to save, but the time it takes to do this is very slow.

**Comment by spuddybike** [comment]
Let’s move this to Redis project and test after that has happened 

======================
Lovingly typed on the iPhone
======================

**Comment by HayleyMills** [comment]
Moving constructs alone doesn't seem to be causing issues in the same way. There is a new issue # #366 which is related. So I will close this one.

**Comment by HayleyMills** [comment]
JS is experiencing issues moving constructs (so far in MCS5) with them reverting back to the their original position. I am unable to replicate this, but I think it is related to it timing out, as it is taking a long time to actual do any moving in large instruments.

**Comment by HayleyMills** [comment]
Closing this issue as it is same as #366
