### ISSUE TITLE
Categories in code lists not shown on code list page- must refresh to see them.

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#160]
If edit is clicked when the categories are empty it will mean the code list categories are lost.

**Comment by HayleyMills** [comment]
This is also the case of min and max in response domains. The refresh is no longer working in some cases.

**Comment by charlesdebarros** [comment]
Reproducing:
Refresh 'build' page, go back into 'code lists'. Refreshing is not working for 'min and max'

**Comment by charlesdebarros** [comment]
Even though some categories do not show when the page loads, refreshing the page makes them appear. Further investigation regarding this behaviour is needed.

**Comment by simonreed** [comment]
This is related to #180 where the category label is blank, causing the whole code list not save successfully.

**Comment by HayleyMills** [comment]
Tested on staging and the code lists are no longer empty. 

However, tested using https://closer-archivist-staging.herokuapp.com/instruments/1605/build/code_lists/ and new code lists are no longer saving with any categories. See cs_test_cardinality I have attached some screenshots. 

The first time saving there is an error message '..failed to update!' but it has created an empty code list. If you then edit and re-add the info it will '..updated successfully however it only saves the Min and Max responses and no categories. 

![image](https://user-images.githubusercontent.com/16664703/62206936-c4324b80-b38a-11e9-9243-4a15b2dcf036.png)
![image](https://user-images.githubusercontent.com/16664703/62206947-c98f9600-b38a-11e9-9d8f-3ffc31112e68.png)
![image](https://user-images.githubusercontent.com/16664703/62206954-cd231d00-b38a-11e9-9ca9-a33833bb58cf.png)

**Comment by HayleyMills** [comment]
Tested on staging again with the same instrument and it is behaving in the same way as described above.

**Comment by simonreed** [comment]
@charlesdebarros this hasn't been merged into `release` branch yet so hasn't been deployed to staging. Could you let @HayleyMills know when it's ready for testing.

same for #180

**Comment by HayleyMills** [comment]
Tested on staging and the categories are now displaying the first time.

**Comment by HayleyMills** [comment]
Tested in staging by JS and all okay.
