### ISSUE TITLE
Cardinality min and max values in Code lists are not saving the first time. 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#180]
JS has experienced this for mcs_07_main, the values are reverting back to 1:1. 

Note this is the case for all instruments.

**Comment by HayleyMills** [comment]
If changing the cardinality from 1:1 you have to do this twice in order for it to save.

**Comment by HayleyMills** [comment]
See #160

**Comment by HayleyMills** [comment]
Tested on staging and the min and max cardinality in the code list are still not saving the first time. It is reverting back to the default of 1 and 1.

**Comment by simonreed** [comment]
@HayleyMills this is now on staging

**Comment by HayleyMills** [comment]
@simonreed The instruments (build pages, the edit or the doc view) are not loading in the staging?

**Comment by simonreed** [comment]
@HayleyMills sorry that is now fixed.

**Comment by HayleyMills** [comment]
Tested on staging and the min and max responses are now saving first time!

**Comment by HayleyMills** [comment]
Tested in staging by JS and all okay.
