### ISSUE TITLE
Issues with line breaks \n\  in literals

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#182]

**Comment by wpoynter** [comment]
I need an example

**Comment by HayleyMills** [comment]
Potentially causing issues in CD?  e.g mcs_05_cpa s_WARN_iv

**Comment by charlesdebarros** [comment]
Escaping special characters issue on export?

**Comment by HayleyMills** [comment]
Is this being handled by Jenny Li's cleaning script?

**Comment by spuddybike** [comment]
Yes
