### ISSUE TITLE
Issues with & in literals

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#183]

**Comment by wpoynter** [comment]
Also need an example.

**Comment by HayleyMills** [comment]
Would like to search the DB for & to find the problem, but currently cannot get access to DataGrip.

**Comment by HayleyMills** [comment]
This applies to all characters entered as their ASCII code which appear as the code (&amp;), rather than the symbol (&) on the Archivist doc view and CD e.g. alspac_00_ays qc_C5_a-e. 

Note this has been added to Trello too.

**Comment by charlesdebarros** [comment]
Different encoding issues?
Check Ingesting into repository.

**Comment by HayleyMills** [comment]
Related to #182 and #280

**Comment by charlesdebarros** [comment]
This issue it tricky to test as it only shows the problem once it is pushed to Heroku. In local development environment, the ampersands (&#38) and apostrophes (&#39) display correctly. 

See https://closer-archivist-browsergroup.herokuapp.com/instruments/alspac_99_ttd under Construct qc_C1_a, second bullet point. Actually, the apostrophe ASCII code appears 12 times in that instrument, under various constructs.

**Comment by spuddybike** [comment]
We should add this to the exporter, to ensure that these characters are not exported from the Archivist instance (on Heroku), it looks like a Heroku feature

**Comment by simonreed** [comment]
@HayleyMills is this still an issue? I can't see if on https://closer-archivist-staging.herokuapp.com/instruments/alspac_99_ttd

**Comment by HayleyMills** [comment]
Hopefully the issues with ' and £ have been resolved for categories, instructions and question literals, in the staging DB, but there are still special characters e.g. "Eat out in a restaurant or caf&#130; (including a fast food restaurant)" in https://closer-archivist-staging.herokuapp.com/instruments/nshd_06_pb.

**Comment by simonreed** [comment]
Do we know where these odd strings are being inputted from? We have this odd example :

```
#<Category:0x00007f90c87773a0 id: 184992, label: "Doesn&amp;#39;t apply", created_at: Fri, 25 Nov 2016 17:40:53 UTC +00:00, updated_at: Fri, 25 Nov 2016 17:40:53 UTC +00:00, instrument_id: 1358>
```

Even we convert the HTML entities (the & parts), we go from `Doesn&amp;#39;t apply` to `"Doesn&#39;t apply"` which needs another rounds of parsing.

**Comment by simonreed** [comment]
It appears that they're stored in the database in this way with HTML entities, which leads us to the question of how why they're being inputted as that? We don't really want to have to escape every user entered phone through a parser.

**Comment by HayleyMills** [comment]
Apologies I don''t know too much about how these work but in terms of where the text has come from in most cases they will have been copied and pasted from PDFs, rather than parsed in.

**Comment by HayleyMills** [comment]
I think the exporter is handling these okay in the literals now, so will close this issue but see #417
