### ISSUE TITLE
Loop logic should show as <= rather than !=

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#184]

**Comment by wpoynter** [comment]
I need an example.

**Comment by HayleyMills** [comment]
This is for all loop logic using the End Value e.g. nshd_65_smsc  l_q3.

**Comment by charlesdebarros** [comment]
Hard coded entry?

**Comment by HayleyMills** [comment]
It looks like when this is exported to XML the != is changed to < and this get added to Discovery. Can we  change this to <= instead?

**Comment by HayleyMills** [comment]
This is resolved in new React Archivist.
