### ISSUE TITLE
Linking a datasets to one or more instruments and the study associated with it.  

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#189]

**Comment by HayleyMills** [comment]
It is now possible to add the study via Archivist.

**Comment by charlesdebarros** [comment]
Work around: append dataset to the instrument using Rails console.

**Comment by HayleyMills** [comment]
You can technically link more than one questionnaire to a datasets, however it will be unclear which it is mapped to. It is not possible do add the mappings manually for this reason as you can't tell which question is from which instrument.

**Comment by HayleyMills** [comment]
This has been resolved.
