### ISSUE TITLE
Named tabs

### ISSUE THREAD

**Issue by ThaminaAnjuman** [CLOSER-Cohorts/archivist#2]
When opening multiple (web) tabs from different parts of CADDIES, the tabs are not indicative of what the webpage is about. Instead the tab label is just the prefix of the questionnaire i.e. DDi3 us2_ysc. It would therefore be quite helpful for tabs to be named after it's webpage* e.g. Conditions, Question items etc. This may reduce time taken to input and verify metadata, especially in the case of swapping between different tabs.

*Apologies for lack of technical terms, can specify upon request

**Comment by wpoynter** [comment]
I have now added this to all built dialogs. The format is to put the questionnaire prefix first followed by the function
