### ISSUE TITLE
Importer not working for instrument DDI XML

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#209]
I have tested the importer by using a downloaded instrument XML from Archivist and then importing it under a different prefix. Archivist message states that it has imported but it does not appear. 

Note the importer works for USoc XML.

**Comment by HayleyMills** [comment]
This likely relates to orphans in the XML which are exported. See #277 for new backup solution.

**Comment by charlesdebarros** [comment]
Very probably related to issue #280 as once there are `orphan elements`, Archivist does not know how to handle those elements and therefore does not import the file uploaded correctly. 

The issue get agravated as Archivist returns a `success` message even though it has failed to perform the import action correctly.

**Comment by HayleyMills** [comment]
This is now covered in #312, #311, #284.
