### ISSUE TITLE
Unable to drag and drop a construct inside a new condition

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#210]
There is an interim solution: create a temporary construct within the loop or condition, then drag and drop the correct construct inside. Delete the temporary construct.

**Comment by charlesdebarros** [comment]
Is this still the case, @HayleyMills?

**Comment by HayleyMills** [comment]
@charlesdebarros Yes this is still the case, when the true branch is empty you cannot move a construct inside. You can however move a construct into the else branch when it is empty.

**Comment by simonreed** [comment]
@HayleyMills could I get an example of this setup on staging, I'm a bit confused about how to replicate.

**Comment by HayleyMills** [comment]
@simonreed No problem, if you look at the construct view of hm_test_1 (https://closer-archivist-staging.herokuapp.com/instruments/hm_test_1/build/constructs) there is a condition labelled Condition#210a, if you expand this there is a True: and an Else: It is not possible to drag and drop a construct inside the True: but it will move inside the Else. 
If you do the same for Condition#210b it will move inside the True: as it has a construct inside already.

**Comment by simonreed** [comment]
@spuddybike @charlesdebarros This is a really tricky one, the library that we're using https://github.com/angular-ui-tree/angular-ui-tree requires for us to have a `ui-tree-node` with a model to back it up in order for you to be able to add to the tree. 

You can't add a new node to a `ui-tree-nodes` parent if the parent has no `ui-tree` to begin with. I've attempted to add a blank `ui-tree-node` if there are no children but this doesn't work as you need  `model` object for it. Creating a blank model object causes issues with both the drag and drop and also when saving the structure as it attempts to.

I'm no closer to finding a solution to this. As this has a workaround and is not a high priority I'd suggest we move this back into the backlog, potentially for a larger body of work into possible `tree` library alternatives.

**Comment by HayleyMills** [comment]
@simonreed Quick question- how are we able to add to the Else: branch? This may be a stupid question, but can we change it so that we can add to the True: straight away, with a work-around for the Else: (we use the True branch most of the time)?

**Comment by simonreed** [comment]
![Screen Capture on 2019-08-06 at 10-53-41](https://user-images.githubusercontent.com/13276/62530600-c7b94d00-b838-11e9-8db5-94a045e92c9b.gif)

You can create a new dummy construct for the `True` or `Else`, that then allows drag and drop to work. Once you've made the move that you want then just remove the dummy statement construct.

**Comment by HayleyMills** [comment]
Thanks, yes that's what we've been doing, but we only have to do it for the True. You can drag and drop straight into the Else without the dummy.

**Comment by spuddybike** [comment]
Could you have  another look at this, we have a workaround, but would be good to understand how mcuh effort might be required to fix this.

**Comment by HayleyMills** [comment]
This will be solved by the new REACT front-end.
