### ISSUE TITLE
Cannot save a construct which has been edited more than once without refreshing

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#214]
When editing a construct which is then saved, you must refresh the page before editing it again otherwise the construct will not save.

**Comment by HayleyMills** [comment]
This is now a problem after moving a construct. If you move a construct then try to edit an unrelated construct, it will not save. You need to refresh the construct page once or twice and then try again.

**Comment by HayleyMills** [comment]
Tested on staging and it is working okay.

**Comment by HayleyMills** [comment]
Tested on live and it is no longer working.

**Comment by charlesdebarros** [comment]
For this example I used https://archivist.closer.ac.uk/instruments/hm_test_2/build/constructs and
https://closer-archivist-browsergroup.herokuapp.com/instruments/alspac_99_ttd/build/constructs 

I have tried different variations of editing for this issue and could not replicate the problem. 

I had tried (with and without clearing the instrument's cache beforehand):
1. moving construct, editing, saving, refresh
2. moving construct, editing saving, moving construct, refresh
3. editing, saving, moving construct, refresh
4. moving construct, moving construct, editing save, moving construct, refresh

@HayleyMills would you please have another go at trying to replicate this issue and see if there are still any problems with it?

**Comment by HayleyMills** [comment]
Tested on live and staging and it is now possible to edit something more then once without having to refresh.
