### ISSUE TITLE
Problems viewing and changing mapped topics

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#215]
Reported by Andrew Peters. See bcs_80_me for example. The topics which have been applied are no longer visible and it is not possible to change them. The variables are still mapped as they are visible in tv.txt. 

![bcs_80_me](https://user-images.githubusercontent.com/16664703/35577833-55c0bef2-05da-11e8-993f-4f4fafa54301.png)

**Comment by HayleyMills** [comment]
Tested on staging whether it is possible to change topics using hcs_1_home_1. 
I can change topics where there are no issues of conflicts in the UI. This make sense. But how do I change a topics in the UI for tq and tv which are mapped through qv? I tried changing one then the other but both give the same validation error. See snips below. 

![image](https://user-images.githubusercontent.com/16664703/65153673-1524fe80-da22-11e9-9855-997751ffde96.png)

![image](https://user-images.githubusercontent.com/16664703/65153705-20782a00-da22-11e9-96cb-3046eed9a298.png)

**Comment by simonreed** [comment]
In the above example is 'qc_1' also associated to another variable that as a topic of `Anthropometry`? `qc_1` is inheriting `Anthropometry` from one of it's associated variables, because of this you can't change the `qc_1` topic and likewise you can't change `atricep1` to another topic other than `Anthropometry` otherwise `qc_1` will have variables with more than one topic.

**Comment by HayleyMills** [comment]
In the example qc_1 is only mapped to atricep1 both the question and variable are mapped to the topic Anthropometry. If I want to change both to say demographics using the UI is this possible? Or do I need to/should I export the mappings make the change and then re-import? Or I could remove the q-v map first and the change the topics and remap. Its not a problem I'm just trying to work out the expected behavior and how to use it.

**Comment by simonreed** [comment]
In the use case above you'd need to clear the topic for one of them. Then you can change the topic from `Anthropometry` to any other topic on the other.
