### ISSUE TITLE
Dataset mapping and instrument view page pagination 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#216]
The first and last page seem to change order.

**Comment by HayleyMills** [comment]
The first and last page seem to change order.

**Comment by charlesdebarros** [comment]
See page pagination add-on.

**Comment by HayleyMills** [comment]
The pagination is now working on the instrument page, but it is still not working on the individual dataset page. It realtes to the first and last pages. The dataset view is no longer loading on the staging version at all. https://closer-archivist-staging.herokuapp.com/datasets/551

**Comment by spuddybike** [comment]
@simonreed

**Comment by spuddybike** [comment]
@HayleyMills should be ready for testing on staging

**Comment by HayleyMills** [comment]
Tested on the staging and the dataset variable pages are now loading and the pagination is working.

**Comment by HayleyMills** [comment]
Tested on live HEAF and it is working on variable pages. Note I can't test the dataset page, as there aren't enough datasets.

**Comment by spuddybike** [comment]
Migrated and updated ALSPAC (closer-archivist-alspac), for testing datasets

**Comment by HayleyMills** [comment]
There are not enough datasets on ALSPAC to test this. There needs to be more than two pages.

**Comment by HayleyMills** [comment]
This is resolved with new React Archivist
