### ISSUE TITLE
Problem with constructs disappearing because of parent ID is null

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#221]
It will not save, it seems like it might already exists but it cannot be seen?

**Comment by HayleyMills** [comment]
This issue is reoccurring for other instruments. For example nshd_99_scq it is not possible to add the question qc_2a as it appears to already exist (Construct failed to update error) although it is not visible in the construct view or the doc view, but it is present in the question summary page.

**Comment by HayleyMills** [comment]
This is also affecting nshd_06_ncs, where the construct c_q72a_i  s not showing.

**Comment by HayleyMills** [comment]
alspac_11_foy is also affected. Sequence "The questions in this section ask you about ..." including questions D24 to D34f inside it, as well as sequence 'Events in your life Listed below are a number..." have disappeared from the doc and construct view.

**Comment by HayleyMills** [comment]
mcs_05_cpa is now also affected, but for conditions. c_qTR3B_i, c_qTR3B_ii, c_qTR3B_iii, c_qTR2A_rename, q_cTR2a_iv and c_qTR2A_v have disappeared but again they are in the summary table.

**Comment by HayleyMills** [comment]
I managed to fix c_q72a_i in nshd_06_ncs. The construct appeared in the xml and in the database, but it did not have a parent, so I added one, cleared the cache and then it appeared. I did the same for qc_2a in nshd_99_scq. 

However, I also looked at alspac_12_iaay. The missing question is inside of a missing condition c_qD3a, which is also in the database, but not in the xml? This had a missing parent too which I also added, but this time it did not reappear?

**Comment by HayleyMills** [comment]
alspac_11_foy the sequence "The questions in this section ask you about ..." including questions D24 to D34f have been fixed. The sequence 'Events in your life Listed below are a number.." does not exist in the database or the xml, so it will need to be re-added manually. 

All constructs for mcs_05_cpa have been fixed except for q_cTR2a_iv which did not exist in the database, and so will need to be added manually.

**Comment by HayleyMills** [comment]
These have now been resolved, but it doesn't solve the underlying problem of the parents disappearing for some constructs, and therefore their disappearance in the construct and doc view.

**Comment by HayleyMills** [comment]
This issue keeps occurring and is high priority. It appears to happen when you make changes to the constructs e.g change the label and reposition.

**Comment by HayleyMills** [comment]
Some more insight into the problem, which may or may not help. 
1) Moved construct and refreshed. 
3) Edited a sequence label and refreshed 
_Doc and construct view no issues. 
In the database however it does not have a parent id._ 
5) Changed another sequence label and refreshed.
_Doc and construct view no issues. 
In database seconds sequence also does not have a parent id._ 
6) Moved construct and refreshed. 
_Doc and construct view both sequences missing. 
In database only the second sequence does not have a parent id._
7) Refreshed. 
Doc and construct view first sequence reappeared. 
8) Moved a construct and refreshed
Doc and construct view second sequence missing. 
In database second sequence does not have a parent id.

**Comment by HayleyMills** [comment]
- Every time an construct is edited (e.g. change a label) the construct loses it parent id in the database. This does not show immediately in the views even after refreshing. 
- When a construct is moved the construct which was edited regains a parent id (most likely as moving constructs has to check all the parents and positions during the move process?). The views however now show them as missing (even though they have parent ids in the database) until this is refreshed. 
- Losing the parent_id seems to be happening every time. However, there are occasions when it is not regained after a move has been made, and so disappears. I cannot replicate this, but if we stop the ids being made null when a change is made, this should stop them disappearing.

**Comment by charlesdebarros** [comment]
Linked to the parent_id disappearing when editing constructs.

**Comment by HayleyMills** [comment]
Note this is also happening in the HEAF version of Archivist. Three constructs lost their parent IDs Friday 11th which resulted in the whole construct view not displaying for Ken and James (see image). My view remained okay, presumably because of the cache. 

![image](https://user-images.githubusercontent.com/16664703/51047360-2d559b80-15c0-11e9-95ae-672ee87f2200.png)

**Comment by HayleyMills** [comment]
Further testing- the parent ID changes to null after **any** of the elements have been edited, for those in a sequence as well as those in a condition within a sequence. 

The work around of moving something after the edit so the parent is regained is still working.

**Comment by charlesdebarros** [comment]
After some more testing from the backend, a pattern emmerged: every time I had a 'parent_id' missing when editing a construct, there was a 'cannot connect to Redis' message.  See backeng log extract below:
>>> Quote
Started PUT "/instruments/hm_test_1/cc_sequences/11567.json" for 127.0.0.1 at 2019-02-19 09:21:36 +0000
Processing by CcSequencesController#update as JSON
  Parameters: {"id"=>"11567", "literal"=>nil, "position"=>1, "branch"=>0, "label"=>"hm_test_1- does this have a parent?", "children"=>[], "top"=>false, "parent_id"=>11649, "parent_type"=>"CcSequence", "topic"=>nil, "instrument_id"=>"hm_test_1", "type"=>"sequence", "resolved"=>true, "cc_sequence"=>{"id"=>"11567", "instrument_id"=>"hm_test_1", "literal"=>nil, "label"=>"hm_test_1- does this have a parent?", "parent_id"=>11649, "parent_type"=>"CcSequence", "position"=>1, "branch"=>0}}
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 44], ["LIMIT", 1]]
  [1m[36mUserGroup Load (0.2ms)[0m  [1m[34mSELECT  "user_groups".* FROM "user_groups" WHERE "user_groups"."id" = $1 LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
  [1m[36mInstrument Load (0.3ms)[0m  [1m[34mSELECT  "instruments".* FROM "instruments" WHERE "instruments"."id" = $1 LIMIT $2[0m  [["id", 1605], ["LIMIT", 1]]
  [1m[36mCcSequence Load (0.8ms)[0m  [1m[34mSELECT  "cc_sequences".* FROM "cc_sequences" WHERE "cc_sequences"."instrument_id" = $1 AND "cc_sequences"."id" = $2 LIMIT $3[0m  [["instrument_id", 1605], ["id", 11567], ["LIMIT", 1]]
  [1m[36mCcSequence Load (0.7ms)[0m  [1m[34mSELECT "cc_sequences".* FROM "cc_sequences" WHERE "cc_sequences"."id" = 11649[0m
Unpermitted parameter: id
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (221.1ms)[0m  [1m[33mUPDATE "cc_sequences" SET "instrument_id" = $1, "parent_type" = $2, "label" = $3, "updated_at" = $4 WHERE "cc_sequences"."id" = $5[0m  [["instrument_id", 0], ["parent_type", nil], ["label", "hm_test_1- does this have a parent?"], ["updated_at", "2019-02-19 09:21:36.066837"], ["id", 11567]]
  [1m[36mInstrument Load (0.3ms)[0m  [1m[34mSELECT  "instruments".* FROM "instruments" WHERE "instruments"."id" = $1 LIMIT $2[0m  [["id", 0], ["LIMIT", 1]]
**_Cannot connect to Redis_**
  [1m[35m (0.8ms)[0m  [1m[35mCOMMIT[0m
  [1m[36mCcCondition Load (0.9ms)[0m  [1m[34mSELECT "cc_conditions".* FROM "cc_conditions" WHERE "cc_conditions"."parent_id" = $1 AND "cc_conditions"."parent_type" = $2[0m  [["parent_id", 11567], ["parent_type", "CcSequence"]]
  [1m[36mCcLoop Load (0.7ms)[0m  [1m[34mSELECT "cc_loops".* FROM "cc_loops" WHERE "cc_loops"."parent_id" = $1 AND "cc_loops"."parent_type" = $2[0m  [["parent_id", 11567], ["parent_type", "CcSequence"]]
  [1m[36mCcQuestion Load (0.6ms)[0m  [1m[34mSELECT "cc_questions".* FROM "cc_questions" WHERE "cc_questions"."parent_id" = $1 AND "cc_questions"."parent_type" = $2[0m  [["parent_id", 11567], ["parent_type", "CcSequence"]]
  [1m[36mCcSequence Load (0.7ms)[0m  [1m[34mSELECT "cc_sequences".* FROM "cc_sequences" WHERE "cc_sequences"."parent_id" = $1 AND "cc_sequences"."parent_type" = $2[0m  [["parent_id", 11567], ["parent_type", "CcSequence"]]
  [1m[36mCcStatement Load (0.5ms)[0m  [1m[34mSELECT "cc_statements".* FROM "cc_statements" WHERE "cc_statements"."parent_id" = $1 AND "cc_statements"."parent_type" = $2[0m  [["parent_id", 11567], ["parent_type", "CcSequence"]]
  Rendering cc_sequences/show.json.jbuilder
  [1m[36mTopic Load (0.7ms)[0m  [1m[35mWITH constructs_selection AS (
  SELECT *
  FROM cc_links
  WHERE construct_id = 11567
    AND construct_type = 'CcSequence'
  ORDER BY id, construct_id, parent_id, branch
) SELECT topics.id, "name", topics.parent_id, code, topics.created_at, topics.updated_at, description
    FROM constructs_selection
    LEFT JOIN topics
      ON constructs_selection.topic_id = topics.id
      where constructs_selection.topic_id IS NOT NULL;
[0m
  Rendered cc_sequences/show.json.jbuilder (3.5ms)
Completed 200 OK in 284ms (Views: 22.1ms | ActiveRecord: 228.6ms)

>>> End Quote

I still do not know what is creating this random 'not being able to connect' to Redis. Further investigation is need but we may probably go down the path of reducing our reliance on Redis (and Realtime).

**Comment by charlesdebarros** [comment]
Adjusted permitions construct_controller.rb lines 22/23 and improved construct handling error messages in general (in the developer tools console screen). Changes seemed to have worked. Tested in my local machine and Archivist's development environment. Changes now in the Staging environment for further tests.

**Comment by HayleyMills** [comment]
Tested editing constructs on the staging environment and it is no longer losing the parent ID with constructs disappearing. It also appears to have resolved issue #214.

**Comment by charlesdebarros** [comment]
There was a backlash with adjusting the permissions: it stops parent_ids from disappearing but it prevents adding new constructs. Restored old permissions for now.

**Comment by charlesdebarros** [comment]
When editing a construct, for this example I am using https://closer-archivist-dev.herokuapp.com/instruments/alspac_99_ttd/build/constructs, the construct's parent_id is automatically set to 'null'.

Reproducing the issue:

1. Clicking on a construct to open the edit panel
2. Changing a 'label' or 'literal' text ()
3. Clicking 'save' - Construct updated successfully! message shows
4. Refreshing the page and the construct disappear as its parent_is set to 'null'

If right after clicking 'save', moving any construct or making a fake move (simply clicking on a construct area - not the 'label' as that opens the edit panel) will prevent the edited construct from disappearing. 

If a construct indeed disappear, then its parent_id will need to be corrected directly via the database. 

The error message displayed at Rails logs is '_**Cannot connect to Redis**_'.

Keep in mind this does not only happen to 'statements'. It can happen to any type of construct.

**Comment by HayleyMills** [comment]
Tested in staging using alspac_03_aam and bcs8 and it looks to be working correctly! There were no constructs which lots there parent IDs.

**Comment by HayleyMills** [comment]
Tested in staging by JS and all okay.

**Comment by HayleyMills** [comment]
JS using us instance of Archivist and has experienced several constructs disappearing again. JS trying to replicate the problem on staging and main Archivist.

**Comment by HayleyMills** [comment]
This problem has become much worse. When you add a new construct it doesn't save in the database with a parent_id, so when you refresh all the new constructs disappear. It looks like when you make a false 'move' it adds the parent_id. This was the case previously, but this was only needed when editing constructs now this is case for creating new constructs and editing constructs. There is no need to refresh.

**Comment by HayleyMills** [comment]
@simonreed Tested on staging using test_i and is is now retaining the parent id when a construct has been edited. However, it is still not creating the parent id for new constructs until there is a 'false move' before refreshing. s_99 and s_100 have disappeared.

**Comment by HayleyMills** [comment]
Tested on staging again, as it was not deployed previously. It is now not losing the parent id when adding or editing constructs! Thanks @simonreed

**Comment by HayleyMills** [comment]
This looks like it might be an old problem returning. We have constructs in the db with null parents so they are not appearing in the view. I have an example on the US verison, but I havn't been able to recreated yet on staging. I also do not know when/why this is happening yet, or whether it is for constructs being parsed in or creaeted in the interface. Sorry for no info on this one. 

See c_qjbflex_cv in instrument 1776 in https://closer-archivist-us.herokuapp.com/instruments/

**Comment by HayleyMills** [comment]
The latest version of Archivist has been deployed onto the main Archivist. It appears that conditions are saving without their parent. and so they do not show in Archivist. 

Examples in instrument 2075 include c_qHist8_ii, c_qHist8_iii and c_qHist8_iv, c_qtest123 and c_qtest122 added inside other conditions or sequences. The first three were added between 12:00-12:30, and then 13:35. 

I did not receive any Heroku failure emails at this time. But I did receieve 4 between 13:06 - 13:13.

**Comment by simonreed** [comment]
@HayleyMills fix for this is now on staging

**Comment by HayleyMills** [comment]
Tested on staging and live and it is saving okay now.

**Comment by HayleyMills** [comment]
Reopening as this is happening again. Tested using onsls_01_hhe on the staging instance, when editing the logic of a condition, the constructs inside this condition disappear (lose their parent). I edited c_q10 logic which saved okay, but qc_12 lost it's parent. 

https://closer-archivist-staging.herokuapp.com/instruments/onsls_01_hhe/build/constructs/

**Comment by simonreed** [comment]
@HayleyMills This should now be fixed on staging, the issue was updating CcConditions would cause a strange tree structure.

**Comment by HayleyMills** [comment]
Tested on staging and no parents were lost when conditions were edited.

**Comment by HayleyMills** [comment]
Re-opening as this is happening again. Sarah found this in us instance 1780  us_covid_q9.

Statement s_jbindustry_xvii has lost it's parent, and so is not showing on the UI. 

I'll find out how this happened and try and replicate.

**Comment by HayleyMills** [comment]
Hopefully false alarm sorry, just found out this was entered in 2022, and so likely it's left over from then.
