### ISSUE TITLE
'Top Sequence' showing in construct and doc view for new instrument

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#222]
I created a new test instrument hm_test_1 and in the build view and doc view the top sequence label is now displaying 'Top Sequence' this is not usually visible. Not critical, but may display in Discovery when these new instruments are added.

**Comment by charlesdebarros** [comment]
To do:  Create new test instrument

**Comment by HayleyMills** [comment]
Created new instrument hm_test_3. The top sequence has automatically been labeled 'TopSequence', instead of it being null.

**Comment by charlesdebarros** [comment]
As per the code base, whenever a new instrument is created, by default a label 'TopSequence' will be added automatically (method add_top_sequence, # Creates an empty sequence as the top-sequence, i.e. parentless). 

I am changing "self.cc_sequences.create(label: 'TopSequence')" to "self.cc_sequences.create(label: nil)" in archivist/app/models/instrumen.rb
line 403.

Note: 'nil' is 'null' in Ruby. 

Tests in progress.

**Comment by charlesdebarros** [comment]
Updated code to correct issue. Set label to be NULL. 

See commit d163888.

**Comment by HayleyMills** [comment]
Checked this in the beta version which was updated. Top sequence is not showing as 'Top sequence' but issues related to the way the constructs are showing. See example below. 

![image](https://user-images.githubusercontent.com/16664703/44029134-1f15ef72-9ef4-11e8-8218-df819d63c5a3.png)

**Comment by charlesdebarros** [comment]
My mistake. Those 'extras' were added to help me debug the 'moving constructs' issue. I am remove those extras now.

**Comment by charlesdebarros** [comment]
'Extras' removed. Build page now back to displaying the normal data.

**Comment by HayleyMills** [comment]
Tested in the live version and Top Sequence is null for new instruments.
