### ISSUE TITLE
Not possible to remove topics mapped to questions in /tq.txt view

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#224]
The instrument map page for ncds_91_wdy shows that no topics have been applied, although not all questions have the option to add/see the topic (bug#215), but if you view the .txt file https://closer-archivist.herokuapp.com/instruments/ncds_91_wdyt/tq.txt it shows some mappings. These can not be overwritten by importing more mappings, as they are not replaced. I've looked at the links table and can't see any mappings there.

**Comment by HayleyMills** [comment]
This is true for all instruments and is problematic when mappings need to be replaced.

**Comment by charlesdebarros** [comment]
After a few adjustments, the dropdown menus are showing to all datasets in the Beta version. You should be able to make the changes you need to make.

I will add a few more datasets to have it tested more comprehensively.

**Comment by charlesdebarros** [comment]
Mappings seems to be displaying to the datasets now in the Beta version. I will add more testing cases just to make sure the issue has been rectified.

**Comment by HayleyMills** [comment]
The instrument map view is still not displaying the topic or the drop down list for ncds_91_wdyt?

**Comment by HayleyMills** [comment]
Can we add more info about what the problem is and how it was being solved in terms of the cache and remapping strands? 

Note that there are further problems related to loading mappings to datasets which I thought no mappings previously existed. For example I loaded mappings for hcs_2_clinic_6, which unfortunately I now believe may have had previous mappings, which were not yet remapped, and so this now has the same problem with the mappings not loading correctly and the /tv.txt containing different mappings.

**Comment by charlesdebarros** [comment]
After we flushed the Redis database, we had to re-build all strands. That involves re-mapping instruments' cc_questions and variables separately and then concatenating them back together. The process takes time as it is demanding in the database and heroku connection. I have been doing the rebuilding in stages and usually do it in times of low traffic. Timing out of the Heroku connection is also an issue as it may cause to have to restart the whole process.

A possible alternative proposed is to download a copy of the database, do the rebuilding process locally and the push the rebuild database back to Heroku. This would in theory be faster and would not disrupt people's work.

**Comment by HayleyMills** [comment]
Partly tested tq related mappings on staging Archivist. 
1) The file loads okay.
2) The /tq.txt is correct.
3) If there are existing tq mappings it overwrites these if topic id is not 0 and if it contains all questions. See queries below. 
4) conflicts- test this

Queries
7) Loaded qv, tv and tq using alspac_01_rat. I was able to overwrite the qv and tv mappings uploading files mapped to 0 so I could remove the mappings (although technically they should then be set to None), but this did not work for the tq file. It did overwrite when the mappings contained other topic ids. 
8) If there are incorrect questions/topics in the file (this includes difference in case) it doesn't look like it loads the rest of the file? (it doesn't overwrite) 
9) If the file only contains a sub-set of mappings it doesn't load the file (it doesn't overwrite).

**Comment by HayleyMills** [comment]
Tested on staging again and issues above still remain. @simonreed if you need more info or example please let me know.

**Comment by simonreed** [comment]
> 5) I am unable to load qt mappings which are mapped to 0 which is a valid topic of None. see https://closer-archivist-staging.herokuapp.com/instruments/alspac_99_ttd/imports/24

Is `0` a valid topic of `None`? Is `None` not in fact `000`. At the moment `0` is in fact used to show that the question has no topic set at all.

e.g.
```
qc_A1	0
qc_A2	103
qc_C2	000
```

In this example `qc_C2` has a topic set as `None` while `qc_A1` has no topic set.

**Comment by simonreed** [comment]
>8) When there are conflicts (when qv and tv have been loaded already) these are flagged in the log (https://closer-archivist-staging.herokuapp.com/instruments/alspac_99_ttd/imports/32) but they load okay into the instrument map view without showing any problem there or in the dataset view. So you could end up with there still being conflicts between the exported /tv.txt and the /tq.txt

If they show as errors in those logs then those records shouldn't have changed. Is that not the case?

**Comment by HayleyMills** [comment]
> 
> 
> > 1. I am unable to load qt mappings which are mapped to 0 which is a valid topic of None. see https://closer-archivist-staging.herokuapp.com/instruments/alspac_99_ttd/imports/24
> 
> Is `0` a valid topic of `None`? Is `None` not in fact `000`. At the moment `0` is in fact used to show that the question has no topic set at all.
> 
> e.g.
> 
> ```
> qc_A1	0
> qc_A2	103
> qc_C2	000
> ```
> 
> In this example `qc_C2` has a topic set as `None` while `qc_A1` has no topic set.

OK if its better to use 0 for clear and 000 as none, we will change our mappings for import from 0 to 000.

**Comment by HayleyMills** [comment]
> 
> 
> > 1. When there are conflicts (when qv and tv have been loaded already) these are flagged in the log (https://closer-archivist-staging.herokuapp.com/instruments/alspac_99_ttd/imports/32) but they load okay into the instrument map view without showing any problem there or in the dataset view. So you could end up with there still being conflicts between the exported /tv.txt and the /tq.txt
> 
> If they show as errors in those logs then those records shouldn't have changed. Is that not the case?
> 
> So as an example with https://closer-archivist-staging.herokuapp.com/instruments/alspac_99_ttd/imports/24 those mappings shouldn't have been saved so when you look at the instruments/datasets you shouldn't see the conflicts as they shouldn't have been saved. Is that not the case?

@simonreed It might be better if I step back a bit first. I removed all mappings for alspac_99_ttd (from db links and maps tables) Then I loaded qv and tv mappings. If you look at the map view- the topics haven't been inherited? https://closer-archivist-staging.herokuapp.com/instruments/alspac_99_ttd/map  

Note all questions are mapped to variable ccaa001

**Comment by simonreed** [comment]
It has in fact inherited them as you can see if you try to change the topic on any of those questions. This again comes down to the display of this on the UI. What i could do is like we do with the variables I show the 'Resolved Topic' in the https://closer-archivist-staging.herokuapp.com/instruments/alspac_99_ttd/map

**Comment by simonreed** [comment]
@HayleyMills I've updated this on staging to remove the links if they're not the txt imports. The conflicts now appear in instruments and datasets as part of #213 and #223 

I've also added the `Resolved Topic` section on the map screens

![image](https://user-images.githubusercontent.com/13276/65331739-43871300-dbb5-11e9-9e3c-6088aa71388c.png)

**Comment by HayleyMills** [comment]
Great. Tested on staging again, and now the inherited topics are visible on the map view. If there are conflicts then they are not loaded but are recorded in the import log.

**Comment by HayleyMills** [comment]
@simonreed should it be possible to delete q-v mappings? I've tired to delete the mapping between qc_A1 and ccad001, but it is not working? Is there a set way to do this (similar to the changing topic mappings).

**Comment by HayleyMills** [comment]
I have opened a new bug #380
