### ISSUE TITLE
.txt needed which includes sequences and question literals

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#227]
Previously the URL /mapper.txt (e.g. https://archivist.closer.ac.uk/instruments/bcs_80_pqf/mapper.txt) contained the questionnaire sequences as well as the question literals (see attached). This was replaced (~ Nov 2017) by /qc_questions.txt which only contains the questions. 

Vilma (CLS) is requesting this sequence info to help her with mapping variables to questions for MCS (due to duplicate question names in different sequences). Ideally she would like this by mid-late March. 

[mcs3_mapper_manual.txt](https://github.com/CLOSER-Cohorts/archivist/files/1771550/mcs3_mapper_manual.txt)

**Comment by charlesdebarros** [comment]
In my local machine, I have restored some of the code needed to display with information that Vilma needs. 

We will discuss with Jon/Vilma the best way to approach the final solution for this issue:  either deploying 'mapper' back as an extra feature (cc_questions.txt is still available and unaltered), or deploying just to the Beta version so as we can get the data that Vilma needs, without altering the codebase of the Live version.

**Comment by charlesdebarros** [comment]
Code correcting this issue has been uploaded. See commit 663fdbd.

**Comment by HayleyMills** [comment]
Tested in beta version and it is working as expected.

**Comment by HayleyMills** [comment]
It is now possible to view sequences and question items in the live version using /mapper.txt

**Comment by HayleyMills** [comment]
I have recently tried to use this, but noticed that it is not listing the questions with the URN for the sequence for all questions, but sometimes it has the condition parent instead. e.g. for https://archivist.closer.ac.uk/instruments/mcs1/mapper.txt  we can see that 
qc_PDOB_i is in sequence urn:ddi:uk.cls.mcs:mcs1-se-002299:1.0.0 which is  Household Module
but 
qc_PAGE_i is in condition urn:ddi:uk.cls.mcs:mcs1-if-005193:1.0.0 and so we can't tell which sequence it is in. 

Would there be a quick way to resolve this so all questions have their sequence URN ID listed?

**Comment by HayleyMills** [comment]
For info- this is only high priority for instruments MCS1 - 5 and would only be a low priority after the: question | sequence list had been created for those.

**Comment by HayleyMills** [comment]
Tested on staging and this working well. May need to revisit if this function is required more frequently as this the implementation may need to be improved for efficiency.
