### ISSUE TITLE
Large questionnaires and datasets not loading

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#228]
For example instruments MCS5 and US4 and datasets alspac_03_fa11 and alspac_01_fa9 (even when 2 dynos in use). Could be related to performance issue, so may be resolved once Ruby has been upgraded. Need to add a CAPI and/or large dataset to the beta version to test this.

**Comment by HayleyMills** [comment]
We need to be able to load us3 for USoc to review and us4 for UKDS placement student to work on.

**Comment by charlesdebarros** [comment]
Both instruments are now loading in the Live version. They might still struggle to load during times of heavy traffic, requiring a page refresh at time. 

I believe this has to do with speed in which some of the SQL queries are running. That is also proving problematic when deleting Instruments.

**Comment by charlesdebarros** [comment]
I am working on the database queries to make them faster and avoiding possible N + 1 scenarios.

**Comment by charlesdebarros** [comment]
Upgrading PostgreSQL to version 9.6 and upgrading the Heroku stash from version 14 to version 18 should provide some speed and improved performance. Working on additional existent N+1 issues will also improve performance and hopefully solve this issue. 

I shall do some more work on N+1 issues this week.

**Comment by HayleyMills** [comment]
Only small instruments will load. All instruments larger than ~75 constructs will not.

**Comment by spuddybike** [comment]
All bar the largest instruments now load, this is due to retrieving the response domains where there are very a large number of questions or mappings

**Comment by charlesdebarros** [comment]
I have updated the database query Archivist uses to gather data and load instruments.  The specific query for 'finding_closest_ancestral_topic' has been updated from a recurssive query to a simple join query. As a result, there is a 10-fold speed improvement when running the query.

Also, the method 'finding_closest_ancestral_topic' has been split into two different methods:
- 'find_closest_ancestor' runs the database query and holds the content
- 'find_closest_ancestor_topic' parses the result to the Instruments#show page

Those changes were to give each method only one task to perform. 

The referred changes are in 'app/lib/linkable_parent.rb'

**Comment by charlesdebarros** [comment]
I believe that, the way AngularJS and Javascript were set in Archivist, regardless of the page being loaded, the entire Javascript code is being loaded. For some pages this may not represent a big difference as the instrument/dataset/construct/etc content being loaded is very small but for larger instruments this is very probably slowing down the loading of the page. 

I will investigate further and make the necessary changes.

**Comment by charlesdebarros** [comment]
An update was release in the 08Feb with changes on some of the database queries. Those queries were slowing down/timing out the loading of pages. We are still struggling to load very large instruments, specially on shared dynos. 

I am working on other database queries (N+1 issues - Question Items is the next problematic one) and optmising Javascript loading on the pages.

**Comment by HayleyMills** [comment]
I have not had any problems with this on the staging.

**Comment by HayleyMills** [comment]
JS tested on USoc instance. When you update a condition and save it, then the qc labels inside the condition disappear on the screen. A refresh appears to bring them back. However this refresh is taking a long time for large instruments (even when dynos turned up).

**Comment by HayleyMills** [comment]
These are now loading, the only slow pages are the mapping pages which take a long time to load (if this is a problem I will create a new issue). Issue  #366 is related to loading and refreshing so I will close this issue.
