### ISSUE TITLE
Must refresh to see new constructs added. 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#231]
Previously didn't need to refresh to see a new construct added, but you did need to refresh to see a deletion (#229), now it is the opposite way round? Duplicate of #207

**Comment by HayleyMills** [comment]
Tested on staging and it is working okay.

**Comment by HayleyMills** [comment]
Tested on live and this is no longer working.

**Comment by simonreed** [comment]
@charlesdebarros I can't replicate this on https://closer-archivist-browsergroup.herokuapp.com/instruments/alspac_99_ttd/build/constructs any idea what steps i need to take?

**Comment by charlesdebarros** [comment]
I am not sure this is still an issue. I need Hayley's input on that one when she is back next week.

**Comment by simonreed** [comment]
@charlesdebarros is this still an issue then? Can we replicate on a staging/dev environment?

**Comment by HayleyMills** [comment]
Tested on live and this no longer seems to be an issue.
