### ISSUE TITLE
tv.txt files not loading

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#238]
Archivist will only load the first mapping in the tv.txt file for hcs_2_clinic_2. As far as I can tell the .txt file looks okay.

**Comment by HayleyMills** [comment]
The tv.txt files for alspac_98_fa7, alspac_99_fa8, alspac_01_fa9, alspac_02_fa10 and alspac_03_fa11are not loading into Archivist. The .txt files okay and the in-out-worker is on.

**Comment by HayleyMills** [comment]
Ongoing problems with loading mapping files to Archivist. 
alspac_ch_bloods tv.txt not loading, the file looks okay and the in-out-worker is on. Note the dv.txt did load okay. 

Also alspac_95_mnq stopped loading half-way through file- in order to get it to work I removed those already loaded and re-imported and it worked. Note that the expected and usual behaviour is that it ignores variables which are already loaded. 

See also issues #215, #252 and #224.

**Comment by HayleyMills** [comment]
bcs_96_q_tv.txt and bcs_80_me_tv.txt only loading the first variable in the files import at a time. 

I import the mapping file and it imports the first variable topic mapping. I remove the first variable frmo the file, and save as bcs_96_q_tv_cut.txt. I then upload that mapping file and it then loads the first one of that file.

**Comment by HayleyMills** [comment]
ncds_91_cmi.tv.txt only some of the variable topics have loaded.

**Comment by simonreed** [comment]
@HayleyMills do we have an example txt file for this, how do I replicate?

**Comment by HayleyMills** [comment]
@simonreed I am no longer able to replicate the problem, as there are now mappings which have loaded for these files, although they are not the correct mappings in /tv.txt. See https://closer-archivist-staging.herokuapp.com/datasets/630 for example. I have attached the tv.txt file which would have been loaded. Many of the examples given above are mapped to 104 in the /tv.txt? 
[hcs_2_clinic_2_tv.txt](https://github.com/CLOSER-Cohorts/archivist/files/3501650/hcs_2_clinic_2_tv.txt)

I can try and replicate the issues described above by removing all the mappings, but since the mappings on the UI do not match the /tv.txt it would likely be affected by the cache issues? #224

**Comment by HayleyMills** [comment]
@simonreed tried to load tv.txt file for nshd_89_dsq in the staging server but I receive the error message "Something went wrong, please import the file again.". 

[nshd_89_dsq.tvlinking.txt](https://github.com/CLOSER-Cohorts/archivist/files/3569329/nshd_89_dsq.tvlinking.txt)

[tv.txt](https://github.com/CLOSER-Cohorts/archivist/files/3569338/tv.txt)

**Comment by simonreed** [comment]
@HayleyMills Sorry the deployment wasn't complete. You can now import them as expected. Here's the import for the nshd_89_dsq.tvlinking.txt I did yesterday https://closer-archivist-staging.herokuapp.com/datasets/488/imports

**Comment by HayleyMills** [comment]
@simonreed sorry I was too keen! I've tested the import for tv.txt using hcs_2_clinic_11. This loaded correctly, the /tv.txt is working and the log view is great. I loaded another tv.txt to test the overwriting and this also worked as expected. The topics were deleted and the remapped. 

The questions also now have topics assigned to them- but I'm not sure how, as I have been unable to load the qv mappings yet? Maybe this was a hangover from before?- I'll test again on another dataset.  

[tv.txt](https://github.com/CLOSER-Cohorts/archivist/files/3573508/tv.txt)
[tv2.txt](https://github.com/CLOSER-Cohorts/archivist/files/3573527/tv2.txt)

**Comment by HayleyMills** [comment]
Following up on my last comment, it looks like most there are tq mappings for lots of instruments in the db already, and so I think those for hcs_2_clinic_11 were already there. I'll remove those mappings first.

**Comment by HayleyMills** [comment]
Tested in staging again using alspac_01_rat. 
The following is all working okay and as expected: 
1) The file loads okay. 
2) The /tv.txt is correct. 
3) If there are variables/topics in the file it logs these in the import log. 
4) If there are existing tv mappings it overwrites these. 
5) If there are qv and tq mappings already and load a tv with a conflict, it flags this in the import log and in the UI- the map view and the dataset view for that show them mapped to loaded (i.e. different topics). I think this is okay, as it is helpful to see both so you can then decide which one is most suitable. 
6) You can change the topic either on the map view or the dataset view to resolve it. 

Queries:  
6)  It would be nice if the instrument map view also showed the red conflict message in the same way as the dataset page (in relation to point 5). 

7) Is it case sensitive? I tried to load tv mappings with a different case, and it didn't map?

8) Variables which are mapped to 0 should map to None rather than staying clear- I don't think 0 are being picked up to map, as they appear in the import log as not loading? See end of https://closer-archivist-staging.herokuapp.com/datasets/573/imports/12 and attached file. 

9) Is the log reporting all issues- in relation to 8) it looks like the log only reports back on the first two variables mapped to 0 (ccg011b and ccg011a)? I may need more help in understanding what the log reports. 

[alspac_01_rat.tvlinking.txt](https://github.com/CLOSER-Cohorts/archivist/files/3580119/alspac_01_rat.tvlinking.txt)

**Comment by simonreed** [comment]
> Queries:
> 6) It would be nice if the instrument map view also showed the red conflict message in the same way as the dataset page (in relation to point 5).

This will be deployed to staging today.

> 
> 7. Is it case sensitive? I tried to load tv mappings with a different case, and it didn't map?

Yes it's case sensitive when matching variables and topics.

> 8. Variables which are mapped to 0 should map to None rather than staying clear- I don't think 0 are being picked up to map, as they appear in the import log as not loading? See end of https://closer-archivist-staging.herokuapp.com/datasets/573/imports/12 and attached file.
> 9. Is the log reporting all issues- in relation to 8) it looks like the log only reports back on the first two variables mapped to 0 (ccg011b and ccg011a)? I may need more help in understanding what the log reports.

You're seeing a bug with the reporting of those. I'll take a look. It is reading and acting on each line but the formatting of the logs is confusing. I'll fix this.

> 10. When I load qv and tq files, I would expect the tv to inherit the topics fully, currently it only adds these as 'Resolved Topic' and these are not in the DB?

A `Resolved Topic` is an inherited topic, it's not stored in the DB for the question or variable but the `Resolved Topic` is used.

**Comment by HayleyMills** [comment]
7) > Yes it's case sensitive when matching variables and topics.
I don't think the qv loading is case-sensitive- can we change this so it ignores the case please? 

8) > You're seeing a bug with the reporting of those. I'll take a look. It is reading and acting on each line but the formatting of the logs is confusing. I'll fix this.
They are appearing in the dataset view as clear rather than None for 0s?

10) > A Resolved Topic is an inherited topic, it's not stored in the DB explicitly for the question or variable but the Resolved Topic (inherited topic) is used.

I'm not sure what this means- how do we get the inherited (resolved) topics to load into the DB?

**Comment by HayleyMills** [comment]
@simonreed can you take a look at this queries please? Let me know if you want me to retest this.

**Comment by simonreed** [comment]
> 7. > Yes it's case sensitive when matching variables and topics.
> 
> I don't think the qv loading is case-sensitive- can we change this so it ignores the case please?
> 

The variable mapping is for qv is not case sensitive anylonger but the question is. I'll change that so both of them ignore case.

> 8. > You're seeing a bug with the reporting of those. I'll take a look. It is reading and acting on each line but the formatting of the logs is confusing. I'll fix this.
> 
> They are appearing in the dataset view as clear rather than None for 0s?
> 

This has been fixed on staging however, let me fix the point above and then we can test all of this issue as one.

> 10. > A Resolved Topic is an inherited topic, it's not stored in the DB explicitly for the question or variable but the Resolved Topic (inherited topic) is used.
> 
> I'm not sure what this means- how do we get the inherited (resolved) topics to load into the DB?

I'll give you the following scenario to hopefully explain better :

```
Given we have a question 'qc_1'
and 'qc_1' has a topic of 'Housing' in the database
and a variable 'v1'
and 'v1' has no topic set in the database
When 'qc_1' is linked to 'v1'
Then 'v1' will have a resolved topic of 'Housing' inherited from 'qc1'
and in the database 'v1' will still have no topic set in the database
and when looking at the topic for 'v1' you will be returned 'Housing' in the web UI or in the exports
```

We check to see if a question/variable has a topic explicitly set, if not then we will look to see if one can be inherited (aka resolved topic). Does that make it clearer?

**Comment by HayleyMills** [comment]
Thanks @simonreed let me know when you are happy for me to test further. 

In terms of the  inherited (resolved) topics, that does make sense thanks. Would it be possible to update the db with these, so that the exported /txt files always match the db?

**Comment by simonreed** [comment]
Unfortunately it's not straightforward as if we updated the db topics with the inherited topics then there would be no way for us to know which question/variable is inheriting the topic and who has it explicitly set.

**Comment by HayleyMills** [comment]
Every mapped q-v should have the same topic and so does it matter if we don't know which have been explicitly set and which have been inherited? Apologies if I'm missing the point or being over simplistic, but I'm just concerned that the only place where the final version of the mappings is held is within the exported txt files rather than the DB. In the past the /txt files have not been reliable and so the DB was always the definitive version.

**Comment by simonreed** [comment]
Sorry to clarify the inherited topics are still stored in the database, so if you did a back of the database it would be persisted there.  It's just stored in a different way than if you set a topic explicitly on a question/variable but it's definitely still there.

**Comment by HayleyMills** [comment]
Okay thanks, is it easy for me to look it up in the DB if I needed to? As usually I would use the tables links and maps if needed- but if this is stored somewhere else, it would be useful to know where. I guess I'm being overly cautious because of the previous problems.

**Comment by simonreed** [comment]
@HayleyMills 

To find the topic and inherited topic for a variable :

```
SELECT  variables.id, topics.name as topic_name, mapped_topics.name as inherited_topic_name
FROM variables
INNER JOIN "maps" ON "maps"."variable_id" = variables.id
INNER JOIN "links" AS mapped_links ON "mapped_links"."target_id" = "maps"."source_id" AND "mapped_links"."target_type" = maps.source_type
INNER JOIN "topics" as mapped_topics ON "mapped_topics"."id" = "mapped_links"."topic_id"
INNER JOIN "links" ON "links"."target_id" = "variables"."id" AND "links"."target_type" = 'Variable'
INNER JOIN "topics" ON "topics"."id" = "links"."topic_id"
WHERE variables.id = 48761;
```
gives you :

```
  id   | topic_name | inherited_topic_name 
-------+------------+----------------------
 48761 | Allergies  | Allergies
```

Doing the same for a CcQuestion is :

```
SELECT  cc_questions.id, topics.name as topic_name, maps.variable_id, mapped_topics.name as inherited_topic_name
FROM cc_questions
INNER JOIN "maps" ON "maps"."source_id" = cc_questions.id
INNER JOIN "links" AS mapped_links ON "mapped_links"."target_id" = "maps"."variable_id" AND "mapped_links"."target_type" = 'Variable'
INNER JOIN "topics" as mapped_topics ON "mapped_topics"."id" = "mapped_links"."topic_id"
INNER JOIN "links" ON "links"."target_id" = "cc_questions"."id" AND "links"."target_type" = 'CcQuestion'
INNER JOIN "topics" ON "topics"."id" = "links"."topic_id"
WHERE cc_questions.id = 125243;
```

and gives you :

```
   id   | topic_name | variable_id | inherited_topic_name 
--------+------------+-------------+----------------------
 125243 | Allergies  |       48759 | Allergies
 125243 | Allergies  |       48760 | Urogenital system
 125243 | Allergies  |       48761 | Allergies
 125243 | Allergies  |       48762 | Allergies
 125243 | Allergies  |       48763 | Allergies
 125243 | Allergies  |       48764 | Allergies
 125243 | Allergies  |       48765 | Allergies
 125243 | Allergies  |       48766 | Allergies
 125243 | Allergies  |       48768 | Allergies
 125243 | Allergies  |       48769 | Allergies
 125243 | Allergies  |       48770 | Allergies
 125243 | Allergies  |       48771 | Allergies
 125243 | Allergies  |       48772 | Allergies
 125243 | Allergies  |       48773 | Allergies
 125243 | Allergies  |       48774 | Allergies
 125243 | Allergies  |       48775 | Allergies
```

from the above you can see that there is a conflict between CcQuestion 125243 and variable 48760.

**Comment by HayleyMills** [comment]
@simonreed I'm having problems uploading a tv.txt file. I initially (accidentally) uploaded a file with three columns instead of two and so it obviously didn't load so I tried again with the standard two columns (twice) but they are all still stuck pending?  https://closer-archivist-staging.herokuapp.com/datasets/269/imports

**Comment by HayleyMills** [comment]
> 
> 
> @simonreed I'm having problems uploading a tv.txt file. I initially (accidentally) uploaded a file with three columns instead of two and so it obviously didn't load so I tried again with the standard two columns (twice) but they are all still stuck pending? https://closer-archivist-staging.herokuapp.com/datasets/269/imports

My fault! I forgot to turn of the in-out-worker!!

**Comment by HayleyMills** [comment]
Tested on live and loading TV seems- variables to be case sensitive?

**Comment by HayleyMills** [comment]
Created new issue #381
