### ISSUE TITLE
When copying an instrument it keeps the orginal global attributes

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#239]
That in itself is not a problem, but when you copy an instrument it gives you an option to add a title, as well as changing the study, agency and version, and so you think you have made these amendments, but it is then not saved. 

The new attributes should either be saved, or we should only have the option of adding a new prefix. 

In addition the control construct count on the instrument page does not reflect the actual number of constructs, which should be the same as the original.

**Comment by spuddybike** [comment]
Use fragments to export items where not completed instrument
