### ISSUE TITLE
Lock instruments after signing them off

### ISSUE THREAD

**Issue by charlesdebarros** [CLOSER-Cohorts/archivist#241]
Add a feature to prevent users from editing instruments after they have been signed off. If changes are needs, and Admin will have to 'unlock' the specifit instrument.

**Comment by HayleyMills** [comment]
This needs to be considered in light of the changes in functionality of Archivist i.e. a central Archivist archive will contain everything completed, with other users not having access to this?

**Comment by HayleyMills** [comment]
@simonreed the instrument pages are not loading? https://closer-archivist-staging.herokuapp.com/instruments

**Comment by spuddybike** [comment]
this should fix it? @HayleyMills now on staging to test

**Comment by HayleyMills** [comment]
@simonreed @spuddybike Instruments are still not loading?

**Comment by simonreed** [comment]
@HayleyMills I've ran the database migration in, the page is loading correctly now.

**Comment by HayleyMills** [comment]
Tested on staging  bcs_80_pi and this works well. However, I'm not sure if the ticking/unticking is taking a while to be seen in Archivist or whether I'm having to do it a few times- it's hard to tell, as when I untick in the admin and it doesn't unlock (after refreshing), when I go back to admin/edit it is still ticked. 

I will discuss with @spuddybike but I think this locking is for just instruments being signed off- if so then we can leave the map view unlocked. We would also need to allow mappings to be imported. 

However, if we want the dataset/mappings to be included in being locked, then we might need to think how to handle the dataset page, which is not locked, but could have multiple instruments linked to the dataset.

**Comment by spuddybike** [comment]
Let’s talk about it tomorrow

**Comment by spuddybike** [comment]
I think as long as the questionnaire can't be edited that is fine - but it seems we need another go at this so that the ticking / unticking works properly

**Comment by HayleyMills** [comment]
Tested again on staging and on roll out on HEAF and it is working well, but we need to change this so it doesn't lock the importing of mappings @simonreed and @spuddybike

**Comment by spuddybike** [comment]
@simonreed - would you have some time this week when you have a convenient stopping point on the other development

**Comment by spuddybike** [comment]
@HayleyMills now ready for testing on Staging

**Comment by HayleyMills** [comment]
Tested on staging and I still can't see the import mappings option when the instrument is locked?

**Comment by HayleyMills** [comment]
Add this functionality to React Archivist.

**Comment by simonreed** [comment]
@HayleyMills the functionality for this and the ability to sign off an instrument in the admin form is now on the staging site.

**Comment by HayleyMills** [comment]
Tested on staging and this is working.
