### ISSUE TITLE
Unable to delete instruments

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#242]
Trying to delete hm_test_3 and hm_test_4 which are not linked to datasets, with the in-out-worker on, but they will not delete.

**Comment by charlesdebarros** [comment]
Rewriting and running all tests related to a 'delete' action.

**Comment by charlesdebarros** [comment]
Related to #253 
As deleting cc_questions is taking a long time, the process times out after 30s and as a consequence the instrument is not deleted. Skylight reports point out to cc_questions queries and the SQL query on ancestral_topic.

**Comment by charlesdebarros** [comment]
See #253

**Comment by charlesdebarros** [comment]
See update in #253

**Comment by HayleyMills** [comment]
Tested on staging and it is working okay.

**Comment by HayleyMills** [comment]
Tested on live and it is working okay.

**Comment by HayleyMills** [comment]
Can we please delete from the table identifiers when an instrument is deleted?

**Comment by simonreed** [comment]
@HayleyMills the identifiers should be deleted and that's what i'm seeing when trying to reproduce locally. Which instrument was it that you had this issue with? Trying to replicate the issue locally.

**Comment by HayleyMills** [comment]
@simonreed this was on the ONSLS version of Archivist. Do you have access to that? I deleted jp_test, as a test and there are still in entries in the database for this.

**Comment by simonreed** [comment]
@HayleyMills no I don't have access to that @spuddybike could I get access.

Do you remember if it the identifier was for a specific kind of item?

**Comment by HayleyMills** [comment]
@simonreed I have done a quick test on staging and you are correct it did delete OK. The versions of Archivist are the same on both, so do you think it's a setup issue? I'll test another version. 

In the ONSLS test example they are all categories, but I'm not sure for the other example. I deleted onsls_81_hhe and then reloaded, but received 'Invalid :  PG::UniqueViolation: ERROR:  duplicate key value violates unique  constraint "index_identifiers_on_id_type_and_value" DETAIL:  Key (id_type, value)=(urn,  urn:ddi:uk.ons:onsls_81_hhe-qi-000525:1.0.0) already exists. : INSERT INTO "identifiers" ("id_type", "value", "item_type", "item_id",  "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING  "id"' if that helps?

**Comment by HayleyMills** [comment]
The versions of Archivist are different, so are behaving differently. This will be fixed in the other versions of Archivist when it is rolled out.

**Comment by HayleyMills** [comment]
Occasionally an instrument will not delete from Archivist e.g. alspac_91_pq_old will not delete from the live version Archivist.

**Comment by HayleyMills** [comment]
Doesn't appear to a problem anymore
