### ISSUE TITLE
Unable to delete constructs, datasets, maps, links etc. 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#253]
It is not possible to delete:
- a dataset which has no links or maps with the in-out-worker on
- links and maps in the database tables
- a construct
- an instrument see #242.  

The most problematic issue is the deleting of constructs as this causes a backlog of queries which eventually causes Archivist to crash. 

Note deleting works on the beta.

**Comment by HayleyMills** [comment]
Is this related to deleting from views, rather than the tables?

**Comment by charlesdebarros** [comment]
Deleting 'statements' is working fine. Attempts to delete 'loops', 'conditions', 'questions' and ' sequences' still cause Archivist's to timeout and crash.

**Comment by charlesdebarros** [comment]
I believe I narrowed down the problem to the relation between cc_questions and links (topics). Those two database queries are the ones which take the longest to run, usually about 4s each, for each construct.

I also believe the problem very probably lies in the following SQL query:

SELECT id, name, parent_id, code, created_at, updated_at, description
FROM ancestral_topic
WHERE construct_id = ?
AND construct_type = ?

**Comment by charlesdebarros** [comment]
I am working on two front on this issue and its links to the ancestral topics: either remove the ancestral_topic Materialized View altogether or changing the code that generated that view. 

I have both scenarios running at the moment, one in the Mac desktop and one in my laptop.

**Comment by charlesdebarros** [comment]
I am working on two front on this issue and its links to the ancestral topics: either remove the ancestral_topic Materialized View altogether or changing the code that generated that view. 

I have both scenarios running at the moment, one in the Mac desktop and one in my laptop.

**Comment by charlesdebarros** [comment]
I have removed the code related to the ancestral_topic materialized view and restore the old database query that existed before the materialized view was implemented. Adjustments in the instruments controller and other related controllers were made. 

I have uploaded the adjusted code to the Dev, and later, to the Staging environments for testing purposes. Instruments are loading as normal, moving constructs seems to be working well and the ability to delete instruments, datasets and constructs seem to be restored. 

I am working on further tests this week before pushing the code to the Production environment.

**Comment by charlesdebarros** [comment]
Just as note, due to the changes in the Instruments and other controllers, some of the tests previously written are failing. I will have them corrected in due time.

**Comment by HayleyMills** [comment]
Tested on staging and is working okay.

**Comment by HayleyMills** [comment]
Tested deleting instrument and constructs on live and this seems to be working.
