### ISSUE TITLE
Displaying error messages in Archivist

### ISSUE THREAD

**Issue by charlesdebarros** [CLOSER-Cohorts/archivist#259]
Archivist's error messages need to be adjusted and corrected.

The error messages displayed in Archivist are not usually very helpful and some of times the information displayed is incorrect. 

As an example, whenever a user tries to import an instrument or dataset, and either have already been imported, Archivist does not display a warning message saying that that instrument/dataset had already been imported. It just displays "Instrument imported" or "Dataset imported", even though nothing has been impored. 

That is a way is linked to the 'false-positives' we get from some of Archivist's the unit tests.

**Comment by charlesdebarros** [comment]
More suitable error messages will provide a better User Experience.

**Comment by HayleyMills** [comment]
Covered by #422
