### ISSUE TITLE
USoc to Archivist parser not working as it should. 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#264]
The original us2caddies parser was re-written and integrated into Archivist, however this is not working in the same way as the previous parser. There are several problems which need to be resolved before it can be used. I've attached a table which contains the issues.

[Understanding society parser checks and changes.docx](https://github.com/CLOSER-Cohorts/archivist/files/2579954/Understanding.society.parser.checks.and.changes.docx)

**Comment by spuddybike** [comment]
This parser should be replaced with the python based parser and removed from Archivist

**Comment by spuddybike** [comment]
I think we need to talk about this and whether the python based parser is really the best way to go -

**Comment by HayleyMills** [comment]
Jenny Li is working on a new parser outside of Archivist so we might want to remove this function from Archivsit.

**Comment by spuddybike** [comment]
superfluous as this is done outside o Archivist
