### ISSUE TITLE
Documentation / readme instructions 

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/archivist#266]
These need updating to reflect a good set of local install instructions

**Comment by charlesdebarros** [comment]
Two entries have been added to Archivist's Github Wiki:
- A short welcome message to Archivist, and
- An "Installing Archivist" page.

Next I will add how to install some of the dependencies needed to install Archivist.

**Comment by HayleyMills** [comment]
@simonreed @spuddybike has this now been sorted by the #608 ?

**Comment by simonreed** [comment]
@HayleyMills we now have a functional Heroku installer. @spuddybike is that enough to close this or do we still want further documentation?

**Comment by spuddybike** [comment]
we can close
