### ISSUE TITLE
Archivist should not save .xml file to Documents table if the instrument/dateset is not imported

### ISSUE THREAD

**Issue by charlesdebarros** [CLOSER-Cohorts/archivist#268]
When a user uses an .xml file to import an instrument or dataset, if the importing action fails, an .xml file reference is still saved in the Documents table. If the user tries to import the instrument/dataset again, Archivist will not attempt to reimport the data from the file as a file reference already exists in the database and Archivist assumes the file has already been imported. 

Maybe Archivist should throw a warning informing that that .xml file already exists in the database and possibly ask the user whether they want to replace/overwrite it.

**Comment by charlesdebarros** [comment]
Possibly related to ""duplicate" variable action 'do nothing' (line 3). See Importers::XML::DDI::instrument method below:

```ruby
def self.build_instrument(doc, options= {})
  save = defined?(options[:save]) ? true : options[:save]
  duplicate = defined?(options[:duplicate]) ? :do_nothing : options[:duplicate]

  i = ::Instrument.new
  begin
    i.label = doc.xpath('//InstrumentName//String').first.content
  rescue
    i.label = 'Missing name'
  end
  urn_pieces = doc.xpath('//URN').first.content.split(':')
  i.agency = urn_pieces[2]
  i.prefix = urn_pieces[3].split('-ddi-')[0]
  instruments = ::Instrument.where({prefix: i.prefix})
  if instruments.length > 0
    Rails.logger.info 'Duplicate instrument(s) found while importing XML.'
    if duplicate == :do_nothing
      raise Exceptions::ImportError, 'Aborting XML import. Consider passing a duplicate option to importer.'
    else
      if duplicate == :update || duplicate == :replace
        if instruments.length == 1
          if duplicate == :update
            i = instruments.first
          else
            instruments.first.destroy
          end
        else
          raise Exceptions::ImportError, 'Aborting XML import. Cannot update or replace instrument as multiple duplicates found.'
        end
      end
    end
  end
  i.version = '1.0'
  if save
    i.save!
  end
  return i
end
```

**Comment by HayleyMills** [comment]
This appears to be still happening- I imported ncds_81_i_test to staging server but it did not load because of a problem with the XML (see error), but it did create a document in the documents table. As far as I know this is not causing any issues. What is the relationship between this and the updated importer?

**Comment by HayleyMills** [comment]
@simonreed has this now been resolved?

**Comment by simonreed** [comment]
@HayleyMills yes this should now be resolved. It does still keep the invalid .xml in the database as a document however this doesn't cause any issue with reuploading the correct .xml file again.
