### ISSUE TITLE
Ability to export mapping .txt files (3/4 column) for each instrument 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#276]
It should export with three or four columns as the default.  Examples attached
[alspac_00_msdhs.dv.txt](https://github.com/CLOSER-Cohorts/archivist/files/3198279/alspac_00_msdhs.dv.txt)
[alspac_00_msdhs.qvmapping.txt](https://github.com/CLOSER-Cohorts/archivist/files/3198282/alspac_00_msdhs.qvmapping.txt)
[alspac_00_msdhs.tqlinking.txt](https://github.com/CLOSER-Cohorts/archivist/files/3198284/alspac_00_msdhs.tqlinking.txt)
[alspac_00_msdhs.tvlinking.txt](https://github.com/CLOSER-Cohorts/archivist/files/3198286/alspac_00_msdhs.tvlinking.txt)

**Comment by HayleyMills** [comment]
![image](https://user-images.githubusercontent.com/16664703/65420273-a0bed680-ddf8-11e9-85b5-181786610583.png)

**Comment by simonreed** [comment]
@HayleyMills @spuddybike If we change the export txt files to the new format and not the importer then it will mean you cannot re-import an exported txt file. Does that mean we also need to change the importer as well, as the importer will be looking for the existing number of columns?

**Comment by simonreed** [comment]
What db column do you want to use for `Dataset Instance`?

**Comment by HayleyMills** [comment]
I think it would need to be the first part of column filename. So everything before the .ddi32.rp.xml. Is that possible?

**Comment by HayleyMills** [comment]
Tested on the staging and it is exporting 3/4 columns for all .txt files.
