### ISSUE TITLE
Backup of instruments should be database based not rely on XML export

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/archivist#277]
a. Regular backups (weekly and monthly) should be instituted
b. Testing of import of instance (and dependencies) from backup
    i. From existing instance of backup
    ii. from external instance of backup

**Comment by charlesdebarros** [comment]
This could be linked to issue #279 as when editing categories, Archivist leaves orphan categories in the XML, which might cause issues when trying to re-import and instrument.

**Comment by spuddybike** [comment]
This seemed like a good idea
