### ISSUE TITLE
Categories - where they have been used

### ISSUE THREAD

**Issue by stadqssf** [CLOSER-Cohorts/archivist#28]
To be able to see where (in which questions) each category has been used.

**Comment by wpoynter** [comment]
This will not be simple to add, what is the main purpose of this feature?

**Comment by stadqssf** [comment]
At present (in verification) if a minor amendment is made to a category e.g. ‘I should gone to the shops’ becomes ‘I should have gone to the shop’ it is not possible to see directly in what code schemes/questions the category has been used as with:

Code Answer e.g.
Id: 12
All Answer Id: 18 This is the Id required when creating/editing question items
Code list:

 *   Id: 16
 *   Short description: cs_YES_NO
 *   Codes:
Value

Category text

Cat Id

Order

1

YES

8

1

2

NO

9

2

Used in the following question items:
Id

Name

Intent

46

qi_C1_c








I think it would be a useful minor feature but maybe not needed in Archivist if there is another way of seeing this!
