### ISSUE TITLE
It is not possible to change a response domain attached to a question grid

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#282]
This may relate to #82. For single column grids which have a response domain attached, it is not possible to change the response domain. There is no workaround other than deleting and recreating the grid. 

It is possible to change a response domain in a multi-column grid however.

**Comment by HayleyMills** [comment]
Test using https://closer-archivist-staging.herokuapp.com/instruments/1033/build/questions/question_grids/7114 
I removed the RD and then added a new one, but after saving it reverts back to the original.

**Comment by simonreed** [comment]
There are 2 data issues at play here. 

1. We had a number of `RdsQs` records in the db with `code_id` of `null` but associated with a `QuestionGrid` which meant that there was no way for the UI to remove this Response Domain. There is no valid reason as far as I'm aware for a QuestionGrid to have no `code_id` associated with it so I've removed these from the staging db.

2. We have duplicate `RdsQs` records for a `QuestionGrid` with the same `code_id`. This means that you can remove one Response Domain but it appears as if it hasn't removed it because now just shows the duplicate.

e.g.
```
RdsQs Load (0.4ms)  SELECT "rds_qs".* FROM "rds_qs" WHERE "rds_qs"."question_id" = $1 AND "rds_qs"."question_type" = $2  [["question_id", 11158], ["question_type", "QuestionGrid"]]


=> [#<RdsQs:0x00007fa82184a208 id: 192162, response_domain_id: 8494, response_domain_type: "ResponseDomainNumeric", question_id: 11158, question_type: "QuestionGrid", created_at: Thu, 21 Feb 2019 15:07:35 UTC +00:00, updated_at: Thu, 21 Feb 2019 15:07:35 UTC +00:00, code_id: nil, instrument_id: 1684, rd_order: 1>,

 #<RdsQs:0x00007fa82184a0a0 id: 194690, response_domain_id: 8494, response_domain_type: "ResponseDomainNumeric", question_id: 11158, question_type: "QuestionGrid", created_at: Mon, 22 Jul 2019 14:26:22 UTC +00:00, updated_at: Mon, 22 Jul 2019 14:26:22 UTC +00:00, code_id: 1, instrument_id: 1684, rd_order: nil>,

 #<RdsQs:0x00007fa821849f38 id: 194692, response_domain_id: 8494, response_domain_type: "ResponseDomainNumeric", question_id: 11158, question_type: "QuestionGrid", created_at: Mon, 22 Jul 2019 14:27:00 UTC +00:00, updated_at: Mon, 22 Jul 2019 14:27:00 UTC +00:00, code_id: 1, instrument_id: 1684, rd_order: nil>]``` 

Records 194690 and 194692 are duplicates so if we click to remove `194690` it will then show `194692`. In the UI you can now not create this duplicates however they exist in the DB.

I'd suggest that we go through and remove this duplicates leaving the only the most recent record.

**Comment by HayleyMills** [comment]
@simonreed Thanks for flagging this. Yes you can remove the duplicates, keeping whichever one is currently visible in the UI please.

**Comment by simonreed** [comment]
Just for future tech reference this is the SQL command used to remove the duplicates, leaving only the oldest version (which is what is shown the UI, so no change for the user)

SQL

```
DELETE FROM 
    rds_qs
USING (SELECT 
      "rds_qs"."question_id", 
      "rds_qs"."question_type",
      "rds_qs"."code_id",
      min("rds_qs"."created_at") as firstTimestamp
    FROM "rds_qs"
    WHERE (code_id IS NOT NULL AND question_type = 'QuestionGrid') 
    GROUP BY "rds_qs"."question_id", "rds_qs"."question_type", "rds_qs"."code_id"
    HAVING (count(*) > 1)) dupes
WHERE
    rds_qs.question_id = dupes.question_id
    AND rds_qs.question_type = dupes.question_type
    AND rds_qs.code_id = dupes.code_id
    AND rds_qs.created_at > dupes.firstTimestamp;
```

And in the Rails console

```
ActiveRecord::Base.connection.execute(%q|DELETE FROM rds_qs USING (SELECT "rds_qs"."question_id", "rds_qs"."question_type", "rds_qs"."code_id", min("rds_qs"."created_at") as firstTimestamp FROM "rds_qs" WHERE (code_id IS NOT NULL AND question_type = 'QuestionGrid')  GROUP BY "rds_qs"."question_id", "rds_qs"."question_type", "rds_qs"."code_id" HAVING (count(*) > 1)) dupes WHERE rds_qs.question_id = dupes.question_id AND rds_qs.question_type = dupes.question_type AND rds_qs.code_id = dupes.code_id AND rds_qs.created_at > dupes.firstTimestamp;|)
```

**Comment by simonreed** [comment]
@HayleyMills this should now be fixed on staging.

**Comment by HayleyMills** [comment]
Tested on staging with hm_test_1 and it is now possible to change a response domain on a question grid. 

I think the deletion of the duplicates, may have had unintended consequences however, as having had a quick look, it appears there are now grids which do not have any response domain attached, but which did previously e.g. 
alspac_03_aam qg_B1_c_i-vi
alspac_01_msdms qg_A9_a-f
alspac_96_ml qg_A1_a-j
It looks like it is okay (from the few I checked) when there is more than one column, as these have retained there response domains.  

It looks like it may have deleted rds_qs where the code_id and rd_order where null even when there was no duplicate row for that question_id?

**Comment by simonreed** [comment]
Hmm ok yes it would have deleted the `rds_qs` if there `code_id` was nil. That issue wasn't related to duplicates.

What do you think we should do for those that had a `code_id` of nil as they should have `code_id` so any ideas what `code_id` we should replace them with?

**Comment by HayleyMills** [comment]
As far as I can tell, the code_id is used in multi-column grids where a response domain is needed for each column in the grid i.e. each code list category on the X axis (the code_id looks like the code value for this). 

Where there is only a single column, then if a code_id is needed, then it could be set to 1? I'm not sure how the code_id is created, but in Archivist when we create an X axis code list we always start from 1 in the code values. - Does this make sense?  

I understood that the issue was related to duplicate response domains attached to the same question? So for example in instrument 1241 question_id 8664, there are multiple rds_qs with the same response_domain_id associated with the same question which is fine, but they also have the same code_ids. So likely when you click remove on a question grid response domain, and save it, it will not remove as there will be another to take its place?

**Comment by simonreed** [comment]
I need @charlesdebarros or @spuddybike to migrate the production database back onto staging so we can try this data migration/cleanup again.

> As far as I can tell, the code_id is used in multi-column grids where a response domain is needed for each column in the grid i.e. each code list category on the X axis (the code_id looks like the code value for this).

The code_id should be set for all RdsQs records for a `QuestionGrid` even if it's not multi-column. 

> Where there is only a single column, then if a code_id is needed, then it could be set to 1? I'm not sure how the code_id is created, but in Archivist when we create an X axis code list we always start from 1 in the code values. - Does this make sense?

It does, this is what happens at the moment in the UI so unsure how this invalid data was created.

> I understood that the issue was related to duplicate response domains attached to the same question? So for example in instrument 1241 question_id 8664, there are multiple rds_qs with the same response_domain_id associated with the same question which is fine, but they also have the same code_ids. So likely when you click remove on a question grid response domain, and save it, it will not remove as there will be another to take its place?

Correct, that's the issue we are seeing on production, it looks like you're not removing a RdsQs but in you are it's just showing the duplicate from the db after the initial RdsQs was removed.

Just to clarify, this is what we've done on staging for the 2 data issues, could you let me know what you think we should be doing with these once the staging data has been reset to production data once again.

> There are 2 data issues at play here.
> 
> 1. We had a number of `RdsQs` records in the db with `code_id` of `null` but associated with a `QuestionGrid` which meant that there was no way for the UI to remove this Response Domain. There is no valid reason as far as I'm aware for a QuestionGrid to have no `code_id` associated with it so I've removed these from the staging db.

We removed all RdsQs if it was related to a QuestionGrid and the code_id was nil. 

> 2. We have duplicate `RdsQs` records for a `QuestionGrid` with the same `code_id`. This means that you can remove one Response Domain but it appears as if it hasn't removed it because now just shows the duplicate.

We removed the duplicates (where question_id, question_type, and code_id was all the same) and just kept the earliest version (created_at field), as that was the one that being shown in the UI.

I guess the other possible solution is for someone at Closer to trawl through the database and fixing it on a case by case basis.

**Comment by charlesdebarros** [comment]
I have migrated a copy of the Production database backup from 06Aug19 to Staging. Staging has now an exact copy of the Production Archivist database as of this morning.

**Comment by HayleyMills** [comment]
I would suggest that we do not delete the records which have a code_id of nil, as they are still displaying in the UI and so we can assume they are valid if there is only one response for a question. In these cases I would set the code_id to 1. This would be followed by deleting all the duplicates. 

If there are cases were there are more than one response for a question and they all are nil then that may be more complicated and we may have to check these case by case. I'm guessing that there aren't any of these as most likely there will be other duplicate records which do have code_ids. This might be something we need to check.

**Comment by simonreed** [comment]
> I would suggest that we do not delete the records which have a code_id of nil, as they are still displaying in the UI and so we can assume they are valid if there is only one response for a question. In these cases I would set the code_id to 1. This would be followed by deleting all the duplicates.

What should we do the duplicates when they don't have a code_id of nil?

> If there are cases were there are more than one response for a question and they all are nil then that may be more complicated and we may have to check these case by case. I'm guessing that there aren't any of these as most likely there will be other duplicate records which do have code_ids. This might be something we need to check.

Ok, these are solutions for data issue 1 https://github.com/CLOSER-Cohorts/archivist/issues/282#issuecomment-516907610 are happy to carry on with the solution to data issue 2 (duplicates with code_id not set to null)?

**Comment by HayleyMills** [comment]
Yes I think the solution to remove the duplicates (issue 2) is fine, and as far as I could tell that worked okay last time.

**Comment by simonreed** [comment]
@HayleyMills Ok I've updated the database on staging accordingly can you take a look and see if we're now good?

**Comment by HayleyMills** [comment]
Great, it looks good to me. 

I think we may need to also rectify the rd_order in the rds_qs table for the question items, as there are records which are nil, but I think they all should have an order. Would it be possible for you to set those all to 1 as well unless there is more than one linked to a question. We will have to sort those manually, as we will have to check the order. Can we also prevent this happening in future the same as for the grids code_ids?- I can open a new issue for this?

**Comment by simonreed** [comment]
Yes can you create a new issue for the Question Item work.

**Comment by HayleyMills** [comment]
Okay thanks, I'll close this and open another for the question item rds_q DB issues.

**Comment by HayleyMills** [comment]
Tested in staging by JS and all okay.

**Comment by HayleyMills** [comment]
@simonreed Can you please post the SQL needed to update the issues on the database? Only the old incorrect version is posted above.
