### ISSUE TITLE
Changes in the main live Archivist are reflected in the staging Archivist

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#287]
When you make a change to an instrument in the construct view, this is automatically reflected in the instrument with the same ID in the staging server, until this is refreshed. 

I have tested this with each Archivist in a different browser. It appears like the cache could be linked in someway?

**Comment by charlesdebarros** [comment]
It happens to both Chrome and/or Firefox.

**Comment by charlesdebarros** [comment]
Turning off Realtime has sorted the issue for now.
