### ISSUE TITLE
Import partial questionnaires from data tables

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/archivist#288]
Data tables to be defined by Jon

**Comment by spuddybike** [comment]
The attached spreadsheet contains the data which will need to be imported.

Tab: A_Code_lists contains code lists, this shuold be sufficient information to populate the **codes, categories and code_lists** tables and the required relationships

Tab: Response_Domain_Ranges should be sufficient to populate the **rds_qs** table

Tab: questions_Instructions_response should be sufficient to populate the **questions** table (the only issue may be instructions where there are duplicates

Tab: Statements should be straightforward to map to **statements** table

Tab conditions should be inserted into the **conditions** table, without question constructs this may not be able to be linked to question tiems - but this could be explored 

Tab: Sequences - needs further elaboration

Tab: 
[Tables.xlsx](https://github.com/CLOSER-Cohorts/archivist/files/3550999/Tables.xlsx)

**Comment by HayleyMills** [comment]
Is this what Jenny Li has developed?

**Comment by spuddybike** [comment]
Jenny Li completed.
