### ISSUE TITLE
Four Column Export

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/archivist#289]
See Table

![Capture](https://user-images.githubusercontent.com/19798638/61649162-d20c1080-aca8-11e9-8879-2cb4d8a62488.JPG)

**Comment by HayleyMills** [comment]
Related to this, the mapping .txt file importers should also accept these formats.

**Comment by spuddybike** [comment]
@charlesdebarros 

![Capture](https://user-images.githubusercontent.com/19798638/63760562-7809f680-c8b7-11e9-8a4d-ece11b5011a6.PNG)
