### ISSUE TITLE
Update Concept list across all instances

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/archivist#294]
The correct concept list (including criminal behaviour) should be available on all instances. Possibly a job for Nimal? and updated on the wiki

**Comment by HayleyMills** [comment]
Nimal can update on the wiki- but it may need @charlesdebarros to add to DB/Archivist? Unless it's a case of adding a new record to the topics table in SQL (Datagrip)-in which case I can do this this.

**Comment by spuddybike** [comment]
Adding via data grip is fine - though it needs to be done in every instance 
J
======================
Lovingly typed on the iPhone
======================

**Comment by HayleyMills** [comment]
Added topic to all instances as well as staging server. Nimal is updating the wiki.
