### ISSUE TITLE
Response domain min and max not displaying

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#298]
The min and max are saving as they can be seen in the doc view when they are used, but they are not displaying and the refresh does not work. 
(Update to #147 and similar issue to #160.)

**Comment by simonreed** [comment]
@HayleyMills sorry what do you mean by the `doc view`?

**Comment by HayleyMills** [comment]
@simonreed Apologies, I just mean the main review page e.g. https://closer-archivist-staging.herokuapp.com/instruments/alspac_02_qht This page shows the min and max of the response domains (see qc_C1), but the Response Domain build page doesn't display them (e.g. https://closer-archivist-staging.herokuapp.com/instruments/1027/build/response_domains/response_domain_numerics/3411)

**Comment by HayleyMills** [comment]
@spuddybike was this tested and is it working now?

**Comment by spuddybike** [comment]
@HayleyMills sorry mea culpa - reopened

**Comment by HayleyMills** [comment]
Tested on staging, the current integer response domains are still not displaying in the build view. Tested adding a new integer using hm_test_1 (https://closer-archivist-staging.herokuapp.com/instruments/1605/build/response_domains/response_domain_numerics/8553) and it still did not display after saving. I edited it and re-added the min and max and they did display after this second time saving, however this did not persist.

**Comment by simonreed** [comment]
@HayleyMills this hasn't been merged into the `release` branch (https://github.com/CLOSER-Cohorts/archivist/tree/release) so isn't on staging yet.

@spuddybike could you merge the latest changes from `develop` into the `release` branch please.

**Comment by simonreed** [comment]
@HayleyMills can you please retest, this is now on staging.

**Comment by HayleyMills** [comment]
Tested on staging. The min and max for the response domains are now displaying which is great. 

When you add a new response domain, the min and max doesn't display straight away after saving. It needs to be refreshed. #302 

The main problem I've noticed is that values which were previously null (i.e. had no max) are now 0? e.g. all 'How many's.

**Comment by simonreed** [comment]
The issue is that `min` and `max` are always stored as numerics, so even if you leave it blank it will be recorded in the db as `0.0`. Therefore there is no way for the db to know if the user has left the field blank or if they've entered `0.0`.

Previously were were showing the field has blank in the UI because it was using a string of `0.0` which was also causing all the min/max to not show.

Now however there is no way for us to know if it should be null or `0.0` as we're not storing a null in the db.

**Comment by HayleyMills** [comment]
Thanks @simonreed, can you clarify what is preventing the DB having NULL values for the numerics? Is it the DB setup/model? We do need to be able to distinguish between 0.0 and NULL. If we need to update the database data, then all cases of the numeric max being 0 should be set to NULL.

**Comment by simonreed** [comment]
@HayleyMills let me investigate further and i'll get back to you.

**Comment by simonreed** [comment]
@HayleyMills ok i've made a change to fix this on the pull request above.

**Comment by simonreed** [comment]
I'll let you know when it's on staging.

**Comment by HayleyMills** [comment]
Tested on staging and this looks good. The min and max are displaying for those entered already, and is showing the Max as empty where it should be. It no longer needs refreshing to see the saved min and max for new response domains.

**Comment by HayleyMills** [comment]
Tested in staging by JS and all okay.
