### ISSUE TITLE
rd_order in rds_qs is nil for some QuestionItem records

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#306]
I think we may need to also rectify the rd_order in the rds_qs table for the question items, as there are records which are nil, but I think they all should have an order. 

Would it be possible for you to set those all to 1 as well unless there is more than one linked to a question. We will have to sort those manually, as we will have to check the order. Can we also prevent this happening in future the same as for the grids code_ids?

**Comment by simonreed** [comment]
This has been run in on the staging database, it sets to `rd_order` for RdsQs records using the same order that the UI at the moment. This means the UI should remain the same but we no longer have any `RdsQs` QuestionItem records with `NULL` for `rd_order`.

This will need to run in on the production servers as we don't have any data migrations in the codebase.

```
QuestionItem.joins(:rds_qs).where('rd_order IS NULL').each do | question_item |
  question_item.rds_qs.order(:rd_order).each_with_index do | rds_qs, i |
    rds_qs.update_column(:rd_order, i + 1)
  end
end
```

**Comment by simonreed** [comment]
@HayleyMills can you test that this looks ok on staging please.

**Comment by HayleyMills** [comment]
Checked the staging DB and there are no longer nil rd_order for QuestionItems. 
@simonreed Where there any scenarios were the rd_order was nil, but there was more than one rd_qs linked to a question?- and so it was not possible to simply assign 1 to them both? 

Adding and removing response domains to QuestionItems is working okay. The rd_order is saving in the staging DB when a new one is created. Although I can't really test this that well, as I can't replicate this in the live (is it saving the rd_order).

**Comment by simonreed** [comment]
> Checked the staging DB and there are no longer nil rd_order for QuestionItems.
> @simonreed Where there any scenarios were the rd_order was nil, but there was more than one rd_qs linked to a question?- and so it was not possible to simply assign 1 to them both?

@HayleyMills Yes there were instances on staging where a QuestionItem had more than 1 rds_qs, in those cases we're saving `rd_order` in the same order as they currrently appear to the user in the UI if they were all nil. That way with the new `rd_order` it appears the same to the users as before but the database is more consistent.

**Comment by HayleyMills** [comment]
Perfect.
