### ISSUE TITLE
Add import status and error logging to import XML

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/archivist#311]
Add import status and error logging to import XML

**Comment by HayleyMills** [comment]
Tested on staging using rat_2 which failed as it was already loaded, a error message was provided. For rat_3 this was uploaded successfully. I also uploaded wchads_15_ph13schx which did not load correctly and so again and error message was provided. 

e.g. Invalid :  PG::UniqueViolation: ERROR:  duplicate key value violates unique  constraint "index_control_constructs_on_label_and_instrument_id" DETAIL:  Key (label, instrument_id)=(qc_s1_1, 1818) already exists. CONTEXT:  SQL statement "UPDATE control_constructs  SET label = new.label,            parent_id   = (SELECT id FROM control_constructs WHERE  construct_type = new.parent_type AND construct_id = new.parent_id), position = new.position,  branch  = new.branch,  updated_at = new.updated_at   WHERE construct_id = new.id AND construct_type = 'CcQuestion'" PL/pgSQL function update_cc_question() line 10 at SQL statement : UPDATE "cc_questions" SET "updated_at" = $1, "label" = $2, "parent_id"  = $3, "parent_type" = $4, "branch" = $5 WHERE "cc_questions"."id" = $6
