### ISSUE TITLE
Export DDI Fragments

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/archivist#316]
At the moment we only export Instances, which is fine for importing into Discovery..

But we will want to export specific question items, code lists and other response domains.

Ideally you should be a select a single or set of items and export them

**Comment by spuddybike** [comment]
Examples of outputs are attached:
[Question with Text Domain.txt](https://github.com/CLOSER-Cohorts/archivist/files/3951865/Question.with.Text.Domain.txt)
[Question with structured Mixed Response Domain code + datetype.txt](https://github.com/CLOSER-Cohorts/archivist/files/3951866/Question.with.structured.Mixed.Response.Domain.code.%2B.datetype.txt)
[Question with structured Mixed Response Domain code + numeric.txt](https://github.com/CLOSER-Cohorts/archivist/files/3951867/Question.with.structured.Mixed.Response.Domain.code.%2B.numeric.txt)
[Question with structured Mixed Response Domain code + text.txt](https://github.com/CLOSER-Cohorts/archivist/files/3951868/Question.with.structured.Mixed.Response.Domain.code.%2B.text.txt)
[Question with Numeric Domain.txt](https://github.com/CLOSER-Cohorts/archivist/files/3951869/Question.with.Numeric.Domain.txt)
[Question with Date Domain.txt](https://github.com/CLOSER-Cohorts/archivist/files/3951870/Question.with.Date.Domain.txt)
[Question with code list.txt](https://github.com/CLOSER-Cohorts/archivist/files/3951871/Question.with.code.list.txt)








Basic structure is
FragmentInstance
TopLevelReference - points to first object which will be the QuestionItem
QuestionItem contains contents as per the old style XML

URN should appear, but also it should also be decomposed into Agency/ID/version fields
this is to support both, its verbose, but when we read in we should be able to read either URN or decomposed version

Other than that is it very similar to the existing export format.

Once issue is how to mark/flag etc the question items for export - the solution should be the simplest to implement!

**Comment by spuddybike** [comment]
QuestionItem should also point to a ConceptReference
The content for this can be obtained from the Topic Name and Label
An additional column should be added to this table to add ConceptURN which will need to be populated
See following Fragment for the format
[Question with Text Domain.txt](https://github.com/CLOSER-Cohorts/archivist/files/3967301/Question.with.Text.Domain.txt)

**Comment by simonreed** [comment]
@spuddybike There are some attributes that are in these fragments which aren't currently part of the full xml export. Are they a requirement and if so do you have any idea where the database to expose this information:

- `isUniversallyUnique="true" ` I'm assuming this is going to be set as a default of true for any object with an id.
- `CodeDomain` - `blankIsMissingValue="false"`
- `Version` just to clarify that this is the version that is used in the URN so will be the version of the Instrument and not a version for a specific object e.g. CodeList.
- `Code//UserID` unsure which user_id this would be?

**Comment by spuddybike** [comment]
isUniversallyUnique="true
Should be the default
Version - best to set that to Instrument version as you suggest
UserID - should have been removed - my mistake. 
CodeDomain. If we haven’t got a blank field should be set to false. 

Jon

**Comment by spuddybike** [comment]
@simonreed Apologies, the TopLevelReference block is superfluous, especially where you are exporting more than one QuestionItem, it doesnt make any sense

**Comment by simonreed** [comment]
@spuddybike with the `ConceptReference` you say we want to look at the topic but a topic is only associated to a `CCQuestion` object rather than a `QuestionItem`? Is that correct? If so how can we get the Topic from a QuestionItem?

**Comment by HayleyMills** [comment]
Has this been completed @spuddybike?

**Comment by spuddybike** [comment]
At the moment it exports a single question - ideally add a select question item and export in bulk But that should be anew issue
