### ISSUE TITLE
Construct summary pages

### ISSUE THREAD

**Issue by spiegeljen** [CLOSER-Cohorts/archivist#32]
In Caddies there are summary pages for various constructs - qcs, statements, condtions, etc. Hiving constructs listed by type and the information displayed in Caddies for each construct type is very useful particualrly when dong verification - for checking ID construction on all constructs, on qc summary checking qi/qg and qc ids mirror,  for statements and conditions checking text and for conditions, logic. In Archivist at moment it looks like these are no longer part of how things are displayed which would be a great loss of functionality.

**Comment by wpoynter** [comment]
Add list views for constructs by construct type
