### ISSUE TITLE
Not loading all variables from XML file (sledghammer and DDI flavour output)

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#320]
I loaded sws_5_clinic files (see attached, extension changed to upload) into main Archivist and it seemed to load okay, however, there are  about 500 variables which did not load. Does anyone have any ideas on whether this is a problem with the xml or Archivist? 

It has loaded the variables up until nnipsm, but not ntomst onwards. 

[sws_5_clinic.ddi32.rp.txt](https://github.com/CLOSER-Cohorts/archivist/files/3555922/sws_5_clinic.ddi32.rp.txt)

**Comment by HayleyMills** [comment]
Investigated with JJ and problem caused by the XML rather than Archivist. I will email Vanessa to try and determine what the possible causes are.

**Comment by spuddybike** [comment]
strings / spss file issues
