### ISSUE TITLE
Question grid X and Y drop-down list showing all code lists

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#326]
The drop down list when sleeting the code list for X or Y axis in a grid is showing all response domains. It would be good if it only showed the code lists which are not response domains (unticked in the code list view). It would also be nice if the list was in a alphabetical order.

**Comment by spuddybike** [comment]
Could we close and open a new issue in enhancements?

======================
Lovingly typed on the iPhone
======================

**Comment by HayleyMills** [comment]
Tested on staging, and the drop down list on both the vertical and the horzontal only show those unticked as a response domain.

**Comment by HayleyMills** [comment]
Tested on live and this is not working. Re-tested on staging and it is also no longer working there either. The drop-down list shows all code lists, not just none response domain code lists. Does this relate to #448 ?

**Comment by HayleyMills** [comment]
Is this now ready to test on staging?
