### ISSUE TITLE
REACT: Re-order response domains attached to question item

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#327]
It would be useful if we could re-order the response domains attached to a question item, when there are more than one (similar to re-ordering code list order). Currently we have to remove them and re-add to make sure they are in the correct order.

**Comment by HayleyMills** [comment]
There seems to be a problem which JS noted about the response domains being saved in the correct order. I have not been able to replicate this, but it will make it difficult to then delete and add and save in a way which gets them to save in the correct order.

**Comment by simonreed** [comment]
<img width="1091" alt="Screenshot 2022-04-29 at 22 07 43" src="https://user-images.githubusercontent.com/13276/166069272-3c7f5cae-2f4f-4b1f-aa97-51434dc3908a.png">

@HayleyMills this is now on staging

**Comment by HayleyMills** [comment]
Tested on Staging and it is now possible to reorder response domains. If you add a new reponse domain and reorder it, it does not save, so need to 'submit' the new addition and then re-order and 'submit' again.
