### ISSUE TITLE
Not possible to delete instruments in staging instance

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#332]
We can delete instruments in the live, but it doesn't look like we can do this in the staging now?

**Comment by simonreed** [comment]
This is now on staging @HayleyMills the deletion of an instrument is queued so it might take a little while to complete the deletion.

**Comment by HayleyMills** [comment]
Tested on staging using ncds_65_mq- deleted this instrument (which had mappings and link to a dataset) with no problems.
