### ISSUE TITLE
SQL Code to deploy when pushing to master 24/9/2019

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/archivist#349]
#306 and #282 
source, need to combine into a single canonical SQL update

**Comment by spuddybike** [comment]
# 306 is 

QuestionItem.joins(:rds_qs).where('rd_order IS NULL').each do | question_item |
  question_item.rds_qs.order(:rd_order).each_with_index do | rds_qs, i |
    rds_qs.update_column(:rd_order, i + 1)
  end
end

**Comment by spuddybike** [comment]
#282 needs updating @simonreed could this be pasted in here so we have one place the code is held

**Comment by simonreed** [comment]
for #282 

```
UPDATE "rds_qs" SET "code_id" = 1 WHERE "rds_qs"."question_type" = 'QuestionGrid' AND "rds_qs"."code_id" IS NULL

DELETE FROM 
    rds_qs
USING (SELECT 
      "rds_qs"."question_id", 
      "rds_qs"."question_type",
      "rds_qs"."code_id",
      min("rds_qs"."created_at") as firstTimestamp
    FROM "rds_qs"
    WHERE (code_id IS NOT NULL AND question_type = 'QuestionGrid') 
    GROUP BY "rds_qs"."question_id", "rds_qs"."question_type", "rds_qs"."code_id"
    HAVING (count(*) > 1)) dupes
WHERE
    rds_qs.question_id = dupes.question_id
    AND rds_qs.question_type = dupes.question_type
    AND rds_qs.code_id = dupes.code_id
    AND rds_qs.created_at > dupes.firstTimestamp;
```

Note that https://github.com/CLOSER-Cohorts/archivist/issues/349#issuecomment-534590226 is to be entered into the Rails console on production as it is Ruby logic rather than SQL.
