### ISSUE TITLE
Refreshing after editing constructs is causing large instruments is slow to load

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#363]
JS tested on USoc instance. When you update a condition and save it, then the qc labels inside the condition disappear on the screen. A refresh appears to bring them back. However this refresh is taking a long time for large instruments (even when dynos turned up).

**Comment by simonreed** [comment]
Just to clarify can you confirm what page this is on with an example URL, preferably on staging?

**Comment by HayleyMills** [comment]
https://closer-archivist-staging.herokuapp.com/instruments/bcs9/build/constructs

**Comment by HayleyMills** [comment]
Tested using https://closer-archivist-staging.herokuapp.com/instruments/bcs9/build/constructs. Changed 
c_ifcurrentresidence to c_ifcurrentresidence_test and it is now much quicker to refresh. Is it possible to retain the display of the constructs inside of the condition, so we don't have to refresh?

**Comment by HayleyMills** [comment]
This issue has been resolved, there is another issue mentioned in the above comment which I have made a new issue for #418
