### ISSUE TITLE
Order of response domain attached to a qi is reversing

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#376]
When you add more than one response domain to a qi once you save it, it reverses the order e.g. https://closer-archivist-staging.herokuapp.com/instruments/1772/build/questions/question_items/157405.

**Comment by HayleyMills** [comment]
Also maybe related, but when you save a question with one or more response domains attached, when you edit it and add another response domain it will not save if it means there are more than two attached. You get around this by removing all response domains and then saving without any, then adding them all again at once.

**Comment by HayleyMills** [comment]
This is worse then first appeared. In all cases where there is more than one response domain attached to a question they have reversed- this is for those that already exist and have not been edit. See https://closer-archivist-staging.herokuapp.com/instruments/nshd_89_scq  qc_sectionB_i as an example.

**Comment by HayleyMills** [comment]
Although the database is correct, the export is not exporting this order, but is exporting the displayed order, this is of high priority.

**Comment by spuddybike** [comment]
moved to staging

**Comment by HayleyMills** [comment]
Tested on staging and its working okay now.
