### ISSUE TITLE
REACT: Allow the deletion of a mapped q-v from the user interface

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#380]
Would it be possible to delete a question linked to a variable from the dataset view or a variable from a question on the map view? I realise this may be difficult to do, but are there any options, which avoid having to export, edit and re-upload the txt files which is time consuming for changing only one or two mappings?

Currently in the map view you can delete a variable, but only until it is refreshed. In the dataset view is is not possible at all.

**Comment by HayleyMills** [comment]
Using this as an example https://closer-archivist-staging.herokuapp.com/datasets/103 I would want to delete the mapping between atricep1 and qc_1. This works in this case (this seems to be an exception to the rule?), I can either delete the question from the dataset page or the variable mapping page https://closer-archivist-staging.herokuapp.com/instruments/hcs_1_home_1/map and it removes the link from both pages. 

However, in the example https://closer-archivist-staging.herokuapp.com/datasets/551 I can't seem to delete the mapping  e.g. qc_A1_a from pl1000 or in the map view https://closer-archivist-staging.herokuapp.com/instruments/alspac_99_fatf/map pl1000 from qc_A1_a  

I have also tried https://closer-archivist-staging.herokuapp.com/datasets/269 and https://closer-archivist-staging.herokuapp.com/instruments/bcs_86_mo/map which doesn't work either.

**Comment by simonreed** [comment]
The problem appears to be when the `x` and `y` of the mappings are set to `0` instead of `nil`.

https://closer-archivist-staging.herokuapp.com/datasets/103 had the mapping as `nil` so when the UI tried to delete that mapping it found it.

However https://closer-archivist-staging.herokuapp.com/datasets/551 and https://closer-archivist-staging.herokuapp.com/datasets/269 both have their mappings set to `x=0` and `y=0` so when the UI is attempting to delete any mappings for those variables only when `x=nil` and `y=nil` then it doesn't delete the mappings and no changes are made.

- [ ] Find out why some mappings are `x=0, y=0` and others are `x=nil, y=nil`
- [ ] Investigate whether in the cases above whether the UI should be passing nil or 0 for x and y.

**Comment by HayleyMills** [comment]
Tested using https://closer-archivist-staging.herokuapp.com/datasets/551 and https://closer-archivist-staging.herokuapp.com/instruments/alspac_99_fatf/map. It now allows the deletion from both views.

**Comment by HayleyMills** [comment]
Tried this again recently in the live Archivist and I am having trouble deleting mappings between variables and questions (not sure if this is because it is a grid?). I have replicated the same problem on the staging. See https://closer-archivist-staging.herokuapp.com/instruments/alspac_08_DCSF/map and https://closer-archivist-staging.herokuapp.com/datasets/665. I have been trying to remove all the mappings for qc_2 but this is not working. I also cannot remove the topic linked to the question.

**Comment by HayleyMills** [comment]
This is because it is a grid and so this is not yet handled in the interface, there is a work-around by re-doing the mappings using the txt files so this is a lower priority.

**Comment by simonreed** [comment]
@HayleyMills this is now on staging you can remove mappings from the dataset view when mapped to a question grid.

**Comment by HayleyMills** [comment]
Tested on staging using https://closer-archivist-staging.herokuapp.com/instruments/alspac_08_DCSF/map and https://closer-archivist-staging.herokuapp.com/datasets/665 and it will now allow the deletion of a variable in a grid on the map view and the dataset view. 

I'm not sure the removing topics is working though?- e.g. how do I remove the topic Finances mapped to qc_1? https://closer-archivist-staging.herokuapp.com/instruments/alspac_08_DCSF/map or Finances mapped to CCXD450 in the dataset vew https://closer-archivist-staging.herokuapp.com/datasets/665 
The x (clear) is not working and I cannot assign it to blank (it is no longer there).

**Comment by simonreed** [comment]
> Tested on staging using https://closer-archivist-staging.herokuapp.com/instruments/alspac_08_DCSF/map and https://closer-archivist-staging.herokuapp.com/datasets/665 and it will now allow the deletion of a variable in a grid on the map view and the dataset view.
> 
> I'm not sure the removing topics is working though?- e.g. how do I remove the topic Finances mapped to qc_1? https://closer-archivist-staging.herokuapp.com/instruments/alspac_08_DCSF/map or Finances mapped to CCXD450 in the dataset vew https://closer-archivist-staging.herokuapp.com/datasets/665 The x (clear) is not working and I cannot assign it to blank (it is no longer there).

@HayleyMills this is now working on staging

**Comment by HayleyMills** [comment]
Tested on staging as above, and this is now working, you can delete the topic using the x- this is much better.
