### ISSUE TITLE
It is not possible to delete a code list

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#409]
It appears that it is no longer possible to delete a code list, whether it is being used by a question or not. I have tested on Staging using https://closer-archivist-staging.herokuapp.com/instruments/1809/build/code_lists/67749 and tried to delete both cs_Yes_No and cs_dash without success.

**Comment by simonreed** [comment]
Just a quick note that this appears to be only happening on CodeLists with foreign key constraints.

**Comment by HayleyMills** [comment]
Tested on staging using https://closer-archivist-staging.herokuapp.com/instruments/1809/build/code_lists/67751 cs_Yes_No has deleted. However it is not possible to delete cs_dash or cs_qA5_Y. 

I wondered whether this has anything to do with these being attached to grids, which is why they won't delete- which makes sense. However, I also tried deleting cs_Yes from https://closer-archivist-staging.herokuapp.com/instruments/1826/build/code_lists/68219 which is not attached to any question, and this will not delete?

**Comment by HayleyMills** [comment]
Tested on staging using hm_test_2_import and it deleted code lists attached the questions, used as grid axis and not used a t all without any problems.
