### ISSUE TITLE
Retain the display of constructs inside an edited construct

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#418]
When a construct (sequence, loop, condition) is edited all constructs within it disapear, this means that you have to refresh the whole page in order for them to appear back. This is okay in small instruments, but for larger instruments, refreshing can be slow and then it is also hard to re-find where you where up to.

**Comment by simonreed** [comment]
![418](https://user-images.githubusercontent.com/13276/84802520-a1d40b80-aff8-11ea-8f5e-549002a71874.gif)

**Comment by HayleyMills** [comment]
Tested on staging on several instruments and this has now been fixed. The constructs inside an edited parent remain in the view.

**Comment by HayleyMills** [comment]
Tested on live and it is not working. 

Tested again on staging, This is no longer working as previously was when tested on staging and in Simon's video above.

**Comment by HayleyMills** [comment]
@spuddybike this is now working on staging, but not on live.

**Comment by HayleyMills** [comment]
Tested on live HEAF and this is now working! :+1:

**Comment by HayleyMills** [comment]
@simonreed @spuddybike I think this might be causing problems. When you make any moves in the construct view, they are not saved when you refresh the page.

**Comment by spuddybike** [comment]
now ready for testing on Staging

**Comment by HayleyMills** [comment]
Tested on staging, and this looks to be working okay.

**Comment by HayleyMills** [comment]
This is working on the react version. This can be closed.
