### ISSUE TITLE
Add a button to the construct view page to expand all collapsed items

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#431]
Suggested by NWV. Add a button to the construct view page to expand all collapsed sequences, conditions and loops. This will allow the option to search for labels which need updating, without having to open each item or finding the location in the doc view first and then navigating to the item.

**Comment by simonreed** [comment]
I'm going to pause this for now. Traversing the tree and expanding the items is too cumbersome, we'll revisit this when looking at the larger work with Angular.

**Comment by HayleyMills** [comment]
Resolved as #497 resolved.
