### ISSUE TITLE
List out all instruments which have problems with responses attached to grids

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#442]
Following the solving of issue #312 @simonreed indicated several issues with the way responses attached to grids were been exported (https://github.com/CLOSER-Cohorts/archivist/pull/433). 

We are having ongoing issues with the way grids are displaying in Discovery e.g. https://discovery.closer.ac.uk/item/uk.cls.bcs70/025577f0-1f6b-4cec-9bbe-e6aa6f7c352e which is likely to be caused by this. 

In order to test this we need to export the instruments again and reload them into Discovery, but we need to know which ones have issues. @simonreed would you be able to list out which instruments have these issues please?

**Comment by simonreed** [comment]
It will be any instruments that have QuestionGrids with horizontal code lists set, I don't have access to the production heroku database.

**Comment by HayleyMills** [comment]
Does it only affect the grids which have code list response domains attached?- Or is it all grids which have more than one column on the horizontal?  

Is there a query which can be used that I can run on the live Archivist?

**Comment by simonreed** [comment]
hi @HayleyMills here's the SQL to find any question grid that contains either a horizontal or vertical code list with more than 1 code list:

```
SELECT question_grids.id
FROM question_grids
INNER JOIN code_lists as horizontal_code_lists ON horizontal_code_lists.id = question_grids.horizontal_code_list_id
INNER JOIN code_lists as vertical_code_lists ON vertical_code_lists.id = question_grids.horizontal_code_list_id
WHERE horizontal_code_lists.id IN (SELECT code_lists.id AS code_lists_id FROM "code_lists" INNER JOIN "codes" ON "codes"."code_list_id" = "code_lists"."id" GROUP BY code_lists.id HAVING (count(code_list_id) > 1))
OR vertical_code_lists.id IN (SELECT code_lists.id AS code_lists_id FROM "code_lists" INNER JOIN "codes" ON "codes"."code_list_id" = "code_lists"."id" GROUP BY code_lists.id HAVING (count(code_list_id) > 1));
```

**Comment by HayleyMills** [comment]
Works well thanks.
