### ISSUE TITLE
Code lists not in doc view on staging server

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#461]
There are differences between the staging and the live versions of Archivist e.g. datasets not loading #216, #312 

All questions which have code lists attached seem to have lost this connection, although from the code list view they look like they are linked. I first noticed this on 15/16th October.

**Comment by HayleyMills** [comment]
Example https://closer-archivist-staging.herokuapp.com/instruments/1013/build/code_lists/35237 shows many questions linked to this code list, however if you look at one of the questions https://closer-archivist-staging.herokuapp.com/instruments/1013/build/questions/question_items/87427 it doesn't have the code list attached.

**Comment by spuddybike** [comment]
@HayleyMills ready for testing on staging

**Comment by HayleyMills** [comment]
Tested on staging and example above is working now.
