### ISSUE TITLE
Exporter no longer working

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#479]
The exporter for all instances appears to have stopped working. The last time I used it was in November 2020 when it worked fine.

**Comment by spuddybike** [comment]
@HayleyMills I have deployed the fix to staging - if you want to test and then I'll update master and put live etc etc

**Comment by HayleyMills** [comment]
Tested on staging and it appears to be working now. I exported instruments not already exported as well as already exported, and both created new export dates and the latest download provided XML with the latest timestamp of the export.
