### ISSUE TITLE
REACT: List of instrument features to be added

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#485]
- [x] Search for instrument - essential
- [ ] Sort by 
- [ ] Filter by study

**Comment by simonreed** [comment]
> * Search for instrument - essential

@HayleyMills this is now on closer-react this searches on the instrument prefix and it works on both '/instruments' and '/admin/instruments'

**Comment by HayleyMills** [comment]
Tested search and it is working.

**Comment by HayleyMills** [comment]
This has now been added and works.
