### ISSUE TITLE
REACT: Drop down list for Code list (X)/(Y) shouldn't include Response Domains

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#488]
Only Code lists which do not have Response Domain ticked should appear in the drop-down for the Horizontal/Vertical Code list selection.

**Comment by simonreed** [comment]
@HayleyMills deployed to https://closer-react.herokuapp.com/

**Comment by HayleyMills** [comment]
@simonreed I think this has been change to the wrong way around. Code lists which are ticked response domain shouldn't show in the X/Y drop list for a grid. 

e.g. for https://closer-react.herokuapp.com/instruments/hm_test_99/build/code_lists/72753 only cs_1 and cs_dash should be availble in the list. 

![image](https://user-images.githubusercontent.com/16664703/106130712-9bdf0500-6159-11eb-9c17-bc1f276d7df0.png)

**Comment by HayleyMills** [comment]
This is now working.
