### ISSUE TITLE
REACT: When viewing a question grid the + question grid does not work

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#489]
If you are viewing an already created question grid and want to create a new one, the + question grid doesn't create a blank form to complete. The + question item does though. 

There is also an extra link next to the + Question item/grid buttons.

**Comment by simonreed** [comment]
@HayleyMills on which page is this?

**Comment by HayleyMills** [comment]
The Build/Questions page e.g. https://closer-react.herokuapp.com/instruments/hm_test_99/build/question_items/

**Comment by HayleyMills** [comment]
I just realised what the extra link does- it's so you can view either all the question grids or all the question items.

**Comment by HayleyMills** [comment]
Tested on REACT Archivist and this is now working.
