### ISSUE TITLE
REACT: Build pages should scroll the items and keep the form at the top

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#492]
For example when you click on question item/question grid you should be able to see the form for this entry without having to scroll up to the top.  This applies to all build pages inlcuding the constructs, which confusingly has three scroll bars. 

Ideally you would want to click through each item and view the entry for each one, so if the list could stay in the same position once selected it, so you also don't have to scroll back down to it that would be great, but not essential. Currently code lists does this in the original Archivist, but the questions and response domains do not.

**Comment by simonreed** [comment]
This should be resolved on heroku-react.

**Comment by HayleyMills** [comment]
Tested on REACT archivist and this works great.
