### ISSUE TITLE
REACT: Can the constructs view have all the constructs automatically collapsed

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#497]
It is currently difficult to navigate the tree as all the constructs are expanded and there are also no formatting distinguishes between the items. Can we add an option to have all the constructs expanded or collapsed? #431

**Comment by simonreed** [comment]
There are now buttons to collapse and expand all of them deployed to heroku-react

**Comment by HayleyMills** [comment]
Great, this works well.
