### ISSUE TITLE
REACT: Error message remains even though error was resolved

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#501]
I edited a contructs with an incorrect label so it didn't save and it gave an error message which is good. But when I correct this and redubmitted (it saved), the error message is still there.

![image](https://user-images.githubusercontent.com/16664703/106129122-e3649180-6157-11eb-9b7a-9caebed8f559.png)

**Comment by HayleyMills** [comment]
The error appears when the construct is unable to save, and when the issue has been resolved it dissapears.

**Comment by HayleyMills** [comment]
This is happening again, if I save a construct without selecting item/grid for example, it gives an error which is good, but when I add and the question type, it still has the error and won't save, when I close the question and click for a new construct, there blank question construct appears but it still has the error. If I delete the "Click to select construct type" and start again, the error is still there. I need to refresh the whole page and start again.

**Comment by HayleyMills** [comment]
@beckyoldroyd can you check this is still happening please? Thanks,

**Comment by beckyoldroyd** [comment]
I tried to test on staging and main but I found that I'm not getting error messages when I should e.g. I added a qc without selecting the Type and it let me save it. 

![image](https://github.com/user-attachments/assets/2b6edb9a-63eb-4418-b77a-1c419ba98d98)

@HayleyMills is this happening for you too?

**Comment by HayleyMills** [comment]
@beckyoldroyd yes, but I think that's fine, it shouldn't be mandatory to select the type- I think it's just a helpful filter, although the * should be removed - can you add a low priority issue for that please?

What about this issue- do you think this is okay, so I can close it?

**Comment by beckyoldroyd** [comment]
Tested on staging and the errors are resolving/no error message is appearing when I make changes so it is working as it should. I've created a separate issue about the * @HayleyMills @simonreed
