### ISSUE TITLE
REACT: The construct page doesn't load the first time. 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#502]
When you click the build/construct link it takes you to the page which it tried to load, but then it goes to a blank page. If you refresh the page it loads okay.

**Comment by simonreed** [comment]
@HayleyMills could you give me an example on heroku-react app?

**Comment by HayleyMills** [comment]
It was happening when I clicked on the construct page for every instrument, but now it seems to be intermittent, with it working most of the time. https://closer-react.herokuapp.com/instruments/onsls_11_inde/build/constructs/ this one has been loading a blank page for me, until I refresh. (It's not a high priority, as the refresh does reload the page okay.)
