### ISSUE TITLE
REACT: Cannot search on the construct page

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#503]
This is most likley due to all the windows but when you try and search for a construct name, it cannot find it unless it is already visible in the window. It is really important that we can find a specific construct so it can be edited. If the find on this page cannot work, then we will need to add a search function to the page.

**Comment by simonreed** [comment]
This has been deployed to heroku-react

**Comment by HayleyMills** [comment]
There is now a search box on the construct page, which finds constructs anywhere in the tree, it provides a count and you can scroll through them with it highlight each one which is good. However, it doesn't navigate to the construct position- can this be added?

**Comment by simonreed** [comment]
"construct position" do you mean the level in the tree where the construct (which it should do) or that you want it to open the form?

**Comment by HayleyMills** [comment]
So at the moment it opens the tree where it finds them which is great, but we need to scroll down and look for where they are to see them. 
Ideally we just need to see the construct which is highlighted like it would if we were using the find on page (if all expanded).  
Either way is fine- with the form open, or just so we can see it to then click on it.

**Comment by simonreed** [comment]
This has been deployed to heroku react.

**Comment by HayleyMills** [comment]
Tested and this is working. However, if you move around on the screen and re-search for the same item, it doens't go back to it?

**Comment by HayleyMills** [comment]
Also when I have tried this recently it is not going to the location of the item searched for e.g. searching for c_qEduc_ii on https://closer-react.herokuapp.com/instruments/LSYPE_Wave_5_3/build/constructs/

**Comment by HayleyMills** [comment]
This has now been removed and the browser search is working.

**Comment by simonreed** [comment]
This is now on staging

**Comment by HayleyMills** [comment]
This is working much better, there is white space at the end, but it is more important that it finds the items.
