### ISSUE TITLE
REACT: Creating a Numeric response domain should give the choice between integer and float

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#505]

**Comment by simonreed** [comment]
This has been deployed to heroku-react

**Comment by HayleyMills** [comment]
There is now the option to select float or integer, but the numeric response domain should not be able to save without a type being selected.

**Comment by HayleyMills** [comment]
Tested on REACT archivist and this is now working- it will not save unless the numeric type is selected.
