### ISSUE TITLE
REACT: Option to go to the build and document views from Response Domain/Questions/Code lists views

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#510]

**Comment by simonreed** [comment]
@HayleyMills How do we mean by the build and document views from this can you give me an example of a page and where you want it to link to?

**Comment by HayleyMills** [comment]
So using the example alspac_16year_cc on the staging Archivist
- Build view https://closer-archivist-staging.herokuapp.com/instruments/alspac_16year_cc/build
- Doc view https://closer-archivist-staging.herokuapp.com/instruments/alspac_16year_cc. This view doesn't yet exist in the REACT version, but is a critical view. 

Currently, if you are on the build view you can click on the instrument prefix name alspac_16year_cc and it will take you to the doc view. If you are on the doc view there are links (drop-down of prefix) back to the Build, Edit and Map view

**Comment by simonreed** [comment]
Ah ok so we're talking about having this part of the navigation on most pages?

<img width="538" alt="Screenshot 2021-02-05 at 15 14 21" src="https://user-images.githubusercontent.com/13276/107051842-d59cb500-67c4-11eb-9726-8ba4bc99b09b.png">

**Comment by HayleyMills** [comment]
Yes ideally we need to have a navigation bar to move through those different pages please.

**Comment by simonreed** [comment]
This has been deployed to heroku-react

**Comment by HayleyMills** [comment]
I can now see the breadcrumbs on the build and map pages, however, I'm not sure I can fully test since the doc view page does not exist yet. We need to be able to move to and from the build and doc view ideally. I'll move this to lower prioirty as we can work around this.

**Comment by HayleyMills** [comment]
There are now links to the build/view/map pages on all pages.
