### ISSUE TITLE
REACT: construct does not save after trying to save with an duplicate label

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#512]
If I try and save a construct with the same label as another construct (same type) it does not save and an error appears, which is good, but if I change the label and re-submit to save it still won't save. This applies to all constructs and for new and existing. 

![image](https://user-images.githubusercontent.com/16664703/106594791-82b7c900-654a-11eb-9881-19b689e2980c.png)

**Comment by HayleyMills** [comment]
JS suggested that the error also indicated that the problem is due to the label not being unique. "I tried to input a new condition and submitting it just brought Error and it wouldn’t input. Have no idea what the error was. Condition construction looked ok to me."

**Comment by simonreed** [comment]
This is on staging

**Comment by HayleyMills** [comment]
Tested this, and it will allow the adding of a question after it has receieved an error without having to refresh, which is great. 

There is an improvement which would be made though. After you receive the error the ideal would be that you click reset and try again with the correct label, but this doesn't work. If we can't get that to work, this is not a huge problem, as it still has the error and we can close the pop-up and reselect the construct type. When we do this however it still shows the error message which is confusing as if you enter correct info it saves fine. Can we either get the reset to work, or have the error not show. Let me know if this doesn't make sense. 

![image](https://user-images.githubusercontent.com/16664703/140307961-b76b6778-5ffd-4fed-990b-2139c11322ac.png)

**Comment by simonreed** [comment]
@HayleyMills this is now on staging

**Comment by HayleyMills** [comment]
This is working really well now.
