### ISSUE TITLE
REACT: Build/code list page format is too busy

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#518]
JS suggestion. Would be better if the code list page was a split screen as it is in current Archivist. The screen feels too busy with so many things going on at once. Putting code list list in split screen and making it smaller would make more room for seeing the entry form and give more space for the label texts. #516

**Comment by simonreed** [comment]
> This looks much better. Just a couple of remaining issues:
> 
> 1. There might end up being an overlap of the code list labels in the list and the form (see image)
> 2. Can we make the code value entry box smaller (this is usually only a couple of characters long). #516
> 

These are now on closer-react
