### ISSUE TITLE
REACT: Build/questions page format is too busy

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#519]
The same issues as #518 but with Question items/grids with question items list on the same screen as the input screen. Would prefer it to be split and area showing qi labels smaller so more text can be seen on input screen.

**Comment by HayleyMills** [comment]
Yes this looks much better. If it's easy to do can we make the drop down list wider reducing the Actions part please?

**Comment by simonreed** [comment]
@HayleyMills It should look like that on closer-react

<img width="1508" alt="Screenshot 2021-05-27 at 17 01 56" src="https://user-images.githubusercontent.com/13276/119859384-3fc09d80-bf0d-11eb-8318-07f68ae2306a.png">
<img width="1486" alt="Screenshot 2021-05-27 at 17 02 10" src="https://user-images.githubusercontent.com/13276/119859419-4818d880-bf0d-11eb-9457-c3f869cf3073.png">
