### ISSUE TITLE
REACT: It is not possible to drag a construct to a position off screen

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#522]
When you try to move a constructs to a place which you can't see on the screen (which is very common), the screen position doesn't move when you drag off screen. It doesn't move when you use the mouse scroll, or when you use the mouse arrows. Original Archivist can do all three, I think the most used is the dragging with the screen automatically moving. 

This looks like it is only a problem when moving up, not down.

**Comment by simonreed** [comment]
This is on heroku-react

**Comment by HayleyMills** [comment]
Tested the new method for moving constructs. It appears to be working when moving constructs into seqeunces, but I'm having difficulties when moving into conditions as it moves it to the outter most level (same as top sequence e.g. hm_test_99) then when refreshing it goes back to the same position. I'm also having problems when trying to move into loops, the screen sometimes goes blank, then there are no changes. 

I have been testing loops here; https://closer-react.herokuapp.com/instruments/hm_test_99/build/constructs/

Also trying moving into conditions here; https://closer-react.herokuapp.com/instruments/alspac_covid_q2/build/constructs/

**Comment by simonreed** [comment]
This is now on closer-react

**Comment by HayleyMills** [comment]
This now appears to work. I also just realised, that you need to make sure that the whole tree is expanded before trying to move, otherwise the screen goes blank, as it can't move it to that part of the tree.
