### ISSUE TITLE
REACT: In the middle of moving constructs the page goes blank

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#523]
On several occasions when moving constructs the page has gone blank- this may be related to #502

**Comment by simonreed** [comment]
Do we have an example on the heroku react instance that I can replicate?

**Comment by HayleyMills** [comment]
This is difficult to replicate, I was moving things in https://closer-react.herokuapp.com/instruments/hm_test_99/build/constructs/ for about 5 minutes and it did it twice.

**Comment by HayleyMills** [comment]
![image](https://user-images.githubusercontent.com/16664703/107494672-fb400a80-6b86-11eb-8a65-95430172b709.png)

**Comment by simonreed** [comment]
The fix for this is now on heroku-react

**Comment by HayleyMills** [comment]
It is difficult to test this as there is no trigger, but tested this on a few instruments without the screen going blank. Will be tested further when it is used more.
