### ISSUE TITLE
REACT: When moving a construct inside a condition and positioning it- it reverts to the bottom after refreshing

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#524]
If you a move a construct to inside a condition and position it at the top of the, after refreshing it is moved to the bottom of the condition. This is the case for both the true and false.

**Comment by simonreed** [comment]
hi @HayleyMills could I get an example to replicate I can't seem to see the same issue when looking at https://closer-react.herokuapp.com/instruments/LSYPE_Wave_5_3/build/constructs/ and c_qEduc_ii

**Comment by HayleyMills** [comment]
Hi @simonreed in your example, i moved qc_Apprent1 to the top position inside c_qEduc_ii and after refreshing it moves back to the bottom?

**Comment by simonreed** [comment]
This should now be fixed on heroku-react

**Comment by HayleyMills** [comment]
Constructs are now saving in the correct position inside true and false branches.
