### ISSUE TITLE
REACT: Construct summary pages add missing link to build page

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#527]
These pages are linked from the main build page:
https://closer-archivist-staging.herokuapp.com/instruments/onsls_11_inde/summary/cc_condition
https://closer-archivist-staging.herokuapp.com/instruments/onsls_11_inde/summary/cc_loop  #424 
https://closer-archivist-staging.herokuapp.com/instruments/onsls_11_inde/summary/cc_question  #125 
https://closer-archivist-staging.herokuapp.com/instruments/onsls_11_inde/summary/cc_sequence
https://closer-archivist-staging.herokuapp.com/instruments/onsls_11_inde/summary/cc_statement

**Comment by simonreed** [comment]
@HayleyMills these are now on closer-react

**Comment by HayleyMills** [comment]
Tested and these are now available.

**Comment by HayleyMills** [comment]
JS- https://closer-archivist-staging.herokuapp.com/instruments/onsls_11_inde/summary/cc_condition doesn't have the option to go back to the build page, the other pages do.

**Comment by simonreed** [comment]
@HayleyMills this is now fixed on staging

**Comment by HayleyMills** [comment]
Link now on condition summary page.
