### ISSUE TITLE
REACT: Build/Question page drop down display format

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#529]
NV and JS suggestion. Can the drop down to add the response domain on the code list page be refomatted so that it doesn't include the text “Response Domain" and only Numeric, date, text, code?

**Comment by simonreed** [comment]
@HayleyMills Is this the page and dropdown in question. It no longer says Response Domain but do we want to go back and add the Numeric etc part?

<img width="1403" alt="Screenshot 2021-05-26 at 16 11 30" src="https://user-images.githubusercontent.com/13276/119685167-091b5200-be3d-11eb-98c6-73fe1b02c6e5.png">

**Comment by HayleyMills** [comment]
@simonreed I think this is the wrong page sorry (I've updated the title), I think this refers to the Question page see image below. There is an issue with the drop down in your screen shot but that is in #561

![image](https://user-images.githubusercontent.com/16664703/119686161-f3f2f300-be3d-11eb-88e5-afda0541077a.png)

**Comment by simonreed** [comment]
This is now on closer-react

<img width="1075" alt="Screenshot 2021-05-27 at 17 12 22" src="https://user-images.githubusercontent.com/13276/119860894-b4480c00-bf0e-11eb-8258-c02a109bd6fa.png">
