### ISSUE TITLE
REACT: Document view page - missing info

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#530]
The page is missing the following information: 
1) the construct labels e.g. https://closer-react.herokuapp.com/instruments/alspac_00_ayc/ ABOUT YOUR CLASS should have the label  s_intro_i . 

2) the code values e.g. 1 Yes 2 No

3) The condition logic e.g. [qc_A2_a == 1 || qc_A2_a == 2 || qc_A2_b == 1 || qc_A2_b == 2]

#240 #90

**Comment by simonreed** [comment]
This has now been deployed to heroku.

**Comment by HayleyMills** [comment]
All important information is now displayed. 
The sequence label is the sequence text and so it only needs to be displayed once.

**Comment by simonreed** [comment]
> The sequence label is the sequence text and so it only needs to be displayed once.

@HayleyMills Is this still happening, I can only see the sequence title displayed once.

**Comment by HayleyMills** [comment]
@simonreed Yes I can only see it once now too.
