### ISSUE TITLE
REACT: Document view page formatting

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#532]
There is no clear distinction between any of the items on the page. It should be clear when one item ends and another starts and what are the sequences.

It should also be possible to distinguish between the levels of the tree easily.

**Comment by simonreed** [comment]
This has now been deployed to heroku.

**Comment by HayleyMills** [comment]
The labels have now all be coloured blue, so it is still hard to distinguish between any of the construct types particualry the sequences. In addtion, the levels are not clear. 

It doesn't have to be the same as the current view as I'm not sure how/what the best way this can be done in react but for example the current doc view each;
- sequence has a black background
- level is a different colour grey
- construct has a box around it so you know the start and end clearly
- contruct type is distinquished by an icon
- response domain has a black background 

![image](https://user-images.githubusercontent.com/16664703/110784800-0bb8d300-8262-11eb-9446-948b44182cab.png)
![image](https://user-images.githubusercontent.com/16664703/110784806-0eb3c380-8262-11eb-8edb-a876e5e0bff0.png)

**Comment by simonreed** [comment]
This is now on heroku-react

**Comment by HayleyMills** [comment]
This is so much better!

Minor changes:
- Sometimes the text overlaps 
![image](https://user-images.githubusercontent.com/16664703/111600954-cba9a100-87c9-11eb-9c87-a5819285b583.png)
-Would it be possible to add cardinality underneath the code list? #240

**Comment by HayleyMills** [comment]
Can we please remove the names of the items? e.g. Question:, Statement:, loop: etc.

**Comment by simonreed** [comment]
This is on heroku-react

**Comment by HayleyMills** [comment]
Yes this has now been udpated. It's much better. I suspect there will be further changes needed, but I will ask for input from JS.
