### ISSUE TITLE
REACT: List of features for Dataset views

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#533]
- [x] - Ability to search for dataset
- [x] Ability to search for variable on a dataset view
- [x] Ability to map topics

#218

**Comment by simonreed** [comment]
@HayleyMills you can now search for Dataset by 'Name' this is true for both '/datasets' and '/admin/datasets'.

**Comment by HayleyMills** [comment]
Search boxes tested.

**Comment by HayleyMills** [comment]
Sorry, search box is missing from the dataset view to search for variable name on this page e.g. https://closer-react.herokuapp.com/datasets/85

**Comment by simonreed** [comment]
This is now on staging

**Comment by HayleyMills** [comment]
There is now the search ability, but ideally we would like to be able to search within a dataset for everything e.g. 
https://closer-archivist-staging.herokuapp.com/datasets/551
Source question- qc_A1_d
Topic - infections
Label - cough

**Comment by simonreed** [comment]
> @simonreed Great thanks. There is now the search ability. Sorry should have been clearer but ideally we would like to be able to search within a dataset for everything e.g. https://closer-archivist-staging.herokuapp.com/datasets/551
> Source question- qc_A1_d
> Topic - infections
> Label - cough

This is now on closer-react

**Comment by HayleyMills** [comment]
Reopening, as the search is no longer finding questions in a dataset view e.g. searching for qc_9 https://closer-archivist-staging.herokuapp.com/datasets/665 there are no results, but it shoud find and show the row- 237669 | CCXD45

**Comment by HayleyMills** [comment]
Tested with example below and it works for all the examples above.
