### ISSUE TITLE
Is it possible to have two exports one for everything and one for Discovery?

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#539]
Currently the instrument XML export only includes content which we want to load into Discovery (it doesn't inlcude anything which doesn't make up the constructs). Would it also be possible to have an export option which includes all content as well e.g. code lists/responses not attached to question items/grids and question items/grids not included in constructs?

This would be useful for importing tables into Archivist via the Gitlab for example if we already have lists of code lists in Excel. 

We could possibly use copy function which would copy db content and not rely on xml. The downside would be that we wouldn't be able to copy accross Archivists and so we would only be able to insert via the Gitlab content which has contructs.

**Comment by simonreed** [comment]
@HayleyMills this is now on staging, it appears as an option in the admin/datasets page.

**Comment by HayleyMills** [comment]
Great, I think there is an issue with the download in th UI similar to #669

**Comment by HayleyMills** [comment]
This is now working, tested in closer_dast which doesn't contain any constructs and the DOWNLOAD COMPLETE EXPORT appears and contains the question item and code list as expected.
