### ISSUE TITLE
The exporter is not exporting the code list order correctly- incorrect code list order loaded into Discovery

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#542]
The exporter appears to be randomly ordering the categories in the code lists. This was spotted by JS when the parsed us_covid_q5 from GitLab was exported from the temp and imported into US- the code lists category order had changed. 

I checked the orginally parsed instrument database and the order was correct in the database and in Archivist, but not in the xml and so not when it is imported. 

I have tested out exporting the same instrument on two different occasions and the order of the categories is different (although when I exported one after another the same order seems to be produced.) 

See attached xml for differences as well as Archivist re-imported https://closer-temp.herokuapp.com/instruments/UKHLS_Covid_Sept_2020_2021_03_05 and https://closer-temp.herokuapp.com/instruments/UKHLS_Covid_Sept_2020_2021_03_10
Examples cs_traceinfoeng_choice ( qc_traceinfoeng) and cs_j1mngr_choice (qc_Jbmngr)

I did some spot checking of recently added instruments to Discovery and found that for ALSPAC g0 and g1 some categories are not in the correct order. This however reflects what is in Archivist (the worng order) as these questionnaires were exported/imported to copy them into two versions. So it's possible it has only effected those which have been exported/imported first. 

I can't think of an easy way of checking that the instruments in Discovery are okay, or a way of checking whether the order of the categories is correct in the xml that was loaded. 

[UKHLS_Covid_Sept_2020_2021-03-05.txt](https://github.com/CLOSER-Cohorts/archivist/files/6117735/UKHLS_Covid_Sept_2020_2021-03-05.txt)

**Comment by spuddybike** [comment]
@simonreed can you take a look at this first thing tomorrow

**Comment by simonreed** [comment]
@spuddybike could I get access to closer-temp on heroku to help debug?

**Comment by HayleyMills** [comment]
@simonreed this may have been caused or be related to #312

**Comment by simonreed** [comment]
In this example should we ensure that the codes are ordered by value?

````
<l:CodeList>
<r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-cl-078312:1.0.0</r:URN>
<r:Label>
<r:Content xml:lang="en-GB">cs_traceinfo_choice</r:Content>
</r:Label>
<l:Code>
<r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-co-388000:1.0.0</r:URN>
<r:CategoryReference>
<r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-ca-283495:1.0.0</r:URN>
<r:TypeOfObject>Category</r:TypeOfObject>
</r:CategoryReference>
<r:Value>3</r:Value>
</l:Code>
<l:Code>
<r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-co-388001:1.0.0</r:URN>
<r:CategoryReference>
<r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-ca-283627:1.0.0</r:URN>
<r:TypeOfObject>Category</r:TypeOfObject>
</r:CategoryReference>
<r:Value>1</r:Value>
</l:Code>
<l:Code>
<r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-co-388002:1.0.0</r:URN>
<r:CategoryReference>
<r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-ca-283935:1.0.0</r:URN>
<r:TypeOfObject>Category</r:TypeOfObject>
</r:CategoryReference>
<r:Value>2</r:Value>
</l:Code>
</l:CodeList>
````

**Comment by simonreed** [comment]
> In this example should we ensure that the codes are ordered by value?
> 
> ```
> <l:CodeList>
> <r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-cl-078312:1.0.0</r:URN>
> <r:Label>
> <r:Content xml:lang="en-GB">cs_traceinfo_choice</r:Content>
> </r:Label>
> <l:Code>
> <r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-co-388000:1.0.0</r:URN>
> <r:CategoryReference>
> <r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-ca-283495:1.0.0</r:URN>
> <r:TypeOfObject>Category</r:TypeOfObject>
> </r:CategoryReference>
> <r:Value>3</r:Value>
> </l:Code>
> <l:Code>
> <r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-co-388001:1.0.0</r:URN>
> <r:CategoryReference>
> <r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-ca-283627:1.0.0</r:URN>
> <r:TypeOfObject>Category</r:TypeOfObject>
> </r:CategoryReference>
> <r:Value>1</r:Value>
> </l:Code>
> <l:Code>
> <r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-co-388002:1.0.0</r:URN>
> <r:CategoryReference>
> <r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-ca-283935:1.0.0</r:URN>
> <r:TypeOfObject>Category</r:TypeOfObject>
> </r:CategoryReference>
> <r:Value>2</r:Value>
> </l:Code>
> </l:CodeList>
> ```

At the moment it's ordered by 'code.order' so it should still be consistent everytime.

**Comment by HayleyMills** [comment]
The categories should be ordered by the order in the codes table in Archivist (code.order) as this isn't necessarily the same as the order of the code value. It seems to me that the order in these tables is correct for 118 but when this is exported and imported this order is not maintained. As far as I can tell the xml export from 118 doesn't match with the order in code.order?

**Comment by simonreed** [comment]
I need access to the db and closer-temp on heroku to take a look at this specific example, I can't see an issue within the code itself.

**Comment by simonreed** [comment]
The original XML is exporting with the categories in the right order `code.order`

https://closer-temp.herokuapp.com/instruments/118/export/144

````
<l:CodeList>
<r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-cl-002159:1.0.0</r:URN>
<r:Label>
<r:Content xml:lang="en-GB">cs_traceinfoeng_choice</r:Content>
</r:Label>
<l:Code>
<r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-co-010717:1.0.0</r:URN>
<r:CategoryReference>
<r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-ca-008746:1.0.0</r:URN>
<r:TypeOfObject>Category</r:TypeOfObject>
</r:CategoryReference>
<r:Value>1</r:Value>
</l:Code>
<l:Code>
<r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-co-010718:1.0.0</r:URN>
<r:CategoryReference>
<r:URN>urn:ddi:uk.iser:UKHLS_Covid_Sept_2020-ca-008721:1.0.0</r:URN>
<r:TypeOfObject>Category</r:TypeOfObject>
</r:CategoryReference>
<r:Value>2</r:Value>
</l:Code>
</l:CodeList>
````

**Comment by HayleyMills** [comment]
Sorry, yes it is for that code list in that XML downloaded on 10th but not for cs_j1mngr_choice. Some code lists are in correct order, some are not. 

cs_traceinfoeng_choice is not in the correct order for XML downloaded on 5th.

**Comment by simonreed** [comment]
Where was the XML generated from? I've tested the exporter and importer and I can't seem to replicate on closer-temp. Where was the original incorrect XML generated on?

**Comment by simonreed** [comment]
Do we have an example where the database is correct but the exported XML isn't?

**Comment by HayleyMills** [comment]
Yes if you look at https://closer-temp.herokuapp.com/instruments/118/export/144
![image](https://user-images.githubusercontent.com/16664703/110822464-fe630f00-8288-11eb-9931-e2b11cacd99d.png)
https://closer-temp.herokuapp.com/instruments/118
![image](https://user-images.githubusercontent.com/16664703/110822624-294d6300-8289-11eb-8d9c-e5e2f1741a33.png)

**Comment by simonreed** [comment]
@HayleyMills @spuddybike sorry it's late but here's the PR for this fix https://github.com/CLOSER-Cohorts/archivist/pull/545

**Comment by spuddybike** [comment]
@HayleyMills this is now on staging for testing

**Comment by HayleyMills** [comment]
It's difficult to test on staging, as I cannot find an example on live/staging which was exporting incorrectly. There is an example in the Temp and so the codebase of this was updated to the Staging and I exported and instrument and loaded it into staging, but the code lists are still incorrect. Should the temp now be the same as staging?

UKHLS_Covid_Sept_2020_2021_03_24
https://closer-archivist-staging.herokuapp.com/instruments/UKHLS_Covid_Sept_2020_2021_03_24

**Comment by HayleyMills** [comment]
Tested as JJ recomended by editing a code list of an instrument on live and staging and moving the new category to the top of the list. The staging Archivist should use the code order to export and the live would still use the order when created. Exported and reimported into staging and the live had the incorrect order and the staging version the correct order, as expected. 

https://closer-archivist-staging.herokuapp.com/instruments/nshd_53_sd
https://closer-archivist-staging.herokuapp.com/instruments/nshd_53_sd_staging
https://closer-archivist-staging.herokuapp.com/instruments/nshd_53_sd_live

See qc_3 and qc_5b
