### ISSUE TITLE
REACT: Question grids to be displayed in the doc view

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#543]
https://closer-react.herokuapp.com/instruments/alspac_00_msdhs e.g. A2

**Comment by simonreed** [comment]
This is on heroku-react

**Comment by HayleyMills** [comment]
Grids have now been added to the doc view. 

I think it would be preferable to only have the code list appearing once for each coloum rather than for each row. 

https://closer-archivist.herokuapp.com/instruments/alspac_00_ays
![image](https://user-images.githubusercontent.com/16664703/112500885-ae07a900-8d80-11eb-845d-5deb87c32b6e.png)
https://closer-react.herokuapp.com/instruments/alspac_00_ays/
![image](https://user-images.githubusercontent.com/16664703/112500924-b95ad480-8d80-11eb-806e-7985c4436405.png)

**Comment by simonreed** [comment]
This is on heroku-react

**Comment by HayleyMills** [comment]
Response domains are now only displayed once for each grid column.
