### ISSUE TITLE
REACT: instrument doc view to show which variables are mapped to questions

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#544]
For example https://closer-react.herokuapp.com/instruments/alspac_08_DCSF/ should show which variables are linked to the questions e.g. https://closer-archivist-staging.herokuapp.com/alspac_08_DCSF/

**Comment by simonreed** [comment]
This is now on staging

**Comment by HayleyMills** [comment]
Yes this is now displaying variables on the doc view.
