### ISSUE TITLE
REACT: Dataset view- cannot see the names of the variables mapped to derived variables

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#552]
https://closer-react.herokuapp.com/datasets/665

![image](https://user-images.githubusercontent.com/16664703/112488692-b27a9480-8d75-11eb-9e7d-e1b18e8e55c1.png)

**Comment by simonreed** [comment]
This is now on staging

**Comment by HayleyMills** [comment]
You can now see the variable labels in the source.
