### ISSUE TITLE
REACT: Need to be able to export the instrument XML

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#553]

**Comment by simonreed** [comment]
@HayleyMills effectively this page? https://closer-archivist-staging.herokuapp.com/admin/export

**Comment by simonreed** [comment]
This is now on heroku-react

<img width="1587" alt="Screenshot 2021-03-25 at 19 40 00" src="https://user-images.githubusercontent.com/13276/112533477-e53a8200-8da1-11eb-82bd-cf7542680e01.png">

**Comment by HayleyMills** [comment]
New export page is working well.
