### ISSUE TITLE
Not sure that the temp Archivist is correct version

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#554]
Codebase should be release which is Archivist staging but the temp version doesn't match this- is doesn't have the DDI imports page for example. I also think it is not importing correctly. I imported nshd_53_sd_live and nshd_53_sd_staging to test #542. But it didn't import qc_3 with the code list attached at all. It loaded okay in the staging Archivist.

We need it to use the latest version of the code with the exporter fix, as the main purpose is to export XML from the GitLab piepline.

**Comment by spuddybike** [comment]
@jli755 it is running off your fork, it should really be running off the release fork of the actual repository

**Comment by spuddybike** [comment]
moved gitrepo to be CLOSER-Cohorts\archivist
