### ISSUE TITLE
REACT: Document view not showing statments inside of conditions

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#555]
https://closer-react.herokuapp.com/instruments/mcs5/
![image](https://user-images.githubusercontent.com/16664703/112502237-d04df680-8d81-11eb-8ed0-6d9133bcf345.png)

https://closer-react.herokuapp.com/instruments/mcs5/build/constructs/
![image](https://user-images.githubusercontent.com/16664703/112502422-f70c2d00-8d81-11eb-8bb0-5b9c23e7a7dc.png)

https://closer-archivist-staging.herokuapp.com/instruments/mcs5
![image](https://user-images.githubusercontent.com/16664703/112502294-de9c1280-8d81-11eb-9052-b0af14023bbb.png)

**Comment by simonreed** [comment]
<img width="1194" alt="Screenshot 2021-03-25 at 19 35 52" src="https://user-images.githubusercontent.com/13276/112532938-5168b600-8da1-11eb-9e3d-955795c9ea1f.png">

**Comment by HayleyMills** [comment]
Statements are now in the doc view.
