### ISSUE TITLE
REACT: Document view not showing contents of else branch

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#556]
In addition, it should distinguish between the two branches.

https://closer-react.herokuapp.com/instruments/mcs5/
![image](https://user-images.githubusercontent.com/16664703/112503475-dabcc000-8d82-11eb-9c12-05cc2f8152ee.png)

https://closer-react.herokuapp.com/instruments/mcs5/build/constructs/
![image](https://user-images.githubusercontent.com/16664703/112503263-aea13f00-8d82-11eb-8538-78d3a1745ce4.png)

**Comment by simonreed** [comment]
<img width="1258" alt="Screenshot 2021-03-25 at 19 38 03" src="https://user-images.githubusercontent.com/13276/112533216-9ee52300-8da1-11eb-94c2-73c2230b31c4.png">

**Comment by HayleyMills** [comment]
True and False and now both included in the doc view.
