### ISSUE TITLE
REACT: Text input boxes are too small

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#558]
JS- In every instance where text is input – statements, conditions, question literals, instructions – it would be nice if text would display in a box so it can be viewed all at once, rather than as a long single line string. This would make it a lot easier to edit text in all of these circumstances. In old Archivist there were text boxes for constructs. Now these have also become single line strings as in question items. This is a move in the wrong direction in my view. All instances where text is input would be better off with a text box that displayed all of the text rather than a single line string of text.

**Comment by simonreed** [comment]
@HayleyMills I'm not quite sure what this means. Could you give me an example.

**Comment by HayleyMills** [comment]
![image](https://user-images.githubusercontent.com/16664703/119806941-9365c380-beda-11eb-9206-c1b53143492c.png)

**Comment by simonreed** [comment]
@HayleyMills Do we know which fields we'd like to have as multiline?

**Comment by simonreed** [comment]
Do we want the multiline option to appear for all text fields? The multiline option expands with the content so if it will look like a regular text field if they don't put in a long line of text.

**Comment by HayleyMills** [comment]
Condition literal, Condition logic and Statement literal on the construct page and if possible Question literal, Question instruction on the question page. 

If it's easier to all of them, then yes, but the ones above are the ones which are likely to have longer text and are important to see.

**Comment by simonreed** [comment]
@HayleyMills this is now on closer-react, I've made every text field a multiline. With the exception of any autocomplete (dropdowns).

**Comment by HayleyMills** [comment]
Tested and this works really well.
