### ISSUE TITLE
REACT: Change name of label on build/Code list page

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#560]
JS- The following are the lables for the codes
ID | Value | Label | Actions

Can 'Label' be changed to 'Category' as it currently is in Archivist. Category is still used as name for code list items on the Build summary page.

**Comment by HayleyMills** [comment]
In addtiion can the submit button be relabled to save.

**Comment by simonreed** [comment]
@HayleyMills this is now fixed on staging

**Comment by HayleyMills** [comment]
Tested on staging and it has been changed.
