### ISSUE TITLE
REACT: Selecting/reusing an existing category on the build/code list page

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#561]
JS -  When typing in the Label box, it doesn’t narrow the list of already input categories. Also categories that display seem to be in a random order so they are difficult to scroll through to find a category to reuse. Maybe having them display alphabetically would give the list some usefulness in filling in repeated categories in different code lists?

**Comment by HayleyMills** [comment]
![image](https://user-images.githubusercontent.com/16664703/119861829-ba8ab800-bf0f-11eb-98ab-6932146e96cf.png)

**Comment by simonreed** [comment]
@HayleyMills this is now on closer-react

**Comment by HayleyMills** [comment]
This is now working.
