### ISSUE TITLE
REACT: Confusing messages when entering a new code list or question

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#562]
JS - After submitting a code list and then clicking + NEW CODELIST the screen clears and a tick Created appears at the top of the blank screen for inputting the new code list. This is confusing as nothing has been created yet. The Label* field turns red and a Required appears below the Label* line eventhough no input has occurred yet. This is also confusing. Same also happens in Question Items screen.

**Comment by HayleyMills** [comment]
Simon has updated the code list page, so that once the code list has been saved, it stays on that page, rather than creating a blank new form. Consensus it that this is preferable. 

We therefore need to update the other pages (questions and responses), so the behaviour is the same.

**Comment by simonreed** [comment]
@HayleyMills this is now the same behaviour on staging for QuestionItems, QuestionGrids and all the Response Domains. All the build forms should perform the same way.

**Comment by HayleyMills** [comment]
Tested on staging and this works on Code lists, QuestionItems, QuestionGrids and all the Response Domains.
