### ISSUE TITLE
REACT: Build/ResponseDomain doesn't display the content of previous entered items

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#564]
e.g. https://closer-react.herokuapp.com/instruments/QuestionnairePrefix/build/response_domains/ResponseDomainDatetime/1975 when you click on Generic text for example it shows an empty form.

**Comment by HayleyMills** [comment]
JS - In addition, when you + NUMERIC and create a new numeric and submit this, if you ckick + NUMERIC then it doesn't provide a new empty form to enter another numeric, it still displays the submitted numeric.

**Comment by simonreed** [comment]
This is on staging

**Comment by HayleyMills** [comment]
This is now working.
