### ISSUE TITLE
REACT: build/questions doesn't always display the response domains attached to the grids

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#565]
JS - On question grid screen when you open up a question grid to edit, the Response domains Type and label isn’t visible all the time, making it look like the responses have not been entered when they have. 
e.g. https://closer-react.herokuapp.com/instruments/us1_asc/build/question_grids/8886
e.g. https://closer-react.herokuapp.com/instruments/heaf_15_fup3/build/question_grids/11420

**Comment by HayleyMills** [comment]
It appears this is having a knock-on effecting on viewing instruments. I think when the responses to a grid have dissapeared we cannot view the instrument. I'm not sure why this would be the case, as it should be possible to view the instrument even if there are no responses attached 

e.g. https://closer-react.herokuapp.com/instruments/hm_test_1_live_2/ this only has one sequence and one question grid https://closer-react.herokuapp.com/instruments/hm_test_1_live_2/build/constructs/ but it doens't display the view.

**Comment by HayleyMills** [comment]
@simonreed this looks like this is still the case. This would be top priority, as if submit is clicked it will save without any response domains attached.

**Comment by simonreed** [comment]
This is now on closer-react

**Comment by HayleyMills** [comment]
This is difficult to test, as there are still many question grids which don't have the response domains attached- but this could be the after effects of the bug. I think we may need to reset the database from the staging and check again?

**Comment by HayleyMills** [comment]
JJ reset the db and tested again, problem appears to have been resolved.

**Comment by HayleyMills** [comment]
This is happening again, the responses attached to a question grid are not displaying. They intiallly flash up, but then disapear. It doesn't appear to be effecting what has been saved though, as even after editing, the responses are still attached in the doc view https://closer-archivist-staging.herokuapp.com/instruments/cls_covid_q3_temp/build/question_grids/11913

**Comment by simonreed** [comment]
@HayleyMills this has now been changed to selects (dropdowns) instead of auto complete boxes on staging. It should now work as expected.

**Comment by HayleyMills** [comment]
Tested on staging and the response domains are now displaying. It is not ideal that we can only search on the first letter though, since all code list start with cs_. I'll have to get feedback from others. Moving to medium, as we are not entering many grids.

**Comment by HayleyMills** [comment]
On staging the response domains which have already been attached to the grids are no longer showing.

**Comment by HayleyMills** [comment]
I have had reports that the onsls and heaf version of Archivist this is happening again - the response domains attached to grids are not showing in the question grid page (they do not flash up first). I have been unable to replicate this though.
