### ISSUE TITLE
REACT: build/construct page expand and contract when adding items

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#566]
JS-  The option to selectively expand constructs only seems to appear once the constructs page has been refreshed or closed and reopened after constructs have been input. It would be nice for the selective expansion and collapse to be available while new input is happening without refreshing or closing and reopening the page.

**Comment by simonreed** [comment]
@HayleyMills I can't seem to replicate this now.

**Comment by HayleyMills** [comment]
Agree I can't replicate this now either, must have been resolved. As far as I can see when you add a condition the expand and contract is there for the True and Else and for sequences and loops the expand and contract appears once it has a construct inside it.
