### ISSUE TITLE
REACT: build/constuct condition branches should appear once the condition has been created

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#568]
JS - After being input the condition construct doesn’t initially give me any way to add a construct inside the condition. The branches should just show up as soon as condition is input or by having a ‘+’ option to click to allow the branches to appear once condition is input.

**Comment by simonreed** [comment]
This is now on closer-react

**Comment by HayleyMills** [comment]
This is now working, and I like the fact that all the True and Else have the names of the conditions, that should hopefully make it easier to navigate through the tree.
