### ISSUE TITLE
REACT: build/construct condition branch label change from "False" to "Else"

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#569]

**Comment by simonreed** [comment]
@HayleyMills is it not already 'Else'?

<img width="390" alt="Screenshot 2022-05-12 at 22 06 00" src="https://user-images.githubusercontent.com/13276/168168145-3c5eba6a-d859-4a8f-814a-22f9a78ebb53.png">

**Comment by HayleyMills** [comment]
Sorry yes!
