### ISSUE TITLE
REACT: build/view Loops are not appearing 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#570]
e.g. https://closer-react.herokuapp.com/instruments/hm_21_test/
https://closer-react.herokuapp.com/instruments/hm_21_test/build/constructs/

**Comment by simonreed** [comment]
This is on staging

**Comment by HayleyMills** [comment]
Loops are now included in the doc view, however the format needs to be changed so it forms scripting note. 

Label       Variable from Start Value while Variable <= End Value Loop While

e.g. 
Label: l_q2
Variable: _variable
Start Value: 1
End Value: 10
Loop While: && _variable < qc_1

l_q1         _variable from 1 while _variable <= 10 and && _variable < qc_1

**Comment by simonreed** [comment]
@HayleyMills this has now been fixed on staging, can you take a look.

**Comment by HayleyMills** [comment]
@simonreed This looks great, but apologies- my fault, we don't need the label in there.

**Comment by simonreed** [comment]
@HayleyMills no problem, removed the label on staging

**Comment by HayleyMills** [comment]
Thanks,.
