### ISSUE TITLE
REACT: Variables which are used a the source of a derived variable should show in the Used by

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#573]
For example https://closer-archivist-staging.herokuapp.com/datasets/85 variable VAR5516 is used by VAR5662 as can be seen in the Sources

**Comment by HayleyMills** [comment]
![image](https://user-images.githubusercontent.com/16664703/168563792-0cec6d20-734d-435c-abac-6d5a146e7cf7.png)

**Comment by simonreed** [comment]
This is now on staging

**Comment by HayleyMills** [comment]
Great, looks like this is working, but can the used by variables also appear in the search results please?

**Comment by simonreed** [comment]
@HayleyMills  This is now on staging
