### ISSUE TITLE
REACT: Ability to link datasets and instruments 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#584]
Would it be possible to add a new feature which allows datasets and instruments to be linked (table instruments_datasets) in the admin. This could be on either datasets or instruments edit pages or a whole new page.

**Comment by simonreed** [comment]
Also allow admin instrument form to allow the admins to edit the prefix and set the lock status.

**Comment by simonreed** [comment]
I've added the ability to toggle the lock "signed off" status of an instrument in the admin instrument form.

**Comment by HayleyMills** [comment]
Tested on staging and this is working.

**Comment by HayleyMills** [comment]
Great, this has been tested on staging and is working.
