### ISSUE TITLE
REACT: Dataset and Instrument search

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#585]
I think currently the dataset page search only searches for the dataset title- can we update this so it will also search the dataset ID and the datasets filename?

The instrument page looks like it is only searching on the prefix- can we update this so it will also search on the instrument ID and instrument label?

**Comment by simonreed** [comment]
This is now on staging

**Comment by HayleyMills** [comment]
Both issues have no been resolved.
