### ISSUE TITLE
REACT: Problem with assigning sources to dataset variable

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#586]
The source options for assigning questions to variables are restricted by the variable topic assigned. I think this could be a good feature, however, I think it needs to not include blank/empty mappings. 

For example https://closer-react.herokuapp.com/datasets/149 Variable NCDSID which is not mapped to a topic, there is only one question in the drop-down (qc_1), and it will also not search for other questions. This is because this question also doesn't have a topic assigned. Ideally if the variable doesn't have a topic, then it should allow users to select from any of the questions, and it would then inherit the topic assigned to that question. 

Similary with variables with a topic assigned e.g. N622, I would also expect to also be able to choose a question which is not mapped to a topic (qc_1) and then that question would inherit the variable topic. 

If I remove the topic from a variable, I would then expect to be able to select any question - as described above.

**Comment by simonreed** [comment]
@HayleyMills this is now on closer-react

**Comment by HayleyMills** [comment]
I think this is better, but needs a bit more work. 
e.g. https://closer-react.herokuapp.com/datasets/103
I would expect the choice of questions for abserno to agripr3 for example to be all questions as these do not have a topic,  therefore when you pick a question it will inherit that topic. 

It is working correctly for those variables which have topics as it only allows qc_14 to be selected which is the only question which is mapped to None, however it also needs to have this behaviour when it is also blank. As when I change qc_14 from None to blank the topic mapped variables no longer show qc_14 as an option. It is still an option for those variables with no topics.

**Comment by simonreed** [comment]
This is now fixed on https://closer-archivist-staging.herokuapp.com

**Comment by HayleyMills** [comment]
Variables with no topic and None topic now allows you to now map to any of the questions. When it has a topic which is associated with some questions it only shows those questions, which is great. 

However, if I change a variable topic mapping to a topic which has not yet been used or is used but without a question linked e.g. in the same example as above - changing abserno to Demographics or aht to Place of Birth, the list of source questions only shows qc_14 instead of all the questions.

In relation to this, if I add a question to a variable e.g. adding qc_1 to asitht I would expect the topic to either be inherited to Endocrine system, or to show a conflict when I select a different topic.

**Comment by simonreed** [comment]
> In relation to this, if I add a question to a variable e.g. adding qc_1 to asitht I would expect the topic to either be inherited to Endocrine system, or to show a conflict when I select a different topic.

@HayleyMills that should be fixed now on staging
