### ISSUE TITLE
REACT: Instrument doc view- interviewee

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#600]
Would it be possible to add the interviewee (response_unit) to each of the questions displayed in the Instrument View?

**Comment by HayleyMills** [comment]
This has been added, but it is slightly in the way, @simonreed  can we add it above the question label instead? Apologies I could have specified this in the orginal issue! We also need to include it for the question grids.

**Comment by simonreed** [comment]
@HayleyMills this is now on staging

**Comment by HayleyMills** [comment]
The position has changed, need to think about ways to make this view clearer.
