### ISSUE TITLE
REACT: Can the order of the topics in the drop-down be level 1 with level 2 inside

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#601]
Currently, the topic drop-down in the dataset and instrument map view are in a mixed order. Can the order show the level 1 with the level 2 inside? e.g. 
![image](https://user-images.githubusercontent.com/16664703/138843728-58c48ec2-3f71-4206-b962-a5c637f92f7a.png)

**Comment by HayleyMills** [comment]
In addition, would it be possible to type and narrow the drop down list so it is easier to find and select a topic, currently it will go to the first letter (for level 2 this is just -) only.

**Comment by simonreed** [comment]
The order is on staging however, the filter by name is more difficult as we've found the autocomplete work to be problematic elsewhere. @HayleyMills let me know if you want me to persevere with the autocomplete filtering.

**Comment by HayleyMills** [comment]
Thanks @simonreed are there any other options to make the selection of topics easier? It is currently very difficult to find a topic to add.

**Comment by simonreed** [comment]
@HayleyMills this is now running on staging
