### ISSUE TITLE
REACT: Instrument View page is not displaying instructions

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#602]
For example question A3 has an instruction "Complete first from records, then enter details from other sources in space marked 'extra information'." https://closer-archivist-staging.herokuapp.com/instruments/bcs_80_me/build/question_items/121452
But this cannot be seen in the instrument view page https://closer-archivist-staging.herokuapp.com/instruments/bcs_80_me/

**Comment by simonreed** [comment]
Can we test again on staging

**Comment by HayleyMills** [comment]
Yes this looks good now.

**Comment by HayleyMills** [comment]
Note this isn't on the live Archvist yet.
