### ISSUE TITLE
REACT: Admin user page is needed

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#603]
Need to view and add new users - https://closer-archivist-us.herokuapp.com/admin/users

**Comment by HayleyMills** [comment]
The link from the login page to the sign-up page is not working for me? Also when I sign-up with a test account it does create one but it also gives an error. Would it also be possible to add a reset password option?

![image](https://user-images.githubusercontent.com/16664703/142850170-6fe34de9-6ab6-4e9a-8848-bd29ff6b1690.png)

**Comment by simonreed** [comment]
@HayleyMills I've just deployed the latest changes to staging. You can now use the login/signup links.

Signup works as expected and when you signup it will log you in and create a new user with the 'editor' role.

**Comment by HayleyMills** [comment]
The link it now working which is good. I can create a new user which is great. I still get the error message even though it does still save. It automatically creates the new user as a reader, which is fine, as I can now edit this on the new user page, as well as delete users.

**Comment by HayleyMills** [comment]
This has not been resolved.
