### ISSUE TITLE
REACT: No search for finding and adding response domains to Question Grids

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#605]
When adding the response domain on the X axis, Y axis and response domain, it isn't possible to seach for the answer. Searching works ok for question items but not for question grids.

**Comment by simonreed** [comment]
@HayleyMills the alphabetical order is now on staging. Is this sufficient?

**Comment by HayleyMills** [comment]
Yes, since this is not and easy problem to solve, I will change the priority.

**Comment by HayleyMills** [comment]
I think it okay, but you have to click submit twice or refresh to see the change in the text.?

It also looks like it has effected the Y and X axis select boxes, as I can't see those and there is no drop down?

![image](https://user-images.githubusercontent.com/16664703/168788144-fe978ba6-dbb7-457e-a893-727d2d276beb.png)

**Comment by simonreed** [comment]
@HayleyMills the X and Y axis select boxes are now fixed

**Comment by HayleyMills** [comment]
Great thanks, these are now appearing, but the attached response domain appears then disappears when there is one column and doesn't appear at all when there is more than one? https://closer-archivist-staging.herokuapp.com/instruments/alspac_01_fas/build/question_grids/8983

**Comment by HayleyMills** [comment]
Had a look again, and the response domains columns, does update to reflect the Code list (X) when you click somewhere on the page including when you click the Type and Label.
