### ISSUE TITLE
REACT: New page which shows which instruments are linked to which datasets

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#612]
linked to #584

**Comment by simonreed** [comment]
I've added the links between Instruments and Datasets on the current list pages

![image](https://user-images.githubusercontent.com/13276/141273687-ea43142d-5c5b-4f1f-9a38-b1e4f6b6c012.png)

![image](https://user-images.githubusercontent.com/13276/141273826-9324a5c6-0f29-4681-bbd3-7046e45c6fd0.png)

this is now on staging.

**Comment by HayleyMills** [comment]
This works well, and also saves having another page. @simonreed can we change the display so it shows the prefixes rather than the titles though?, as I'm concerned that in some cases there can be up to 10 datasets linked to one instrument which will take up too much space.

**Comment by simonreed** [comment]
@HayleyMills A prefix for the instruments?

**Comment by HayleyMills** [comment]
On the instrument page for this example it would link to the datast using ce_indresp_w; ce_schild_w rather than
 COVID-19 Wave 5 Data from the individual interview DatasetCOVID-19 Wave 5 Data from the individual interview Dataset
Sorry realised this is not called the prefix for the dataset- it is effectively the first part of the filename. 

![image](https://user-images.githubusercontent.com/16664703/141347459-3092b3d7-d164-4b00-a71b-7234c24edd22.png)

Then on the dataset page in this example it would have the link to the instrument using the prefix us_covid_q5 instead of COVID-19 Wave 5 QuestionnaireCOVID-19 Wave 5 Questionnaire
![image](https://user-images.githubusercontent.com/16664703/141347781-1c7c3959-6d86-4e34-9aff-fc082caff76d.png)

**Comment by simonreed** [comment]
@HayleyMills this is now on staging

**Comment by HayleyMills** [comment]
This looks great.
