### ISSUE TITLE
REACT: /cc_questions.txt to include question grid items from Y axis

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#614]
The current /cc_questions.txt includes a list of question items (their ID, label and question text), e.g. https://closer-archivist-staging.herokuapp.com/instruments/heaf_13_base/cc_questions.txt but it doesn't list out the question grids. 

Can we add the question grids to this list but it would also need to include the XY axis (i.e. $1;1) and the categories for these as well, otherwise it will only be the same question literal repeated. 
e.g. 
qc_9_a-b$1;1	In an average week, and outside any paid jobs that you do, roughly how many hours would you spend doing the following activities? (Please answer each question) Physical activities sufficient to make you hot or sweaty (e.g. heavy gardening, dancing, cycling, jogging) 
qc_9_a-b$1;2	In an average week, and outside any paid jobs that you do, roughly how many hours would you spend doing the following activities? (Please answer each question) Meeting or doing things with friends or relatives who do not live in your home 

I have attached an example. 
This what it is like now -
[heaf_13_base_questions_now.txt](https://github.com/CLOSER-Cohorts/archivist/files/8676297/heaf_13_base_questions_now.txt)

This would be the ideal format -
[heaf_13_base_questions.txt](https://github.com/CLOSER-Cohorts/archivist/files/8676291/heaf_13_base_questions.txt)

**Comment by simonreed** [comment]
This is now fixed on staging

**Comment by HayleyMills** [comment]
Thanks @simonreed can you point me in the direction of the new download button please?

**Comment by HayleyMills** [comment]
https://closer-archivist-staging.herokuapp.com/admin/instruments/exports > view has all the instrument txt downloads and dataset downloads if there is a linked dataset.

**Comment by HayleyMills** [comment]
Thanks this is working well, I think this is my fault, but in light of what is being done with the all_mappings which also includes the X axis for the grids, can we update this to include cell references for those too please? i.e. for ncds_74_a it would also include 
qc_XI$2;1	LEFT EAR Hearing loss in dB 10	
qc_XI$2;2	LEFT EAR Hearing loss in dB 0	
qc_XI$2;3	LEFT EAR Hearing loss in dB 10	
qc_XI$2;4	LEFT EAR Hearing loss in dB 20	
qc_XI$2;5	LEFT EAR Hearing loss in dB 30	
qc_XI$2;6	LEFT EAR Hearing loss in dB 40	
qc_XI$2;7	LEFT EAR Hearing loss in dB 50	
qc_XI$2;8	LEFT EAR Hearing loss in dB 60	
qc_XI$2;9	LEFT EAR Hearing loss in dB 70	
qc_XI$2;10	LEFT EAR Hearing loss in dB 80	
qc_XI$2;11	LEFT EAR Hearing loss in dB 90	

Ideally both would also include the X header when there is more than one column, but I think just having all the cells listed out with the Y added is helpful.

**Comment by simonreed** [comment]
@HayleyMills  This is now on staging

**Comment by HayleyMills** [comment]
Great the .txt file now contains all the grid cells for multi-column grids.
