### ISSUE TITLE
REACT: Loop text is incorrect

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#622]
In react it is adding the start number in the incorrect place 

Example 1 with a start value of 1, no end value or loop while it should look like this with a [] at the end ideally - 
![image](https://user-images.githubusercontent.com/16664703/146803963-4aa7c742-59d4-4854-8c66-552ff5f447f9.png)

Not like this 
![image](https://user-images.githubusercontent.com/16664703/146804028-60bec8bd-92ee-4dae-bb07-af4ffb6f527c.png)

Example 2 when there is a start value 1 and end value 10 then it is also incorrect, it should look like this- 
_test from 1 while _test <= 10

Rather then this- 
![image](https://user-images.githubusercontent.com/16664703/146804311-bf03eb61-47f2-43cf-90af-1d63e18bd8a1.png)

Example 3 
When there is a start value 1 and a loop while it should look like this- 
![image](https://user-images.githubusercontent.com/16664703/146804712-bafe96dc-4a06-4b2a-80bb-68a46f51b5d2.png)

Rather than this- 
![image](https://user-images.githubusercontent.com/16664703/146804776-a7255fe0-0fc3-49f0-ba18-826b0405f57e.png)

**Comment by simonreed** [comment]
@HayleyMills with example 3 is the start value '1', loop_while is 'qc_test == 2' and the end value is 10?

**Comment by HayleyMills** [comment]
@simonreed apologies for not been clearer, example 3 start value is "1" and loop while is "qc_test == 2 and _test >= 10" there is no end value.

**Comment by simonreed** [comment]
@HayleyMills so what would happen if :

start value '1'
end value '10'
loop while 'qc_test == 2'

?

**Comment by HayleyMills** [comment]
_test from 1 while _test <= 10 and qc_test == 2

_variable_ **from** _start value_ **while** _variable end value_ _and_ _loop while_

**Comment by simonreed** [comment]
This is on staging

**Comment by simonreed** [comment]
@HayleyMills this is on staging

**Comment by HayleyMills** [comment]
Tested on staging it is now adding [] to the loop logic when there is no end value or loop while.

**Comment by simonreed** [comment]
@HayleyMills this is on staging

**Comment by HayleyMills** [comment]
AND has been changed to &&
