### ISSUE TITLE
REACT: Issues with the admin pages - permissons

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#623]
Intermitendly I lose the admin option when I am logged in, I have to log out and in again to see the pages. - I think is is only in the staging version. 

In addition, Jennifer Speigel doesn't have admin permission, but she can also see the admin pages? - in the live version.

**Comment by HayleyMills** [comment]
The staging server no longer removes my admin permissions.

**Comment by simonreed** [comment]
This is now on the staging site
