### ISSUE TITLE
REACT: Cannot load DV mappings

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#635]
When uploading dv.txt mappings to a dataset bu uploading and selecting DV mapping from the drop-down, it tries to load the file as a T-V mapping instead. https://closer-archivist.herokuapp.com/admin/datasets/1105/imports

[ncds_81_i.dv.txt](https://github.com/CLOSER-Cohorts/archivist/files/7897732/ncds_81_i.dv.txt)

**Comment by simonreed** [comment]
@HayleyMills This is now on staging

**Comment by HayleyMills** [comment]
Tested loading in a dv.txt file in teh staging Archivist and this is now loading.
