### ISSUE TITLE
REACT: Add option to add topics to question using the sequence

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#636]
Would it be possible to add a new feature to the questionnaire map page which can assign a topic to all qestions in a sequence? This might be similar to what is in the original Archivist (if it had worked). So in the example screenshot below the Coronavirus illness module has a drop-down which if a topic was assigned all the questions in that sequence would be mapped to that topic. 

![image](https://user-images.githubusercontent.com/16664703/151832199-5a6479fb-17e0-465d-b1e9-a9d03088a20f.png)

**Comment by simonreed** [comment]
@HayleyMills this is now on staging

**Comment by HayleyMills** [comment]
Tested on staging using https://closer-archivist-staging.herokuapp.com/instruments/alspac_01_rat/map/. It is partly working. 

If I assign a topic, it saves, but I have to refresh to see it e.g. 
![image](https://user-images.githubusercontent.com/16664703/157839160-db8fda74-7756-4964-ad3b-d1fc2ec44939.png)

After I refresh it does show the topic, but it is not appying all questions inside the sequence, I think it is only applying to questions where the parent is the sequence, but we will need it to apply to questions whos parents are children of the sequence?
e.g. 
![image](https://user-images.githubusercontent.com/16664703/157839497-1e5ba48b-ee50-4070-8239-d18cd16de5e7.png)

**Comment by HayleyMills** [comment]
Also unsure about the behaviour here https://closer-archivist-staging.herokuapp.com/instruments/alspac_08_DCSF/map
![image](https://user-images.githubusercontent.com/16664703/157840392-445ef80a-31ee-42d8-b17c-a882da56f13d.png)
The seqeunce has a topic Further education (I did not apply this), but qc_1 has a topic of Employment. There are other questions which have a parent of the sequence e.g. qc_2_i which do not have the sequence topic Employment?

**Comment by simonreed** [comment]
@HayleyMills This is now fixed on staging

**Comment by HayleyMills** [comment]
Great, so as it stands now, if there are resolved or added topics mapped to questions which are the first child of the sequence and they are all the same, then the sequence topic is available to update. Where the topics are not the same the option will not display. If you change the sequence topic it will change those first child questions to that, unless there is a conflict with the variable.

One minor niggle, is that when you apply a topic to the sequence, the questions say 'saving' then 'saved' but the topic doesn't actually display until you refresh the page. Would be good to sort if it is a quick fix.

**Comment by simonreed** [comment]
> One minor niggle, is that when you apply a topic to the sequence, the questions say 'saving' then 'saved' but the topic doesn't actually display until you refresh the page. Would be good to sort if it is a quick fix @simonreed

Fixed on staging

**Comment by HayleyMills** [comment]
Tested on staging and this is working.
