### ISSUE TITLE
REACT: Doc view should show labels for mapped variables

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#643]
In the orginal archivist if you clicked on the variable name it would pop up with the label and if you clicked the name again it would close. See example below. 

![image](https://user-images.githubusercontent.com/16664703/152840469-76d54356-1a53-4fd0-8934-4f0e9078ef34.png)

**Comment by simonreed** [comment]
<img width="1265" alt="Screenshot 2022-03-24 at 16 22 10" src="https://user-images.githubusercontent.com/13276/159963001-7cc49f7e-fd58-4b80-9779-e505da9e1ef3.png">

This is now on staging
