### ISSUE TITLE
REACT: Add filename to datasets view

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#649]
Is it possible to include the dataset filename somewhere in the dataset - perhaps in the edit (https://closer-archivist.herokuapp.com/datasets/1112/edit) or on the dataset page (https://closer-archivist.herokuapp.com/datasets/1112) so for this example it would be bcs_86_strt.

**Comment by simonreed** [comment]
@HayleyMills This is now on staging

**Comment by simonreed** [comment]
@HayleyMills This is now on staging

<img width="1499" alt="Screenshot 2022-04-25 at 21 56 43" src="https://user-images.githubusercontent.com/13276/165173561-59c25cec-ab49-4d60-bccd-cd6c563ca462.png">

**Comment by simonreed** [comment]
This appears on the view page for a Dataset.

**Comment by HayleyMills** [comment]
Tested on staging and the name has been added, which will be really helpful.
