### ISSUE TITLE
REACT: Dataset page not loading after changing variable type to derived

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#653]
This may be unique to this example, as I have not been able to replicate on the staging, but for dataset https://closer-archivist-us.herokuapp.com/datasets/1020 a variable was type was changed from normal to derived (it did not have any mappings) and now the dataset will not load. I havn't had this problem on the staging Archivist.

**Comment by simonreed** [comment]
@HayleyMills the dataset is loading now, is there a specific section i should be looking at or do you think the issue is now fixed by itself?
