### ISSUE TITLE
REACT: Code lists, Response Domains and Question pages panel too narrow

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#660]
JS - The column that displays the labels is sometimes too narrow to see which label has been highlighted from the search. Can the width of this column be adjustable or adaptable to the size of the lables?

**Comment by simonreed** [comment]
@HayleyMills the Code Lists page on staging now has an arrow on the sidebar that allows you to expand that sidebar if you want to search and see the full names.

Let me know if this is ok and I'll roll it out to the other build pages.

**Comment by HayleyMills** [comment]
Tested on staging using https://closer-archivist-staging.herokuapp.com/instruments/us2/build/code_lists/. I can't seem to see where the arrow is for expanding?

**Comment by simonreed** [comment]
@HayleyMills this is now on staging <img width="444" alt="Screenshot 2022-04-29 at 14 23 33" src="https://user-images.githubusercontent.com/13276/165952926-c5c56af6-3a08-4009-b699-314279d72beb.png">

**Comment by HayleyMills** [comment]
Comments "being able to adjust the width freely would be the most ideal solution, but I think what we have now does the job."
" it is not possible, can we put two arrows (in two stages) to increase the size of the left-hand column instead of one arrow"
Can either of these solutions be implemented, if not can it ben rolled out to the other pages please?

**Comment by simonreed** [comment]
These are now on staging @HayleyMills

**Comment by HayleyMills** [comment]
I cannot see the arrow on the other pages? Also can we have the expand only go half way across the page plaease?

**Comment by simonreed** [comment]
@HayleyMills changed on staging, let me know if you want more space.

**Comment by HayleyMills** [comment]
Looks great, much better thanks.
