### ISSUE TITLE
Download export link not showing for instruments

### ISSUE THREAD

**Issue by simonreed** [CLOSER-Cohorts/archivist#661]
You can 'Create new export' however there is no export_url or export_date being returned for the instruments.

**Comment by HayleyMills** [comment]
Note - this was working in the past (a month ago), as an exporter Gitlab pipeline was created based on this and it was working then. I tried again last week and it failed- which must have been for this reason.

**Comment by HayleyMills** [comment]
This is now working.

**Comment by HayleyMills** [comment]
@simonreed Tested on live version now that has been deployed on the main Archvist, but it is no longer woeking. It is running on sidekiq, but the buttons are not appearing. I have tried exporting alspac_covid_g1q5, alspac_covid_g0q5, ns_15_w8, for both exports.

**Comment by HayleyMills** [comment]
Simon ran the migrations in. It is now working.
