### ISSUE TITLE
REACT: Text response in grids doesn't show the max length

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#662]
e.g. see https://closer-archivist-staging.herokuapp.com/instruments/bcs_86_pif_test/ qc_A7 it has "Generic text (no maximum length)" instead of "Generic text (255 maximum length)" which can be seen in the question items e.g. qc_A5.

**Comment by simonreed** [comment]
@HayleyMills This is now on staging

**Comment by HayleyMills** [comment]
Tested on staging, the max is no displaying.
