### ISSUE TITLE
REACT: Some instruments are not loading the view page (including map)

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#667]
There are several instruments on the live and staging which are not loading the document view or the map view. The construct view is loading. This doesn't seem to be related to whether the instrument is signed off or not, but this shouldn't effect whether the doc view is visible anyway. Examples include
https://closer-archivist-staging.herokuapp.com/instruments/alspac_96_spq/
https://closer-archivist-staging.herokuapp.com/instruments/alspac_00_msdh/

**Comment by simonreed** [comment]
@HayleyMills this is now on staging

**Comment by HayleyMills** [comment]
Tested on staging and these are now loading.
