### ISSUE TITLE
REACT: Instructions not displaying on question grids in doc view

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#670]
e.g. https://closer-archivist-staging.herokuapp.com/instruments/hm_test_2_import2/

All grids have instructions but they are not displaying on the doc view. This is true for staging and main Archivist.

**Comment by simonreed** [comment]
@HayleyMills this is now on staging

**Comment by HayleyMills** [comment]
Tested on staging, the grid Y axis is now not displaying see  https://closer-archivist-staging.herokuapp.com/instruments/hm_test_2_import2/ qc_G9_test 4

**Comment by simonreed** [comment]
@HayleyMills what should it look like, are we saying the first column is missing?

**Comment by HayleyMills** [comment]
Yes it should look like this ![image](https://user-images.githubusercontent.com/16664703/165130415-89ecafea-7e16-46c7-ac0d-9a32de942d1a.png)
Rather than this 
![image](https://user-images.githubusercontent.com/16664703/165130486-a19b6d64-8993-4432-b1b6-f18f01023c0c.png)

I don't think it is realted to your latest change as it is also an issue on the main Archivist- shall I create a new ticket? @simonreed

**Comment by simonreed** [comment]
@HayleyMills this should now be fixed on staging.

**Comment by HayleyMills** [comment]
This is now displaying, however there is a rogue 0 at the bottom of all the grids. Is this the roster number? - can we hide this?
![image](https://user-images.githubusercontent.com/16664703/165928030-031fa558-290a-4310-b9c1-7d3970bb2c1a.png)
 https://closer-archivist-staging.herokuapp.com/instruments/hm_test_2_import2/
