### ISSUE TITLE
REACT: Doc view Build link not working

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#671]
On the staging Archivist when I am on the doc view e.g. https://closer-archivist-staging.herokuapp.com/instruments/hm_test_2_import2/ and click the build, the link directs to https://closer-archivist-staging.herokuapp.com/instruments/:instrument_id/build/ instead of https://closer-archivist-staging.herokuapp.com/instruments/hm_test_2_import2/build. 

This is not the case for the main Archivist.

**Comment by simonreed** [comment]
@HayleyMills this is now on staging

**Comment by HayleyMills** [comment]
Tested on staging and the links now appear to be working.
