### ISSUE TITLE
REACT: Can we add a forgot password functionality to the user login page?

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#681]
There is a workaround in that I can delete the user and they can sign-up again with a new password.

**Comment by simonreed** [comment]
@HayleyMills this is now on staging, we've changed email provider from Sendgrid to Mailgun and will need to make those changes onto all the environments.

**Comment by HayleyMills** [comment]
Tested on staging and this is now working.
