### ISSUE TITLE
REACT: New .txt files for missing mappings

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#683]
Would it be possible to create a couple of new .txt files to download. Currently, I download tv.txt, qt.txt, mapper.txt and variables.txt to create spreadsheet which I can use to see which questions/variables have not been mapped to topics, which questions have not been mapped to variables and which variables have not been mapped to questions/variables. It would be great if new .txt files can be created to save time in the creation of these. I'm not sure the best way to do this is. 

The easiest way may be to create an additonal version of the txt files with the addtional info. 
1) qv_all.txt would need to contain all the questions not just the ones which have been mapped, as well as the question literal and variable label. 
2) tv_all.txt addition of variable label
3) qt_all.txt addition of question literal
4 dv_all.txt addition of both variable labels

Alternative would be to create one new .txt which contains all the info which would be something like this (doesn't contain dv info)...
[mappings.txt](https://github.com/CLOSER-Cohorts/archivist/files/8688259/mappings.txt)

**Comment by simonreed** [comment]
This is all on staging, you can download the file here
<img width="1502" alt="Screenshot 2022-05-19 at 09 38 58" src="https://user-images.githubusercontent.com/13276/169251010-4a5b8d32-eed0-4fad-8ec2-fd979bfe0bd6.png">

**Comment by simonreed** [comment]
This is now on staging with the question grid question text including the category. Also fixed the mappings not showing properly on the map page.

**Comment by HayleyMills** [comment]
Great, on what page will I find it?

**Comment by HayleyMills** [comment]
Th all_mappings .txt file can be downloaded from the instrument > map page.

**Comment by HayleyMills** [comment]
I'm confused by what the extra column is?
[all_mappings_us_covid_q2.txt](https://github.com/CLOSER-Cohorts/archivist/files/8737885/all_mappings_us_covid_q2.txt)

**Comment by simonreed** [comment]
@HayleyMills  This is now on staging

**Comment by HayleyMills** [comment]
Tested on staging and this has now been removed.
