### ISSUE TITLE
REACT: Add percentages for the number fo mappings completed

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#687]
Now that we have these additional pages #684 
This might be a good place to add some percentages for the number fo mappings completed i.e.
Number of questions mapped to variables as a percentage of questions
Number of questions mapped to topics as a percentage of questions
Number of variables mapped to questions as a percentage of variables
Number of variables mapped to topics as a percentage of variables 

It may need some more thought.

**Comment by HayleyMills** [comment]
#655

**Comment by simonreed** [comment]
@HayleyMills on staging this is found on instrument map and dataset view pages e.g. https://closer-archivist-staging.herokuapp.com/instruments/mcs_12_ch/map/ and https://closer-archivist-staging.herokuapp.com/datasets/753

**Comment by HayleyMills** [comment]
Tested on staging, and this is great, really helpful.
