### ISSUE TITLE
REACT: Datasets not deleting

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#692]
Issue raised by BO. Datasets 1039 and 1054 not deleting in the US version of Archivist. In-out-worker on. Should this type of process be seen in sidekiq?

Tested on staging deleting 281, but it also didn't delete. It did however delete smaller datasets.

**Comment by simonreed** [comment]
@HayleyMills this is now on staging

**Comment by HayleyMills** [comment]
Tested on stgaing by deleting a large dataset, it appeared in Sidekiq and toook about 2min to delete.
