### ISSUE TITLE
REACT: construct page not loading in the middle of being used

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#693]
BO - When editing things on the constructs page, every few edits the screen goes white and I have to refresh the page to get the questionnaire to reappear. Not a huge issue but can be annoying when working on nested conditions.

May be resolved with new version is deployed which has resolved memory N+1 issues?

**Comment by simonreed** [comment]
@HayleyMills is this still an issue after the deploy?

**Comment by HayleyMills** [comment]
@simonreed so far so good :)
