### ISSUE TITLE
Update Heroku to latest stack

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/archivist#701]
The Heroku-18 stack is deprecated
You have 6 personal apps that are using the Heroku-18 stack, which is deprecated. From April 30th, 2023, Heroku-18 will be end-of-life and no longer receive security updates. From May 1st, 2023, builds will be disabled. Please upgrade your apps to a newer Heroku stack.  [ Visit here to learn more](https://help.heroku.com/X5OE6BCA/heroku-18-end-of-life-faq)

**Comment by spuddybike** [comment]
This also involves upgrading Rails & Ruby - this is likely to be a longer process - deferred until later in 2022

**Comment by HayleyMills** [comment]
@spuddybike has this been resolved?
