### ISSUE TITLE
REACT: questions in condition Else branch and loops are not showing in map view and can't be mapped via .txt files

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#702]
For example ncds_81_i question qc_currentjob_17_a_B is in the Else branch of c_currentjob_q17cA. https://closer-archivist-staging.herokuapp.com/instruments/ncds_81_i/

However this question does not appear in the map view https://closer-archivist-staging.herokuapp.com/instruments/ncds_81_i/map/

This is also true for questions in loops e.g. qc_familyincome_2_a_i which is inside l_familyincome_q2a_TEST

It will also not load mappings for these questions https://closer-archivist-staging.herokuapp.com/admin/instruments/1989/imports/546

**Comment by simonreed** [comment]
@HayleyMills https://closer-archivist-staging.herokuapp.com/admin/instruments/1989/imports/546 was imported as a TopicQ import rather than a mapping. Therefore it can't find the CcQuestion as it's written as `qc_currentjob_17_a_B$0;0` instead of `qc_currentjob_17_a_B`.

**Comment by simonreed** [comment]
The other issue is fixed on staging.

**Comment by HayleyMills** [comment]
Tested on staging and the False (to be changed to Else) branch of conditions are now showing in the map view with their question children. 

Still outstanding issue of the the loops and children not showing in the map view e.g. l_familyincome_q2a_TEST (https://closer-archivist-staging.herokuapp.com/instruments/ncds_81_i/map/)  

Yes the import mappings issue was an issue with the input file thanks.

**Comment by HayleyMills** [comment]
Tested on staging and the questions inside loops are now appearing.
