### ISSUE TITLE
REACT: When updating statement construct labels they save but do not display as updated until you refresh

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#703]
I have been testing on https://closer-archivist-staging.herokuapp.com/instruments/bib_test_redcap/build/constructs/
e.g.
![image](https://user-images.githubusercontent.com/16664703/182590786-8f6499ef-0a80-44cc-b4f7-621e8eb77085.png)

For all other constructs any lablel updates are automatically shown on the construct view page
e.g.
![image](https://user-images.githubusercontent.com/16664703/182590899-34a530ca-9a6c-4a3c-919c-dfe5df483ceb.png)

**Comment by simonreed** [comment]
@HayleyMills this is now on staging

**Comment by HayleyMills** [comment]
Tested on staging and the updates are instant now.
