### ISSUE TITLE
REACT: Instrument sign-off is not working

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#704]
e.g.
Admin > Instrument > us_covid_q5 > edit > toggle Signed Off 

This shows an error and does not save. 

![image](https://user-images.githubusercontent.com/16664703/183060424-6a47620f-3cdd-4115-86c6-2a56b5bb14a5.png)

**Comment by simonreed** [comment]
@HayleyMills this is now fixed on staging.

**Comment by HayleyMills** [comment]
Tested on staging it is now signing off instruments (does not display build view) and unsigning off instruments without an issue.
