### ISSUE TITLE
REACT: Date response domains not appearing on the list and so cannot be edited or deleted

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#716]
Found by Brendan
e.g. https://closer-archivist-staging.herokuapp.com/instruments/bcs_covid_q1/build/
![image](https://user-images.githubusercontent.com/16664703/190457669-8956bc74-8e43-4b55-b177-657061d483f9.png)
There have been 4 dates created, but they cannot be seen in the list. They can be attached to questions, so the main issue is that it is not clear they are being saved and created, and then once they are created, you cannot edit or delete them, as they are not in the list. 

e.g. https://closer-archivist-staging.herokuapp.com/instruments/bcs_covid_q1/build/response_domains/
![image](https://user-images.githubusercontent.com/16664703/190457994-9d7c89f9-4565-4498-8a57-44582fa701c7.png)

There is also a typo in the numeric response domain on the build page! 
![image](https://user-images.githubusercontent.com/16664703/190458180-8fc0f81a-5e88-43d4-adef-44dd270a6846.png)

**Comment by simonreed** [comment]
@HayleyMills this is now on staging

**Comment by HayleyMills** [comment]
Tested on staging and the dates are now appearing in the list as well as the previously created ones. @simonreed there is still a typo on the build page though.
