### ISSUE TITLE
REACT: variables.txt is not loading correctly

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#717]
e.g. https://closer-archivist-staging.herokuapp.com/datasets/734/variables.txt?token=eyJhbGciOiJIUzI1NiJ9.eyJpZCI6NjcsImFwaV9rZXkiOiJjNWFhZTg4MjUzOTM0NjllODU5NSJ9.donSPbb8rCNs5S0tZDujkix-awvn_qaDj9ZW2aFiqu4

It should look something like this
![image](https://user-images.githubusercontent.com/16664703/191970795-889eee1a-c8a2-40f5-9742-8131d548b780.png)

But it looks like this 
![image](https://user-images.githubusercontent.com/16664703/191970858-c89d7e2e-ccc9-4e25-902c-023cbd6c8c05.png)

I can get the variables from the tv.txt and the backend so not high priority.

**Comment by simonreed** [comment]
@HayleyMills this is now fixed on staging

**Comment by HayleyMills** [comment]
Tested on staging and this is now loading okay.

**Comment by HayleyMills** [comment]
Tested on live archivist and it is not working? https://closer-archivist.herokuapp.com/datasets/1222/variables.txt?token=eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MywiYXBpX2tleSI6IjM5YjBhNjM5MGUyMGM2MzIyMjNmIn0.NwpBUhAnCQOQp8pyletxPE_blbpg-blbMWBMcaxpeDI

**Comment by HayleyMills** [comment]
Archivist hadn't been updated. This is working as expected.
