### ISSUE TITLE
REACT: Can the sign-off instrument make the instrument read only rather than removing the buttons

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#720]
It would still be good to access the build page to view summary tables etc. even when the instrument has been signed off. Can we stop the instrument being edited and maybe grey out the buttons rather than removing them?

**Comment by simonreed** [comment]
@HayleyMills this is on staging, you can view build pages but you can't submit the form to make changes. We also display a clear banner to indicate that you're in read only mode.

<img width="1507" alt="Screenshot 2022-11-25 at 14 49 08" src="https://user-images.githubusercontent.com/13276/204008947-accffd31-af0a-499a-8ec3-4fc2b7b3147e.png">

<img width="1500" alt="Screenshot 2022-11-25 at 14 49 26" src="https://user-images.githubusercontent.com/13276/204009123-0bad1f47-ca0d-45c9-afa2-7175478763ec.png">

**Comment by HayleyMills** [comment]
Tested on staging and this is working really well.
