### ISSUE TITLE
REACT: More detailed error messages needed when an instrument does not load. 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#721]
e.g. https://closer-archivist-staging.herokuapp.com/admin/imports/574

"Invalid : Validation failed: Literal can't be blank" Can this list where these literals are? It is impossible to locate where this issue is to resolve it. 

[cls_covid_q3.txt](https://github.com/CLOSER-Cohorts/archivist/files/9733705/cls_covid_q3.txt)

Any ideas on why this is failing?

**Comment by simonreed** [comment]
@HayleyMills this is now on staging

**Comment by HayleyMills** [comment]
This is working really well, tested on a couple of instruments importing on staging to test different errors and is much clearer and easier.
