### ISSUE TITLE
REACT: Instruments not deleting on the front end

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#722]
When I delete an instrument there is no indication it is deleting or that it has completed. When I check the database, I can see it has deleted but it still remains on the front end. Is there an additional table that has been created which is not being deleted, as I am still able to view the Edit page of the instrument, but as you would expect, none of the other pages (build, view) will load as there is no content for these. 

This applies to both the live and staging

e.g. onsls_11_hhe_copy

**Comment by simonreed** [comment]
@HayleyMills this is now fixed on staging

**Comment by HayleyMills** [comment]
Tested on staging and the instruments are being removed from the list.

**Comment by HayleyMills** [comment]
Tested on main Archivist and instruments are not being removed from the cache again e.g. 
ncds_04_cai_test
ukds_91_census

**Comment by HayleyMills** [comment]
Archivist hadn't been updated. This is working as expected.
