### ISSUE TITLE
REACT: Export/import should always be valid

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#723]
There are examples of instruments which are being exported with no issues, but which will not import. Can we add additional checks or validation to ensure that it is not possible for an exported intrument not to be imported? 

e.g. attached xml exported from live will not import into staging. I think this is a content issue (as other instruments import), but cannot find the issue. 
[cls_covid_q3.txt](https://github.com/CLOSER-Cohorts/archivist/files/9754836/cls_covid_q3.txt)

https://closer-archivist-staging.herokuapp.com/admin/imports/568

**Comment by HayleyMills** [comment]
There is an issue with the exporter not exporting a literal and so is null when trying to import https://closer-archivist-staging.herokuapp.com/admin/imports/580

This could be an issue with a special characters? It looks like this in the db - 
![image](https://user-images.githubusercontent.com/16664703/200896101-a5ddd8e2-ed8a-48c6-bec5-983af86a59fc.png)

Ideally an instrument shouldn't be exported if it's not possible to be imported- any ideas on the best way to deal with this?

**Comment by HayleyMills** [comment]
I will add to list of checks to perform on the Gitlab exporter.

**Comment by spuddybike** [comment]
Dealt with elsewhere, content issue
