### ISSUE TITLE
REACT: New accounts can see admin view even though they are editors

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#725]
When I create a new account it creates and logs in to the account, but the new account has access to the admin pages? When I check the users the new account - it is set to an Editor and so shouldn't be able to see the admin.

**Comment by simonreed** [comment]
@HayleyMills If I create a new user through the signup link (from the login page) then it creates an account and logs me in but I can't see the admin pages and if I go the admin url (by typing it in) then it still redirects me to /instruments so it doesn't give me access.

Could you give me steps to replicate this?

**Comment by HayleyMills** [comment]
That's weird, this is what I'm going...
does this video work? https://user-images.githubusercontent.com/16664703/201053595-3fc1a729-299d-4d11-a69f-b60197b993c8.mp4

**Comment by HayleyMills** [comment]
I think this is an issue with my browser When I try in chrome or firefox ingonito it doens't login as an admin. Therefore I don't think this poses a real issue, since this will only happen if someone is using firefox and has admin permission on the account anyway. It is strange though. I can look into further @simonreed but I couldn't find the 'whoami.json'?
