### ISSUE TITLE
REACT: When creating a new item the form is not resetting to a blank form

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#726]
After clicking submit, the question should be entered and a new blank form should appear. This is not the case, the label and response domain are still populated from the previous question. Even when you click + QUESTION ITEM a new form does not appear. 

![image](https://user-images.githubusercontent.com/16664703/195644030-bd398a39-c575-4567-a728-4169a0f1d2ba.png)

This is also the case for question grids 

![image](https://user-images.githubusercontent.com/16664703/195805442-1c8eb4c3-8789-49d4-b843-9a93e7a4825b.png)

**Comment by HayleyMills** [comment]
Even when the + QUESTION ITEM is clicked - it still doesn't reset.

**Comment by simonreed** [comment]
@HayleyMills this is now fixed on staging.

**Comment by HayleyMills** [comment]
The numeric and date responses are no longer resetting.
