### ISSUE TITLE
REACT: Issues with duplicate categories

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#734]
cls_covid_q3 was not loading because of a duplicate category label. 

https://closer-archivist-staging.herokuapp.com/admin/imports/578 

This is partly because because of the way the parser rationalised the categories on input to the db, and the way the importer treat carriage returns. On input these categories have been treated as different and so has created two categories (usual behaviour is that only one category is created per questionnaire if they are identical). Whereas, the importer is treating them the same, which is causing issues with duplicate labels. 

I'm not sure how it was possible to load the categories into the database if it technically invalid?

"Live here rent-free, including rent-free in relative&#39;s / friend&#39;s / employer’s property; exclude squatting"
"Live here rent-free, including rent-free in relative&#39;s / friend&#39;s / employer’s property; exclude
squatting"

Is there anything we need to do for this - or is it likley a one off? 

Relates to #259, #723 #729

**Comment by spuddybike** [comment]
content issue
