### ISSUE TITLE
REACT: Not all topic mappings are being inherited

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#738]
For example see mcs4 question - variable mapping in the map view 
https://closer-archivist-staging.herokuapp.com/instruments/mcs4/map/

It shows qc_BCHK is linked to DPBCHK00 and qc_BCHK is mapped to topic 'Household composition'. Therefore I would expect DPBCHK00  to have inherited the topic 'Household composition'. 
https://closer-archivist-staging.herokuapp.com/datasets/736 

See [all_mappings.txt](https://github.com/CLOSER-Cohorts/archivist/files/10004236/all_mappings.txt) for the list of variables which do not have topics, but which are linked to questions which are mapped to topics.

**Comment by simonreed** [comment]
@HayleyMills  Fixed on staging

**Comment by simonreed** [comment]
<img width="1498" alt="Screenshot 2022-11-22 at 18 38 57" src="https://user-images.githubusercontent.com/13276/203394954-7d83b054-2d84-4147-9614-7cf8092f2b78.png">

**Comment by HayleyMills** [comment]
Tested on staging and this is working both ways.
