### ISSUE TITLE
REACT: Variable mappings not displaying

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#747]
e.g. tv.txt file shows that variable CW1_FRTVEGSP is mapped to 11606, and this variable is used as a source for CW1_FRTVEGPP, which shows it has resolved the topic from CW1_FRTVEGSP, but CW1_FRTVEGSP doesn't show a topic?

https://closer-archivist.herokuapp.com/datasets/1222
![image](https://user-images.githubusercontent.com/16664703/202698992-733b9628-33e2-4cd9-b667-fcbf0c854dff.png)
[tv.txt](https://github.com/CLOSER-Cohorts/archivist/files/10040976/tv.txt)

**Comment by HayleyMills** [comment]
Also the 'resolved from' text doesn't look correct? e.g. CW1_SHIELD was mapped to a topic and so the question should show the topic being resolved from the variable as below - this is correct 

![image](https://user-images.githubusercontent.com/16664703/202699713-9e3e0898-bb62-4a1f-8c4c-0f45e1bbf431.png)

However, the variable shows the topic being resolved from the question - which is not correct
![image](https://user-images.githubusercontent.com/16664703/202699858-4f01ec40-d1c7-49a1-bda9-fa798c176c67.png)

**Comment by simonreed** [comment]
@HayleyMills  Fixed on staging

**Comment by HayleyMills** [comment]
Tested on the staging and the 'Used by' doesn't look correct? 
Staging: 
https://closer-archivist-staging.herokuapp.com/datasets/735
![image](https://user-images.githubusercontent.com/16664703/203523989-c6511775-3db1-4c72-91c8-637339a0dcaa.png)

Live:
https://closer-archivist.herokuapp.com/datasets/1222
![image](https://user-images.githubusercontent.com/16664703/203524099-af11004e-301b-4297-a31e-5a054ed4a487.png)

**Comment by HayleyMills** [comment]
Tested on staging, still not sure this is working? Although I may be doing something wrong. 
e.g. https://closer-archivist-staging.herokuapp.com/datasets/735
![image](https://user-images.githubusercontent.com/16664703/203525570-b9fc67e3-25f4-4755-b12c-80f20984544d.png)
CW1_FRTVEGPP has no inherited topic, but it does have a topic in the tv.txt? 
https://closer-archivist-staging.herokuapp.com/datasets/735/tv.txt?token=eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MTE0LCJhcGlfa2V5IjpudWxsfQ.Yk5GgDOOZOVggBbpabGmdK5VqOrewJKyHdYnn-WHNi8

**Comment by simonreed** [comment]
@HayleyMills fixed now on staging

**Comment by HayleyMills** [comment]
Tested on staging, and this is now working as expected.
