### ISSUE TITLE
REACT: Typo on build page

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#752]
There is also a typo in the numeric response domain on the build page!#

Would be good to fix as we are demo-ing Archivist next week. 

![image](https://user-images.githubusercontent.com/16664703/203756988-c608e48a-13b5-4f3a-95fb-b4eb8f2ed0e4.png)

**Comment by simonreed** [comment]
@HayleyMills fixed on staging
