### ISSUE TITLE
REACT: >admin>instruments>exports

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#771]
XML Exports
Firstly, can I double-check that this is a history of each instrument export, so we can back to a previously exported if needed?
Secondly, the links are not working 
e.g.
https://closer-archivist-us.herokuapp.com/admin/instruments/us5/exports
directs to https://closer-archivist-us.herokuapp.comundefined/

and it cannot find the site.

**Comment by simonreed** [comment]
Yes this is the history of all the exports for that instrument so you can go back and view the previously exported versions.

I'll fix the links now.

**Comment by simonreed** [comment]
@HayleyMills this should be fixed on staging

**Comment by HayleyMills** [comment]
Tested on staging and this is now working.
