### ISSUE TITLE
REACT: nshd_65_sq instrument will not export

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#772]
The export is working, but the actual export pages are not loading. - The page you were looking for doesn't exist.
https://closer-archivist.herokuapp.com/instruments/1329/export/9538
https://closer-archivist.herokuapp.com/instruments/1329/export/9537

**Comment by simonreed** [comment]
@HayleyMills this has been fixed as part of 824

**Comment by HayleyMills** [comment]
Tested on staging, will test the example above when rolled out to other instances.

**Comment by HayleyMills** [comment]
The exports are now working.
