### ISSUE TITLE
REACT: Error with DDI import

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#773]
Do you know what the error "Record Invalid : undefined method `at_xpath' for nil:NilClass" means?

We have received this error for several instruments e.g. https://closer-archivist-staging.herokuapp.com/admin/imports/675

It appears to be stuck at constructs.

**Comment by simonreed** [comment]
Don't suppose you have the original xml file for me to test with? I realise it was 2 weeks ago now.

**Comment by HayleyMills** [comment]
[alspac_00_foa9yo.txt](https://github.com/CLOSER-Cohorts/archivist/files/10911918/alspac_00_foa9yo.txt)

**Comment by HayleyMills** [comment]
This is now working importing without any issues.
