### ISSUE TITLE
TEMP: it is not the latest version of Archivist.

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#774]
There are some bugs which have been resolved on staging and rolled out to other versions, and so I don't think this is the most up to date version?

**Comment by simonreed** [comment]
@HayleyMills the latest version should now be on temp

**Comment by HayleyMills** [comment]
I'm not sure it is, as it it doesn't match the staging or live ? e.g. code list page has 'submit' instead of 'save'.

**Comment by simonreed** [comment]
Sorry I merged in the `master` branch instead of `develop`. The forms now have 'save' instead of 'submit'.

**Comment by HayleyMills** [comment]
Yes this is the latest version now.
