### ISSUE TITLE
Temp: Error text showing

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#775]
Temp
![image](https://user-images.githubusercontent.com/16664703/222498619-600296c7-d693-46de-8891-e8cfd6b3a903.png)

vs 
Staging
![image](https://user-images.githubusercontent.com/16664703/222498809-ccaecf79-2cb4-44f4-95ef-2846e2d6505a.png)

**Comment by HayleyMills** [comment]
To add to this, when I add correct information and save it, then edit to so it is incorrect, the error message shows this
![image](https://user-images.githubusercontent.com/16664703/222727531-7ac53889-6057-4bd4-8d3f-fd183f8cc907.png)

**Comment by simonreed** [comment]
this should now be fixed on staging

**Comment by HayleyMills** [comment]
Tested in staging and this is working now.
