### ISSUE TITLE
Temp: Resolved topic from variables not showing topic in map view

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#777]
e.g. 
![image](https://user-images.githubusercontent.com/16664703/222753658-a6db53c1-b0d6-4b06-bb11-2c7b4c632366.png)

compared to 
![image](https://user-images.githubusercontent.com/16664703/222753696-10c268c1-708a-4719-b64a-dffdc973fbd4.png)

**Comment by simonreed** [comment]
@HayleyMills this is now fixed on temp

**Comment by HayleyMills** [comment]
The dataset map view now has very assigned topic as being a resolved topic? It should only be a resolved topic if the source already has a topic. You can see the question map view shows these do not have a topic assigned and these are resolved from the variables which is correct. 

https://closer-temporary.herokuapp.com/datasets/11
![image](https://user-images.githubusercontent.com/16664703/223145555-4b01aebc-7e8d-4afb-832f-34894f4a809c.png)
![image](https://user-images.githubusercontent.com/16664703/223145861-b29753ae-6ddf-4647-a932-6d09040e4b42.png)

**Comment by HayleyMills** [comment]
Also something strange happening here? It says it is already associated with pregnancy which is correct, but it is showing that it is resolved from Age? (the question mapping, wasn't previously set to Age). 
![image](https://user-images.githubusercontent.com/16664703/223147795-34481123-cd7c-45c3-9abc-7e93dd99cf3e.png)

**Comment by simonreed** [comment]
Both of these issues should now be fixed.

> Also something strange happening here? It says it is already associated with pregnancy which is correct, but it is showing that it is resolved from Age? (the question mapping, wasn't previously set to Age). ![image](https://user-images.githubusercontent.com/16664703/223147795-34481123-cd7c-45c3-9abc-7e93dd99cf3e.png)

we've now got the following on temp

<img width="1471" alt="Screenshot 2023-03-07 at 11 43 44" src="https://user-images.githubusercontent.com/13276/223412739-e1268bab-ce8c-492e-9a45-15d555569663.png">

<img width="1376" alt="Screenshot 2023-03-07 at 11 43 55" src="https://user-images.githubusercontent.com/13276/223412774-59dba4da-e4a3-4c31-8f52-af996f439764.png">

**Comment by HayleyMills** [comment]
Tested in temp and this appears to be working as expected.
