### ISSUE TITLE
Temp: Derived variable not inheriting the topic

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#778]
e.g. 
![image](https://user-images.githubusercontent.com/16664703/222772038-92b1f30e-4b3a-47ff-b1ea-4d9ad86b0c26.png)

should be
![image](https://user-images.githubusercontent.com/16664703/222772093-81324cab-d86a-46f0-a9a0-0b187555b42b.png)

**Comment by simonreed** [comment]
@HayleyMills this is now fixed on temp

**Comment by HayleyMills** [comment]
Tested on temp and derived variables are inheriting the source topic.
