### ISSUE TITLE
Temp: Not sure export xml is working as it didn't import?

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#779]
Exported alspac_00_ayc as DOWNLOAD EXPORT and DOWNLOAD COMPLETE EXPORT. The complete export has loaded into staging 
[alspac_00_ayc_test_all.txt](https://github.com/CLOSER-Cohorts/archivist/files/10884664/alspac_00_ayc_test_all.txt)
https://closer-archivist-staging.herokuapp.com/admin/imports/689

but the other export has an error related to heaf?
[alspac_00_ayc_test.txt](https://github.com/CLOSER-Cohorts/archivist/files/10884671/alspac_00_ayc_test.txt)
https://closer-archivist-staging.herokuapp.com/admin/imports/690

I can test with other instruments if needed?

**Comment by simonreed** [comment]
It appears to be failing because category `urn:ddi:uk.mrcleu-uos.heaf:heaf_13_base-ca-000490:1.0.0` already exists in the database for instrument https://closer-archivist-staging.herokuapp.com/instruments/heaf_13_base.

That seems like a valid error?

**Comment by HayleyMills** [comment]
That is a valid error, except the xml I'm importing is not heaf! As you can see from the .txt file above it is urn:ddi:uk.closer:alspac_00_ayc_test-ddi-000001:1.0.0

**Comment by simonreed** [comment]
I'm confident this is an issue with the export rather than the import, as you point out it shouldn't have heaf categories in the export at all.

**Comment by simonreed** [comment]
Can we retest this. Now the non complete export no longer has references to another instrument.

**Comment by HayleyMills** [comment]
Yes it has imported sucessfully https://closer-archivist-staging.herokuapp.com/admin/imports/691
