### ISSUE TITLE
REACT: Resolving topics for questions linked to variable with a resolved topic

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#780]
https://closer-archivist-staging.herokuapp.com/instruments/ncds_81_i/map/
https://closer-archivist-staging.herokuapp.com/datasets/695
Questions _4 and _5 are linked to n4140 which has inherited a topic from the question _4
![image](https://user-images.githubusercontent.com/16664703/223415246-0d3ebec7-d409-4220-b8b3-77951cd9dfba.png)

Since the variable mapped to question _5 has a topic (even it is one that has been inherited), I would expect the question _5 to inherit that topic as it is linked. 
![image](https://user-images.githubusercontent.com/16664703/223415463-f8f0335d-02aa-456a-9ad8-8ec19ee911d9.png)

**Comment by HayleyMills** [comment]
This is true for the reverse. If a variable is mapped to a topic the question inherits the topic, when another variable is mapped to that question, that variable should have the same topic

e.g. 
![image](https://user-images.githubusercontent.com/16664703/227255179-2df620ab-cb4d-4f52-9b2e-82f9054148a6.png)
![image](https://user-images.githubusercontent.com/16664703/227255244-b062301d-292b-45c1-860e-d976d1288153.png)

**Comment by HayleyMills** [comment]
Update, it looks like it is trying to resolve to the topic, but it disappears when you refresh e.g. 

![image](https://user-images.githubusercontent.com/16664703/233654022-2806fb02-88f1-4fdf-98ef-2fe9065f2d37.png)

**Comment by simonreed** [comment]
@HayleyMills this should be now be fixed on staging

**Comment by HayleyMills** [comment]
Tested on staging and the inheritance is now working as described.
