### ISSUE TITLE
Temp: dataset page pagination is hidden

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#789]
e.g. https://closer-archivist-staging.herokuapp.com/datasets/
![image](https://user-images.githubusercontent.com/16664703/223689283-6325c7c2-7483-4f00-8994-a6e3ba28f1ea.png)

It was like this 
![image](https://user-images.githubusercontent.com/16664703/223689448-5b8f2228-108c-49e3-8935-781640eebdd7.png)

**Comment by simonreed** [comment]
Not quite sure I follow, this is what I'm seeing at https://closer-archivist-staging.herokuapp.com/datasets/

![Uploading Screenshot 2023-03-08 at 10.45.27.png…]()
