### ISSUE TITLE
Temp: May be a one off- but bcs_covid_q2 is stuck on pending?

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#790]
https://closer-archivist-staging.herokuapp.com/admin/imports/

**Comment by simonreed** [comment]
Interesting, there is an instrument with that prefix already https://closer-archivist-staging.herokuapp.com/instruments/bcs_covid_q2/build/ was that there before the import do you know?

It might be that it's a duplicate and therefore isn't importing correctly. Though if that is the case then we should still be showing an error.

**Comment by HayleyMills** [comment]
I deleted the duplicate first. I think that instrument is the one it is trying to import, as it's the top of the list and doesn't contain anything? It was being strange in that normally when you click import it says 'created' it didn't say anything. It might just be a fluke, as it loaded into ONSLS fine.

**Comment by HayleyMills** [comment]
Will reopen if can replicate.
