### ISSUE TITLE
User groups not working

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#791]
User groups should be used to determine what instruments and datasets a user can see in Archivist, based on the Group they signed up with and the study of the instrument/dataset. This is no longer working (not sure how long this has been the case, it was working in the past). Now the user can see all the instruments but does not have access to the view or the construct pages.

**Comment by simonreed** [comment]
@HayleyMills this is now fixed on staging

**Comment by HayleyMills** [comment]
Tested on staging and this is now working, you can only see the studies based on the user group of the user account.
