### ISSUE TITLE
Archivist Staging having issues with importing

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#793]
https://closer-archivist-staging.herokuapp.com/admin/imports/

Lots of instruments importing stuck on pending and then failure due to "Record Invalid : OOM command not allowed when used memory > 'maxmemory'."

e.g. https://closer-archivist-staging.herokuapp.com/admin/imports/1114

I don't think this is related to the db size as most of the instruments were deleted before they were imported. 

They were imported using a script- as we needed to check that all the instruments would load before archiving. However, the same issue occurs when I try to one at a time manually. When I browse and select a file for import, when I click IMPORT INSTRUMENT it using says "Created", but this is not happening, and it get stuck on Pending.

**Comment by HayleyMills** [comment]
Tested importing an instrument which failed previously and it imported. Most likely related to RAM and importing too many at the same time. Next time the script is run, we need to increase the time between the imports. Simon investigating whether we can improve the status of pending when it has actually failed.

**Comment by HayleyMills** [comment]
Tried again today, and it's OOM again, there have been no other imports between the instrument importing above and this import, so I'm not sure what this would have happened? 
https://closer-archivist-staging.herokuapp.com/admin/imports/

**Comment by HayleyMills** [comment]
Tested importing 10+ instruments on heaf and onsls versions and there were no issues.

**Comment by HayleyMills** [comment]
Update - after Simon pushed the staging version to GH and deployed to HEAF and ONSLS. Same as latest update above.

**Comment by simonreed** [comment]
If you find this issue on Heroku then go and take a look at the redis component on Heroku. If the memory is at the limit then we can flush the redis db.

<img width="1318" alt="Screenshot 2023-04-21 at 17 14 36" src="https://user-images.githubusercontent.com/13276/233685083-cf901cd6-687f-430f-ae53-1fd7c55ba89e.png">

`heroku redis:cli --app closer-archivist-staging`

then run 

`FLUSHALL`
