### ISSUE TITLE
Code list category is not deleting correctly

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#794]
This is on live - created code list
![image](https://user-images.githubusercontent.com/16664703/227227689-c98d5da3-d6c6-43a6-8a91-30d919d6e74a.png)

Moved category and then deleted top category
![image](https://user-images.githubusercontent.com/16664703/227227893-7d933071-b316-4fb5-9636-e3cdb5cd5953.png)

The category is no longer correct
![image](https://user-images.githubusercontent.com/16664703/227228046-0e216a76-9169-4754-a3ce-c7c73fe7b66a.png)

**Comment by simonreed** [comment]
@HayleyMills I can't seem to replicate this locally or on staging, can you replicate on staging?

**Comment by HayleyMills** [comment]
Yes it is also happening on the staging.

**Comment by HayleyMills** [comment]
@simonreed is this on staging now?

**Comment by simonreed** [comment]
@HayleyMills Yes this is now on staging

**Comment by HayleyMills** [comment]
Tested on staging and this is now working as expected.
