### ISSUE TITLE
Temp: Issue with moving constructs

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#798]
Edited and moved constructs in main_test_prefix https://closer-archivist-onsls.herokuapp.com/instruments/main_test_prefix/build/constructs/

Which has resulted in most of the constructs disappearing. Only three constructs are in the construct view 
![image](https://user-images.githubusercontent.com/16664703/227244752-d6c429f9-caf2-4ba0-90f9-d99395795941.png)

However, there are several in the db. This is usually because the parent is missing, but in this case it looks like the constructs are parents which are not allowed e.g. the parent of the loop l_q12 is the question qc_test1 which is not possible. 

May have been caused when issues with #797 

![image](https://user-images.githubusercontent.com/16664703/227244884-6f384e93-3e28-46ef-bf67-1c126fc77580.png)

**Comment by HayleyMills** [comment]
I edited the constructs and then moved them, but I cannot replicate the problem.

**Comment by simonreed** [comment]
We're now stopping this happening in the Rails backend.

**Comment by HayleyMills** [comment]
Thanks. Since I can't replicate this, I will not be able to test.
