### ISSUE TITLE
Should it allow the deletion of a condition with constructs inside it?

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#80]
Archivist allows you to delete a condition, which then deletes everything inside of the condition- should only delete if it is empty.

**Comment by charlesdebarros** [comment]
Also deleting Sequences if they are empty.

**Comment by spuddybike** [comment]
A popup warning should appear if there are children, to make sure user confirms delete

**Comment by HayleyMills** [comment]
This was moved into In progress, has any progress been made? Otherwise I think this is more a nice to have?

**Comment by spuddybike** [comment]
@HayleyMills ready for testing on staging

**Comment by HayleyMills** [comment]
Tested on staging, and this is working great.

**Comment by HayleyMills** [comment]
Tested on live HEAF and this is working.
