### ISSUE TITLE
Build/questions change the text so it is clearer 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#802]
I'm not sure why the test stays Question Items? It is meant to say what type of question you are looking at when you click the link Question Items or Question Grids, as it always says Question Items, which is confusing. 

![image](https://user-images.githubusercontent.com/16664703/233294098-1a70cc45-f190-4912-9307-1dbe5814770c.png)

**Comment by simonreed** [comment]
@HayleyMills this is now fixed on staging

**Comment by HayleyMills** [comment]
This has been fixed on staging 
![image](https://user-images.githubusercontent.com/16664703/234329968-613fb213-edf6-44ba-9a69-1fa7e1c43c05.png)
