### ISSUE TITLE
Reader user should not be able to edit only view 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#807]
A user with a reader account should not be able to make any edits. This should only allow them to see the instrument doc view and the dataset view, or have be similar to when an instrument is locked (can see everything, but not edit).

**Comment by HayleyMills** [comment]
Cannot test until #834 resolved.

**Comment by simonreed** [comment]
@HayleyMills https://github.com/CLOSER-Cohorts/archivist/issues/834 show now be resolved on staging

**Comment by HayleyMills** [comment]
Tested on staging and readers can now only view datasets and instruments.
