### ISSUE TITLE
Adding a response domain to a question- difficult to see the 'add'

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#81]
When adding a response domain to a question and there is a long code list label, it extends across the white box, and so the add option is very far right and not within the white box (it is hard to see).

**Comment by charlesdebarros** [comment]
Screenshot

![pasted_image_at_2018-08-13__4_56_pm](https://user-images.githubusercontent.com/6763090/44043349-91159296-9f1a-11e8-96bd-7849de8df38d.png)

**Comment by HayleyMills** [comment]
This is no longer an issue in React version of Archivist.
