### ISSUE TITLE
React: It is not possible to edit a question grid without losing the response domains attached

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#811]
Spotted on live, but the behaviour is the same on staging. This may be related to #565 

The response domains are visible on the question grid, but as soon you click into any field to make an edit, the response domains disappear, so then if you save as is, it will lose them. If you refresh before saving (and lose the edits), then the responses appear back.

**Comment by HayleyMills** [comment]
e.g. https://closer-archivist-staging.herokuapp.com/instruments/us3_ysc/build/question_grids/ edit anything on any grid and the response domain disappears.

**Comment by simonreed** [comment]
@HayleyMills fixed on staging

**Comment by HayleyMills** [comment]
Tested on staging and the response domain no longer disappears.
