### ISSUE TITLE
Exported mapping files do not match

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#812]
qv.txt file (https://closer-archivist.herokuapp.com/instruments/1190/qv.txt?token=eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MywiYXBpX2tleSI6IjAxZThkMzU4NGQ3NzRmNmE2OTkxIn0.AXHvq-c3IFui0d3bq1hO7nIx9wrAWKHMxQaJMr7s4Zc) downloaded from instrument export doesn't match the allmappings.txt file downloaded from the instrument map view (https://closer-archivist.herokuapp.com/instruments/mcs_12_ts_e/all_mappings.txt?token=eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MywiYXBpX2tleSI6IjAxZThkMzU4NGQ3NzRmNmE2OTkxIn0.AXHvq-c3IFui0d3bq1hO7nIx9wrAWKHMxQaJMr7s4Zc).

The all mappings file doesn't contain all the question to variable mappings e.g.  qc_5_a-y$0;0 is not mapped to any variables whereas the qv.txt qc_5_a-y$0;0 is mapped to ~25 variables.  

This is on main live. I will try to recreate on staging.

**Comment by simonreed** [comment]
This is fixed on staging

**Comment by HayleyMills** [comment]
Tested on staging and it looks like it is working.
