### ISSUE TITLE
Cannot remove topic with conflict using the instrument map page

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#813]
https://closer-archivist-staging.herokuapp.com/instruments/mcs_12_ts_e/map/
qc_5_a-y is mapped to wellbeing via the TQ.txt. TV.txt was loaded and flagged a conflict https://closer-archivist-staging.herokuapp.com/admin/datasets/753/imports/1138 which is correct. However, when I try to remove the wellbeing topic in the map view (clicking x or choosing another topic), it loads the admin instrument view instead. When I go back to the map view no change has been made. 

This issue was on the main live version, but I have recreated on the staging.

**Comment by simonreed** [comment]
This is fixed on staging

**Comment by HayleyMills** [comment]
Tested in staging.
