### ISSUE TITLE
allmappings and cc_question txt remove carriage returns and ascii codes

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#819]
I realise this is a content problem, but is it possible to remove the additional carriage returns (new lines) from the .txt file?
e.g.
end of "qc_3$0;0 I understand that the information I provide in the HEAF COVID-19 study will be linked with information I provided as part of my involvement in the main HEAF study.	11615	cons3		3) I understand that the information I provide in"

[all_mappings.txt](https://github.com/CLOSER-Cohorts/archivist/files/13844188/all_mappings.txt)

This is adding an extra steps in reformatting before I can use the file.

**Comment by HayleyMills** [comment]
Can we also remove ascii character codes and replace with the symbols i.e. &#39; to '

For all_mappings.txt as well as cc_questions.txt

**Comment by simonreed** [comment]
This is now on staging

**Comment by HayleyMills** [comment]
The carriage returns have been removed from allmappings.txt. Ascii codes are still not appearing correctly &#39; has been replaced by â€“? cc_questions.txt seem to have symbols â€¦ ?

**Comment by HayleyMills** [comment]
Tested using https://closer-archivist-staging.herokuapp.com/admin/instruments/heaf_21_covid_q1/exports

**Comment by simonreed** [comment]
@HayleyMills can you retest on staging please

**Comment by HayleyMills** [comment]
It looks okay in Archivist, so I think the issue is when it is opened in Excel? 
[all_mappings.xlsx](https://github.com/CLOSER-Cohorts/archivist/files/14863495/all_mappings.xlsx)
[all_mappings.txt](https://github.com/CLOSER-Cohorts/archivist/files/14863496/all_mappings.txt)

**Comment by simonreed** [comment]
@HayleyMills I've now changed it on staging to download .tsv files which will open in Excel correctly

**Comment by HayleyMills** [comment]
Tested on staging and downloaded as tsv - there are still symbols when opening in Excel? 

![image](https://github.com/CLOSER-Cohorts/archivist/assets/16664703/69792a82-b9b0-45a1-9e38-2e079132a91c)

Tested using https://closer-archivist-staging.herokuapp.com/admin/instruments/heaf_21_covid_q1/exports
https://closer-archivist-staging.herokuapp.com/instruments/heaf_21_covid_q1/map/

**Comment by simonreed** [comment]
@HayleyMills can you test again on staging, I've now change the encoding again to handle this for Excel. Sorry I was using Apple Numbers and I thought it would work the same for Excel.

**Comment by HayleyMills** [comment]
Tested again as above, and it all looks okay now.
