### ISSUE TITLE
Cannot add a response domain to a question grid after it has saved without one. 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#82]
If to you save a qg without a response domain, when you edit it to add it later there is no add button. You can get around it by changing the column axis to something else and back again so the add then appears.

**Comment by HayleyMills** [comment]
The add button does sometimes appear now, but once a response domains is added it sometimes doesn't save e.g. bcs_75_hi qg_C2. There is no work aorund in this case.

**Comment by HayleyMills** [comment]
In addition (as discussed) it is not possible to replace or delete a response domain in a grid. Issue #119 may be related.

**Comment by HayleyMills** [comment]
High priority. You have to delete and recreate a grid in order to change the response domain. See bcs_75_hi.

**Comment by HayleyMills** [comment]
This is also true for question items. If you need to change one response domain you must delete all response domains, then save before adding them again.

**Comment by HayleyMills** [comment]
Tested on staging and it is working okay when replacing response domains in question grids and items. 
It is still not possible to add a response domain to a grid when saved without one.

**Comment by HayleyMills** [comment]
Tested on the live and it is no longer working.

**Comment by HayleyMills** [comment]
Test this again when Charles' latest update is pushed to the live (may need to rename the bug).

**Comment by HayleyMills** [comment]
Tested using https://closer-archivist-staging.herokuapp.com/instruments/1605/build/questions/question_grids/11283
I cannot add a RD to the grid, after it has saved without one - there is no 'Add' option.

**Comment by HayleyMills** [comment]
Tested on staging again, with same instrument. The edit button does appear once you have refreshed the page after saving. It would be great not to have to refresh if possible, but not critical.

**Comment by simonreed** [comment]
@HayleyMills sorry, when is the edit button missing? Could you give me some screenshots of the steps to replicate.

**Comment by HayleyMills** [comment]
This is a refresh problem related to #302 as this is not critical, I'm closing this issue.
