### ISSUE TITLE
Not possible to remove or change topics mapped to a grid

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#820]
e.g. 
https://closer-archivist-staging.herokuapp.com/instruments/mcs_12_ts_e/map/
Cannot remove or change topic 'School engagement' mapped to qc_3_a-e, it redirects to the admin dataset page for some reason.

**Comment by HayleyMills** [comment]
Found an example which is not a grid https://closer-archivist.herokuapp.com/instruments/mcs_12_sc/map/ Cannot remove None mapped to qc_22

**Comment by simonreed** [comment]
This is fixed on staging

**Comment by HayleyMills** [comment]
Tested on staging, and this is now working.
