### ISSUE TITLE
Importing mapping files stuck on running 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#821]
It is 'running' even though the process has ended (in sidekiq) and the mappings have uploaded. 
e.g. 
https://closer-archivist-staging.herokuapp.com/admin/datasets/754/imports

**Comment by simonreed** [comment]
This is now on staging but the previous imports will still be on 'running', new imports should finish.

**Comment by HayleyMills** [comment]
Cannot replicate this to test? What was the issue?

**Comment by simonreed** [comment]
This is hard to replicate as it needs a import to fail to fully test. Assigning this over to you @HayleyMills
