### ISSUE TITLE
Dataset view will not load

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#822]
Dataset view page will not load e.g. https://closer-archivist-wirral.herokuapp.com/datasets/32)](https://closer-archivist-wirral.herokuapp.com/datasets/32
I have loaded the same dataset into the staging and it is loading okay. https://closer-archivist-staging.herokuapp.com/datasets/755

Dataset view page will not load e.g https://closer-archivist.herokuapp.com/datasets/516

**Comment by HayleyMills** [comment]
Another example https://closer-archivist-staging.herokuapp.com/datasets/756

**Comment by simonreed** [comment]
@HayleyMills this has now been fixed on staging

**Comment by HayleyMills** [comment]
Tested on dataset 756 which is still not loading, does it load for you, or is there a specific issue with that dataset?

**Comment by simonreed** [comment]
@HayleyMills fixed something, can you try again please.

**Comment by HayleyMills** [comment]
Tested again, and it's loading thanks.
