### ISSUE TITLE
Instrument exports not viewable

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#823]
The instruments download, but are not viewable - "The page you were looking for doesn't exist."
e.g. https://closer-archivist-wirral.herokuapp.com/instruments/183/export/480

**Comment by HayleyMills** [comment]
@simonreed This is now the case for heaf, main, alspac, us and genscotland. It is now only working for staging and onsls.

**Comment by simonreed** [comment]
@spuddybike we'll need to deploy the change that's on staging to all the instances

**Comment by HayleyMills** [comment]
#772

**Comment by simonreed** [comment]
@HayleyMills this has been fixed as part of 824

**Comment by HayleyMills** [comment]
Will test when rolled out out other instances, but it is working on staging.

**Comment by HayleyMills** [comment]
Wirral, alspac, onsls, genscotland, us, heaf  and all downloads are working

**Comment by HayleyMills** [comment]
Reopening, although this was previously working, the export pages are now not loading again (at least for wirral). I don't think anything has changed since it was tested two weeks ago?
https://closer-archivist-wirral.herokuapp.com/admin/instruments/exports

**Comment by HayleyMills** [comment]
Issue on:
wirral https://closer-archivist-wirral.herokuapp.com/admin/instruments/exports
main https://closer-archivist.herokuapp.com/admin/instruments/exports


It is working on: 
alspac 
staging
genscotland
heaf
onsls
us

**Comment by HayleyMills** [comment]
So if I log out and login again it works - so as @simonreed says it relates to the token.
