### ISSUE TITLE
Instrument exports XML Export links not working

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#824]
Links on this page e.g. https://closer-archivist-staging.herokuapp.com/admin/instruments/mcs_12_ts_e/exports
"This site can’t be reached"
e.g. https://closer-archivist-staging.herokuapp.com/admin/instruments/mcs_12_ts_e/exports

**Comment by HayleyMills** [comment]
@simonreed document related issue. I could only find #268 which also relates to documents.

**Comment by simonreed** [comment]
@HayleyMills this is now fixed on staging.

**Comment by HayleyMills** [comment]
Tested on staging and this is now working.
