### ISSUE TITLE
Dataset mapping page - not showing all questions in the drop down

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#827]
So far only experienced in this case https://closer-archivist.herokuapp.com/datasets/1129, but will test further. 

![image](https://github.com/CLOSER-Cohorts/archivist/assets/16664703/1cb7c375-75ac-47fc-80d3-6062498cd500)

**Comment by simonreed** [comment]
This is fixed on staging

**Comment by HayleyMills** [comment]
Cannot test on staging, as cannot export the example from live yet.

**Comment by HayleyMills** [comment]
Tested on staging and this is now giving more options in the dropdown
