### ISSUE TITLE
Instrument map and dataset pages are not showing up topic conflict

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#831]
https://closer-archivist.herokuapp.com/datasets/1219
qc_s3_6 is mapped to EPSCS200 and EPSCSX00 which have different topics. 
![image](https://github.com/CLOSER-Cohorts/archivist/assets/16664703/8576732a-95a0-4d97-952c-921b3c22ee84)

![image](https://github.com/CLOSER-Cohorts/archivist/assets/16664703/21a2a373-e9e6-4a4e-875a-a32b86ac46ab)

**Comment by simonreed** [comment]
@HayleyMills this is now not showing this on product using the dataset provided, do we know of any other instances?

**Comment by HayleyMills** [comment]
I can't recreate this on staging, as I am unable to download the instrument XML needed.

**Comment by HayleyMills** [comment]
@simonreed this has been recreated on staging. https://closer-archivist-staging.herokuapp.com/datasets/742

The topics were applied to the variables first through the txt files, the qv mappings were applied through the text files, then I added the qc_SCSX2 and qc_SCSX manually. 

Note when I tried to add those same mappings manually (before I uploaded the qv txt files), it showed a conflict error related to the topic.

**Comment by simonreed** [comment]
@HayleyMills so are we saying that the conflict was added when uploading the qv mappings even though when you tried to add it manually beforehand you were correctly told it was a conflict?

**Comment by HayleyMills** [comment]
Yes that's correct.

**Comment by HayleyMills** [comment]
Tested again, and it will not allow me to select the question from the dropdown as it will cause a conflict.
