### ISSUE TITLE
Dataset mappings - source gives no options in dropdown

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#833]
In this example there are no options given when there are questions are mapped to Alcohol consumption. 
https://closer-archivist.herokuapp.com/datasets/1220
![image](https://github.com/CLOSER-Cohorts/archivist/assets/16664703/2d5886db-84b4-45f6-98ee-2e9331fba549)

**Comment by simonreed** [comment]
@HayleyMills can we test this on staging, I think it's been fixed by other changes.

**Comment by HayleyMills** [comment]
Cannot replicate issues on staging https://closer-archivist-staging.herokuapp.com/datasets/743 so it may have been fixed.
