### ISSUE TITLE
Download imported document

### ISSUE THREAD

**Issue by simonreed** [CLOSER-Cohorts/archivist#835]
You can now download the file when looking at the imports for a instrument mapping or DDI imports.

**Comment by simonreed** [comment]
e.g. https://closer-archivist-staging.herokuapp.com/admin/instruments/2369/imports/1205 or https://closer-archivist-staging.herokuapp.com/admin/imports/1214

**Comment by HayleyMills** [comment]
Tested on staging, and this new feature is there and is working.
