### ISSUE TITLE
Question Grids -  blank page when adding X axis

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#839]
When creating a grid, when I select a code list from the dropdown for the X axis, the page goes blank? This is not the case for the Y axis. 

https://closer-archivist-staging.herokuapp.com/instruments/alspac_17_la25/build/question_grids/

**Comment by HayleyMills** [comment]
Note that this instrument no longer exists as Archivist has just deleted it!

**Comment by simonreed** [comment]
@HayleyMills this is now on staging

**Comment by HayleyMills** [comment]
Is this question grid loading for you? https://closer-archivist-staging.herokuapp.com/instruments/test111/build/question_grids/15502

**Comment by HayleyMills** [comment]
Tested on staging, and this is no longer crashing.

**Comment by HayleyMills** [comment]
Was this pushed? This is happening again- I'll add what archivist and instrument when I know.
