### ISSUE TITLE
Adding a new category to a code list which has not been previously entered is awkward

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#84]
When using the autocomplete for adding categories, the only way you can type something new and not choose an option which is already there is by clicking somewhere else. Both tab and enter select the first category on the list. Would be quicker if only the keyboard could be used.

**Comment by HayleyMills** [comment]
Test this again in light of the other changes to the code list page.

**Comment by HayleyMills** [comment]
This is still the case, if there is a similar category already entered it will suggest this and if you don't want to select it then you have to click somewhere. Both the tab and enter select the highlighted suggestion.

**Comment by spuddybike** [comment]
I wonder if this related to Regis caches, move to redid project and test after that is done

======================
Lovingly typed on the iPhone
======================

**Comment by HayleyMills** [comment]
This is resolved with new React Archivist.
