### ISSUE TITLE
tq.txt export page is not loading for wchads_11_ph10mx

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#841]
This is on the wirrral instance. Error - We're sorry, but something went wrong.
If you are the application owner check the logs for more information. 

https://closer-archivist-wirral.herokuapp.com/instruments/182/tq.txt?token=eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MywiYXBpX2tleSI6IjBmNWFhYjg2ZDU0Y2EwNGI5NzU3In0.lQv1hslcZQ-AYzoHiG2sV_M8LzUFEPiFO_1_H8LXNLQ

**Comment by simonreed** [comment]
@HayleyMills this has been fixed and deployed to wirral, if we're happy we can roll this out to others.

**Comment by HayleyMills** [comment]
Thanks the page is loading now, but the mappings are not there - they are all 0? They were imported here https://closer-archivist-wirral.herokuapp.com/admin/instruments/182/imports/247. Will this affect anything else? 

Also not sure if this relates to #823 which I have reopened.

**Comment by HayleyMills** [comment]
#830 ?

**Comment by HayleyMills** [comment]
This is working okay now, so closing.
