### ISSUE TITLE
Constructs undefined

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#843]
From CA 
In alspac https://closer-archivist-alspac.herokuapp.com/instruments/alspac_16_la24/build/constructs/

![image](https://github.com/CLOSER-Cohorts/archivist/assets/16664703/ddc57933-6c91-4b86-aaa0-ecb9c2129adb)
![image](https://github.com/CLOSER-Cohorts/archivist/assets/16664703/7573f266-af19-4020-8d1e-cd1991514a31)

It doesn't look like they were constructs which were there before and have been edited (I've have checked past exports), it looks like they have just been created somehow?

**Comment by HayleyMills** [comment]
From JS- working in Main Archivist this morning on ns_04_w1 when I first loaded a construct tree I had constructs come up with a label of 'undefined' I reloaded the page and the tree populated with correctly labelled and filled in constructs.

Refreshing the alspac instrument doesn't do the same.

**Comment by simonreed** [comment]
It's strange behaviour because these 'undefined' constraints are not in the database.

**Comment by HayleyMills** [comment]
Cleared cache and it's okay now.
