### ISSUE TITLE
qv mapping - enforce dataset prefix from .txt 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#848]
The qv mapping file for import via Admin > Instruments > import, has four columns. For the instrument, questions, dataset and variable. The dataset prefix usually has to match the dataset which the variables are within. However, I loaded a qv.txt file with the dataset in the .txt as whii_89_hs, when no such dataset exists, however it found the variables. 

[whii_89_hs.qv_mapping.txt](https://github.com/CLOSER-Cohorts/archivist/files/15264369/whii_89_hs.qv_mapping.txt)
https://closer-archivist.herokuapp.com/admin/instruments/1543/imports/2536

and in the qv.txt to export it has the correct dataset
https://closer-archivist.herokuapp.com/admin/instruments/whii_89_hs2/exports

The datasets which are linked and have been mapped are labelled whii_89_hs and Wh2_phase_02_quest and Wh2_phase_02_events

**Comment by HayleyMills** [comment]
Can we enforce that it uses the dataset prefix from the file, rather than whatever it's linked to. As this will flag potential issues.

**Comment by simonreed** [comment]
@HayleyMills this is on staging.

**Comment by HayleyMills** [comment]
@simonreed  Tested on staging, and it's working as expected. One minor thing is the error message meant to say the what's in the file?
e.g. Wh2_phase_03 instead of (%{dataset)?
![image](https://github.com/user-attachments/assets/18a0a73c-735a-4a32-a938-c872a6a87991)

**Comment by simonreed** [comment]
@HayleyMills this translation error should be fixed on staging now

**Comment by HayleyMills** [comment]
Tested on staging and error message is correct.
