### ISSUE TITLE
Variable page - cannot remove topic from variable

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#851]
The X clear is not working. 
![image](https://github.com/CLOSER-Cohorts/archivist/assets/16664703/99f61099-4cc2-4150-bf66-c74a216c0be6)

**Comment by simonreed** [comment]
@HayleyMills what page is this on? it works on https://closer-archivist-staging.herokuapp.com/datasets/753

**Comment by HayleyMills** [comment]
This is working okay on all instances now,
