### ISSUE TITLE
0 vs 000 differnet behaviour on heaf instance 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#853]
Pulled out from #830

On staging 0 is loaded as no topic (https://closer-archivist-staging.herokuapp.com/admin/datasets/741/imports/1208), whereas in heaf it has loaded 0 to the None topic (this should be 000).

https://closer-archivist-heaf.herokuapp.com/admin/instruments/154/imports/159

https://closer-archivist-staging.herokuapp.com/admin/datasets/741/imports/1208

**Comment by simonreed** [comment]
@HayleyMills you're right the heaf database had the 'None' topic code the wrong way around. I've changed it to be code '000' for None as expected elsewhere.

**Comment by HayleyMills** [comment]
Tested on heaf and this is now the correct way round. e.g. https://closer-archivist-heaf.herokuapp.com/admin/instruments/154/imports/169

Assume the other DBs are okay @simonreed ?

**Comment by simonreed** [comment]
onsls was also the wrong way around but I've changed it. All the others are correct.

**Comment by HayleyMills** [comment]
Great thank you.
