### ISSUE TITLE
Updates to all_mapping.tsv

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#854]
1) Is it possible that the inherited topics from variables are also included in the all_mappings output?
e.g. qc_16$0;0 mapped to HLTHYR which has a topic of 10323, so qc_16$0;0  should show a topic of 10323
See attached file. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/qtnvmil/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/qtnvmil/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

Question name | Question text | Question Topic ID | Variable name | Variable Topic ID | Variable Label
-- | -- | -- | -- | -- | --
qc_16$0;0 | Over the last 12 months would you say your health has been? |   | HLTHYR | 10323 | Q16 State of health in the last year (S1)

</body>

</html>

2) Can we remove blank rows?
See attached file.

3) Related to 1) Is it possible that the grid question output shows the inherited topic applied to all grid cells in the output? A question grid can only have one topic linked to it (see tq which has only one topic for each grid https://closer-archivist.herokuapp.com/instruments/1537/tq.txt?token=eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MywiYXBpX2tleSI6IjY0YzNlN2U1MmVmZTYyYmMyMjM0In0.LeccWxLW8xJ68Ie94nTJZAU6HZf5gffFEvgrOuhd6j0) , but in the all_mappings output the grid cells are given and some of the question cells in the grid show they are not mapped to a topic and the overall grid reference e.g. qc_37_a-d$0;0 is also not mapped. This makes it look like there are some questions which are not mapped, when this is not the case. 
e.g. 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/qtnvmil/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/qtnvmil/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

qc_37_a-d$0;0 | If you are still having periods do you suffer   from any premenstrual symptoms? |   |   |   |  
-- | -- | -- | -- | -- | --
qc_37_a-d$1;1 | If you are still having periods do you suffer from any premenstrual   symptoms? Irritability |   | SYMIRRIT | 10316 | Q37a Suffer premenstrual irritability (S1)
qc_37_a-d$1;2 | If you are still having periods do you suffer from any premenstrual   symptoms? Swelling or weight gain (Bloated feeling) |   | SYMBLOAT | 10316 | Q37b Suffer premenstrual swelling (S1)
qc_37_a-d$1;3 | If you are still having periods do you suffer from any premenstrual   symptoms? Breast tenderness |   | SYMBRST | 10316 | Q37c Suffer premenstrual breast tenderness (S1)
qc_37_a-d$1;4 | If you are still having periods do you suffer from any premenstrual   symptoms? Other |   |   |   |  

</body>

</html>

4) Can the file include all the variables even if they haven't been mapped?  e.g. CPCONFJ3 is not in the file.  

5) Can the file include all the questions even if they haven't been mapped? e.g. qc_19_r

6) Can the output file also include the questionnaire prefix and the dataset prefix?

7) Can we change the order to;  
Dataset prefix, Variable Name, Variable Label, Variable Topic ID, Questionnaire prefix, Question Name, Question Text, Question Topic ID

Attached as .txt [whii_85_hs1_all_mappings.txt](https://github.com/CLOSER-Cohorts/archivist/files/15415999/whii_85_hs1_all_mappings.txt)

**Comment by simonreed** [comment]
@HayleyMills this is on staging, all the issues should be fixed.

**Comment by HayleyMills** [comment]
@simonreed Great thanks, tested on staging, the only one I think is not working is 3)?

**Comment by HayleyMills** [comment]
qc_37_a-d$0;0 - qc_37_a-d$1;4
![image](https://github.com/user-attachments/assets/833e5b28-3255-4b89-8da4-60ddc6da0a28)
is it possible for it to be more like this?
![image](https://github.com/user-attachments/assets/120ada49-ccd6-4716-b925-ec922a0fbf85)
[all_mappings (5).txt](https://github.com/user-attachments/files/17025490/all_mappings.5.txt)

https://closer-archivist-staging.herokuapp.com/instruments/whii_85_hs1/map/

**Comment by simonreed** [comment]
@HayleyMills this is on staging now

**Comment by HayleyMills** [comment]
Tested on staging and this is now working too.
