### ISSUE TITLE
Exporter not including all constructs

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#855]
xml export is missing question constructs e.g. Main alspac_covid_g0q4 -  qc_covid_s5_6_a_2 

Export attached as .txt

[alspac_covid_g0q4.txt](https://github.com/CLOSER-Cohorts/archivist/files/15435800/alspac_covid_g0q4.txt)

This is for both exports.

**Comment by HayleyMills** [comment]
xml exporter is missing instructions attached to question grids. The complete export does include the instructions e.g. sws_4_cq export includes the instruction reference urn:ddi:uk.mrcleu-uos.sws:sws_4_cq-ii-29362:1.0.0 but not the instruction. 

Export attached as .txt
[sws_4_cq.txt](https://github.com/user-attachments/files/15805373/sws_4_cq.txt)

Complete export attached as .txt
[sws_4_cq_complete.txt](https://github.com/user-attachments/files/15805379/sws_4_cq_complete.txt)

In order to use the export, I have edited the instrument to remove any additional items which are not used in the final constructs so I can use the complete export, so the export and complete export should be the same in this example, but this wouldn't normally be the case.

**Comment by simonreed** [comment]
@HayleyMills do we know a specific construct/type of construct that's not being exported. Some constructs are but I'm not sure which ones aren't being exported.

**Comment by HayleyMills** [comment]
Question constructs e.g. 
alspac_covid_g0q4 
qc_covid_s5_6_a_2

**Comment by simonreed** [comment]
@HayleyMills this has been deployed to staging.

**Comment by HayleyMills** [comment]
Thanks, unfortunately we cannot test this, as the same questionnaire is not on staging, and I don't know of an other example. Will need to test on main.

**Comment by HayleyMills** [comment]
Testing on live - exported and downloaded the instrument again (both version) and neither of them will load? 
https://closer-archivist.herokuapp.com/admin/imports/2789
https://closer-archivist.herokuapp.com/admin/imports/2790

Issue related to "No sequence found for instrument prefix" @simonreed

**Comment by simonreed** [comment]
@HayleyMills it's missing a sequence with the label of the instrument prefix, in the case of 2789 it's got `alspac_covid_q4` but that sequence should have been called `alspac_covid_g0q4_july`.

**Comment by simonreed** [comment]
When I make that change it imports successfully https://closer-archivist.herokuapp.com/admin/imports/2799

**Comment by HayleyMills** [comment]
Tested on production, xml exports with all constructs and imports successfully.

**Comment by simonreed** [comment]
I've done the same for the xml which was failing in import 2790 but is successful here https://closer-archivist.herokuapp.com/admin/imports/2802
