### ISSUE TITLE
variables.txt is downloading with a space instead of a tab

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#856]
Not sure why this has changed, but the first two columns are separated by a space and the rest are comma separated. 

e.g. 
[variables.txt](https://github.com/user-attachments/files/15805713/variables.txt)

Downloaded from here https://closer-archivist.herokuapp.com/admin/datasets/1429/exports

**Comment by simonreed** [comment]
This has been fixed on production as part of a previous deploy.

**Comment by HayleyMills** [comment]
Tested on live and it is all tab.
