### ISSUE TITLE
CC Questions .tsv remove extra spaces

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#857]
The rows sometimes include additional spaces at the start. 

e.g. saved as .txt to attach. 
[cc_questions (4).txt](https://github.com/user-attachments/files/15805910/cc_questions.4.txt)

downloaded from here https://closer-archivist.herokuapp.com/admin/instruments/whii_15_hs12/exports

**Comment by simonreed** [comment]
This has been fixed on production as part of a previous deploy.

**Comment by HayleyMills** [comment]
Tested on staging and the spaces have been removed.
