### ISSUE TITLE
Topic mapping conflict not showing in Map view until try to remove the topic

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#859]
![image](https://github.com/CLOSER-Cohorts/archivist/assets/16664703/5d91db31-e51d-4cc3-a9ec-036e44908dc3)

I know there is a conflict as it showed in the import mapping pages when I uploaded the tv.txt file, but didn't show in the map view, which is an issue. 
![image](https://github.com/CLOSER-Cohorts/archivist/assets/16664703/f85e09b9-5d7c-4c18-a916-c3d7aeb3bf4a)

Clicked x to remove finances and it saves
![image](https://github.com/CLOSER-Cohorts/archivist/assets/16664703/8be00a0f-0c73-4ed8-b43b-18401580fea9)

But then reverts back to finances and then does show an error, which should have been there before, but not after I removed the topic
![image](https://github.com/CLOSER-Cohorts/archivist/assets/16664703/4789a6f4-7f0c-4de0-9395-14bef1ecca6e)

I will try to resolve using the .txt files, and so will need to replicate on staging.

**Comment by simonreed** [comment]
@HayleyMills this will now show the validation error when you go to the instrument mapping page and there is a conflict, you no longer need to make a change to see it. This is on staging.

**Comment by HayleyMills** [comment]
Tested on staging, and the conflict error is appearing, when I click the x, the conflict is resolved as expected.

**Comment by HayleyMills** [comment]
Re-tested on another instrument, and it is not working as expected. 
https://closer-archivist-staging.herokuapp.com/admin/datasets/805/imports/1344
![image](https://github.com/user-attachments/assets/29e5e11e-a2d3-4a71-9010-98f027ae596a)

No conflict is shown on the variable view
![image](https://github.com/user-attachments/assets/9d077643-41b6-4da3-907f-9ba235775104)

No conflict is shown on map view
https://closer-archivist-staging.herokuapp.com/instruments/mcs2_new/map/
![image](https://github.com/user-attachments/assets/0583540c-3f8f-49a2-9764-76d2f2031caa)

Clicked the x and no topic is assigned
![image](https://github.com/user-attachments/assets/12195abc-3e5e-4624-9a96-aadf21b29ef8)

**Comment by simonreed** [comment]
There is no conflict shown on https://closer-archivist-staging.herokuapp.com/instruments/mcs2_new/map/ because the conflict was caught as part of the import. We now don't save the topic if there's a conflict so when you visit the map page there is no conflict in this case to show.

**Comment by HayleyMills** [comment]
Ok, I will make a note of this in the documentation, so we know this is the behaviour.
