### ISSUE TITLE
Exporter not including all instructions 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#860]
xml exporter is missing instructions attached to question grids. The complete (all) export does include the instructions e.g. sws_4_cq export includes the instruction reference urn:ddi:uk.mrcleu-uos.sws:sws_4_cq-ii-29362:1.0.0 but not the instruction.

Export attached as .txt
[sws_4_cq.txt](https://github.com/user-attachments/files/15805373/sws_4_cq.txt)

Complete export attached as .txt
[sws_4_cq_complete.txt](https://github.com/user-attachments/files/15805379/sws_4_cq_complete.txt)

In order to use the export, I have edited the instrument to remove any additional items which are not used in the final constructs so I can use the complete export, so the export and complete export should be the same in this example, but this wouldn't normally be the case.

**Comment by simonreed** [comment]
@HayleyMills this has been fixed on staging

**Comment by HayleyMills** [comment]
Tested on staging and instructions attached to grids are exporting in both exporters. Will need to test again when deployed to main.

**Comment by HayleyMills** [comment]
Cannot test as issue with importer #838

**Comment by HayleyMills** [comment]
Tested on production and it has loaded the instructions on the grids as expected.
