### ISSUE TITLE
Issues importing instrument xml

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#861]
On the staging - In order to test #830 I downloaded the complete instrument of mcs_12_sc, I renamed the file and the prefix inside the file to mcs_12_sc_new. Tried to load several times and received the errors that it was a duplicate e.g. https://closer-archivist-staging.herokuapp.com/admin/imports/1345 as it was picking up the input of mcs_12_sc and it was also naming the file mcs_12_sc_complete.xml even though that was not what was uploaded. I managed to get it to load by renaming to test123 then back to mcs_12_sc_new - I have not been able to replicate this.  

The second issue is that it says the import is successful https://closer-archivist-staging.herokuapp.com/admin/imports/1351 - but it has only imported 11 out of 121 constructs. The constructs are in the xml
[mcs_12_sc_new.txt](https://github.com/user-attachments/files/16376862/mcs_12_sc_new.txt)

**Comment by simonreed** [comment]
@HayleyMills  We've now added logging to show the xml as it is loaded in https://closer-archivist-staging.herokuapp.com/admin/imports/1359

I've also fixed the issue where it wasn't looking for the top sequence successfully. I've re uploaded this as mcs_12_sc_new_re on staging.

**Comment by simonreed** [comment]
@HayleyMills this is on staging can we retest

**Comment by HayleyMills** [comment]
Tested on staging and the instruments loaded successfully and had all the constructs.

**Comment by HayleyMills** [comment]
Note that if it fails, it will no longer load the failed instrument.
