### ISSUE TITLE
Renaming instrument prefix doesn't update the matching sequence- knock on effect with exporter/importer

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#862]
If you edit an instrument and change the name of the prefix, it doesn't automatically update the matching sequence labelled after the prefix- this might cause issues with the way the exporter/importer now works see https://github.com/CLOSER-Cohorts/archivist/issues/855#issuecomment-2260707569

Note that the 'top sequence' (the first sequence visible and with a label) is created automatically from the prefix when a new instrument is created.

**Comment by simonreed** [comment]
@HayleyMills this is now fixed on staging. Note however, this is for when an instrument prefix has been changed. It will only update the sequence IF the label matches that of the old instrument prefix. 

If say you've previously changed the instrument to 'test_prefix_new' from 'test_prefix_old' but the sequence wasn't called 'test_prefix_old' when making the instrument prefix change it will not update the sequence label.

Hope that makes sense.

**Comment by HayleyMills** [comment]
@beckyoldroyd will you be able to test this please?

**Comment by beckyoldroyd** [comment]
@simonreed I've tested this on staging - I created a new instrument, checked the instrument prefix matched the prefix sequence, changed the instrument prefix, and then checked that the prefix sequence changed to match (it did).
