### ISSUE TITLE
Can't "create new export" for gs_08_pcq5 in GenScot Archivist instance

### ISSUE THREAD

**Issue by beckyoldroyd** [CLOSER-Cohorts/archivist#864]
I can't "create new export" for gs_08_pcq5, which is in the GenScot instance of Archivist (https://closer-archivist-genscotland.herokuapp.com/instruments/).

This doesn't seem to affect any other instrument in this or any other instance of Archivist.

**Comment by spuddybike** [comment]
@beckyoldroyd can you check if this is now resolved?

**Comment by beckyoldroyd** [comment]
Tested and resolved @spuddybike @simonreed
