### ISSUE TITLE
Missing dataset on frontend, but in the db

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#868]
This maybe something I'm doing wrong - but can you check that you can see the dataset 958 in the main Archivist - frontend and in the db? I can only see it in the db and not the frontend?

**Comment by spuddybike** [comment]
I can’t see itJonOn 15 Aug 2024, at 11:03, HayleyMills ***@***.***> wrote:﻿
This maybe something I'm doing wrong - but can you check that you can see the dataset 958 in the main Archivist - frontend and int eh db? I can only see it in the db and not the frontend?

**Comment by HayleyMills** [comment]
Can you send a screenshot please?

**Comment by spuddybike** [comment]
<img width="1339" alt="Screenshot 2024-08-15 at 13 09 59" src="https://github.com/user-attachments/assets/ecb9deff-5314-4ff4-b74a-1ee60e045381">
@HayleyMills

**Comment by simonreed** [comment]
This dataset is no longer on closer-archivist.herokuapp.com and all the datasets in the database are being displayed in the UI. I'm still looking at the reasons why the problem could have occurred but if you can find another missing dataset then let me know.

**Comment by HayleyMills** [comment]
Ok, so 958 is no longer in the db? I can't currently check, as I don't have the software. Ok will do.

**Comment by spuddybike** [comment]
issue with script removing redundant instruments
