### ISSUE TITLE
Cannot create new constructs on a new instrument

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#869]
This is on all versions of Archivist. It is likely to have been introduced when the changes to the 'top sequence', #862? as that was the last issue related to the construct page, but the creation of constructs was tested on the main/production, before it was rolled out to the other archivists and there were no issues.

**Comment by simonreed** [comment]
@HayleyMills I've found an issue where if you try to create a new construct with a label that already exists (e.g. the same as the prefix for the new instrument) that it fails but other constructs still are created. Is that what you're also seeing?

**Comment by beckyoldroyd** [comment]
Tested on staging and main Archivist instance. I can create new constructs on a new instrument, but I can't create a new construct labelled after the instrument prefix, so I can see the same behaviour as @simonreed
