### ISSUE TITLE
Instrument URN not exporting ID correctly

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/archivist#872]
The URN ID should be 6 characters long for 

An example output is 
wchads_08_ph07mx-in-178:1.0.0

It should be 000 padded
wchads_08_ph07mx-in-**000**178:1.0.0

This is affecting (not exhaustively)
- Instrument -in- 
- instruction -ii-
- codelist -cl-
- code -co-
- sequence -se-

Could a test be written to flush them out, check that this is enforced

**Comment by simonreed** [comment]
This has been deployed to staging

**Comment by spuddybike** [comment]
looks good
