### ISSUE TITLE
Archivist build behaviour is different from other Archivists? - New instrument error 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#873]
Identified by JL. Build archivist has an error when creating a new instrument. This means that the automated archivist tests fails. 
It does create a new one, but it gives an error, and doesn't take you to the construct page, like the other instances
![image](https://github.com/user-attachments/assets/c18a812e-3d0e-45d0-83ce-6f532e292ac2)

**Comment by spuddybike** [comment]
instance running on old version
