### ISSUE TITLE
Archivist build behaviour is different from other Archivists? - Cannot export instrument xml

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#874]
Identified by JL. Build archivist does not create any exports. This is causing problems with exporting xml from the parsers.

**Comment by HayleyMills** [comment]
https://dashboard.heroku.com/apps/closer-build

**Comment by simonreed** [comment]
@HayleyMills https://closer-build.herokuapp.com/admin/instruments/exports It should now be exporting, the issue was a lack of migration.

**Comment by HayleyMills** [comment]
Tested on build, and this is now working.
