### ISSUE TITLE
Pressing enter when entering a code list, it deletes the category.

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist#92]
When entering a code list and you press enter it deletes the previous row in the code list. Not sure if this is a feature or a bug?

**Comment by HayleyMills** [comment]
This is still the case, it deletes the first code list. Ideally the enter button would save the code list. 
The tab button works correctly.

**Comment by charlesdebarros** [comment]
Apparently buttons and hyperlinks work differently in AngularJS 1.5. When you create a button (<button></button>) and press enter in the text field immediately before, the enter action triggers the next function in line, in the Code List create and edit pages, it happens to be 'remove'. Had it been 'up' or 'down', it would perform those actions in the same way. 

If we change those buttons into hyperlinks (<a></a>) then this unwanted behaviour stops. I have made those changes.

@HayleyMills to QA and sign it off.

**Comment by HayleyMills** [comment]
Tested on staging and pressing enter will no longer delete a category, and it can be used to select an existing category from the drop down list which is good.
